---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-logs-s3-creds
  namespace: odm
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCkNWmyeCO3IMxWsyLxEdOnV6rfu3zAbJzJhLT5qElb6uj+QK69FChHnWL/+0PV3DUJYba4fpKbFd55cfz5JpDR798ieVX458i06mLUpTAGoUfsravhu3HxglDrbvZrxu91qaFqgpXYGGMzw1V29SI0O3YWDP7ytMxmm2oonDF2F+R+q3FmyQLFVf3XTaikGjuUSEfaqV1k3xUUs1AALIDKGACQcgyXtMxLHgXEQP95TSCCg4CepEMS1fHzjGwma6muTekWTK4hwzT7t35u4LyCjMOEU4NXW6T2UxBnAqSzK+Anb5eZRPj/MX0eW17w/vOSYjFgRAjLsIaXg5e4Q9JE6lmi5j3uTuuMI/vOHQPMyWm/pGUoPtfAbmos2oqiAbGEYiP60tRVqhEV7ekN0aHWF9vKMA+D0sv4qm6yQUX3fr8eg9reEakGI38sO7vTKGLDRRGwcegOnh9M+MQaj6/FWD2LTRjvD2gFJjY8GY4SUvPS4uFqP3BQQgeW0JYSWHyVylrebJ4yfX00nJM3NUZ/nxVPSqXafowcdOi6s4OVm8tZQbE+dYkuI0of/1JZ5o3pfe9itD0nqpViAAMj/ypxnkCDpsfHQ1dna51vvLCeoza1jwKumquLT4RYIrSydupSwZ7s1zicncbMlaZvGgSCCeUmpFzvY3ckF0xvf2nOwhVNatrHmpufJ2gcKKjllonwtqeLUNztv1D8E1opwjKpCulsNA==
    AWS_SECRET_ACCESS_KEY: AgB7iwLId90Y39E0FePIDW5iRwWD3KaPAYhcwwkUOxSH+LpTQodSP1JLqKejl0HjGVDDYKE8yyIDOoiKCLXR9m5ZQb8TCYLSg0FVrI46LQJNDkAUERl9I5DIEwogmfxut1sTIRjOVxb7+a9haS7Wc7+WMIAvHOUY+jBfhO8OrlcJAGJDWlxzibaoGHAYtyve3QNoaGLim2gPYtv6sxaF+LeLXe3/Bn8eoc3OJtwAIDH8O8WUGQmMos7nXd9oiYGoJWETJspfQ9GPKbcElO70hq8u+JffmXDCgzQMhIkHxxSo8Wi/tHCzP3aGGW2N0uMMUJtj1vIJveDpCwFUemna8uK/fAvXM76LppGNURgkmhDTx6hxghtCjRcxmopAOmXIm7a3YgQ1ltftXwpEvH0U9cCf2AHMldBKWEgvvY6hBH51xkE0ODBDNOB5TFUO0F7gbjxPzhfryPU1TcLa/DnWZmnfM39yqx2XXzo8r7uOhl1u+cdOQqnq0eDmRFpC9hoyyN5y/xSJWJ4G7OHY3HqIvUXVfEqE7k9/p7+YU6KF6GsKpPaxGM7hMgO5UoOHO4HdGVd2Ez+aI6La64qikdHIFn61nuj3y0dFdgWikU1yluAZdCb7Iszl0/RMAzpqvsBCWDaiEH88KSWaIZx+MBHlTYcTmzhb2obw+jwNLyUi6o14zhxKk0JPwwHt0xrZyvaC4mI19JYX6f/FyHlC+KzuQxoE1vdsJbk3MqPIsVstyAz7XwxlH8r1+zly
  template:
    metadata:
      creationTimestamp: null
      name: argo-logs-s3-creds
      namespace: odm
