---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-logs-s3-creds
  namespace: odm
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgC6CRpuUzCZwZ5gi2vlIWmyYzs6AM+8kIiiVQie98CqImOMo8+WfIipLCcDeDaklwmLZ82cdgyQZCPrv4p4hwGE55W/OZz2Cbn0ABvq8LtgepQfnGDZMVHgGB6ftDyoC8R4ynlRkq+hVZ86/Jozjvk0i0WMSBpGY79tQ8+1+gH9iSuobK/0CXNhelU0bGe2IIUiIqQtJhaFsRV1SETt0gOVoqgtSD54RuRTHcZeQO/XvmfU/4JPpLEC62Ia6fKrCCfYNINOBrXIXhbB0xFxM5e7JMnm7zFSXcLNYJd/2qJNzhU0pN0J4bAaArIEgeYV1vGi2DjLLCyrC2SPnnbReqf03Ykp8P4py7MKpxDgru4cfIqqDXrMDyk4baIRtHRSVaGSG7CVqXTMMME2pZz4Fbf1DTLqTPG4/dJKm7ZMJrLJVJGs+h0itH5SjC9fHQXrufmUY1s/AtbABU2LcpEkBtr31ESrRLF7xr2/ronSMdiXe0khVzih3BSziaE9NSSbRJBI6wrUTTsCfiO9sCv6rm8ziGHhd9IcU6YncSbRF4A4MQlHzIIZVEeBVDd0rMtiY2XpvTrxXdrzYbU41+n7fPvPAqVjjo0Hkc3jEuUzb7TcWcOPwtbCKJOJgsVS9a18IpnbGs//+4iYNdfYJ8xwEk9MUvzSyo6fICiolTl2ra7r5+wp9UD5lIrWBd1S3E6vEO26hKIEzaf9frPgn3koKK1s63Lj1A==
    AWS_SECRET_ACCESS_KEY: AgCbEUqOIYXRZo7yjylTunC/KdKvnRiAC8bS+XrANTCmVX7A2EJybBetwzyFGlzWQZXsxXsjdQ3F9dzNNLFN7Ooeum7NuwCALi9N2uiRwMS/IoL2Ws7UH6lMxJ/b8YLz5/3j1CSk8Y/21G4fFM/bMyEQFjQQdvtZY4qkDCRWVkwPP6tqMUJXKjdLApiHfnbbx9u1+2WkPGyhhjBPNrSc6JCgrFff+fmJmExRWKNqC7G9S16YA543bbTbO+DXysEoivc8/XpuNVJKIiRJ7piyVUxQMuK1sWkQHnGdlj2KBnZdJ6MgrtZLUCiTFSwxBVHZBKCkuD+/R9DyWZxIxx75DYP+lO5IWep8btN4ElKm4nK8Eca6Djl+DwVqs6pR/ys/GJ9pg7BtjEPAr63NfuEB8GAigqOLOjKtypUZtD9R+2T2W5orWt3eLg9mWMQCHZVN4Ye8mn0Z1EbhIt+dUIuyuAHiSpGBC2Xay46lJ+J/AjrtWZRHFmftRZZrTzjUoxOOuLLhYZ6SXAzfjYgToGJh2EtJ7MZ/fckLioTY3OISk61O8njvD0GwQEKE+awjPokjB+kpQJQTF9bJG6NJpj2KF3eWrqxmheVdkO+QrxFOApvTweXGn6NB0B53rTibKDBSGZ8kxzWPVIMLQ9OMkqd08DVB1Vb4l2MqGRmdOHLjee/yWr0OFcl32DO2cKMmfe8QuwfwUTPNAAD7nYz8TMFSH871/Jhmv6HNEP8K2qL8OvSXUcG2RmnGuaWy
  template:
    metadata:
      creationTimestamp: null
      name: argo-logs-s3-creds
      namespace: odm
