# Cost tracking
podLabels:
  project: fieldtm
  tool: fieldtm

replicaCount: 2

qfieldQgis:
  image:
    pullPolicy: Always
  # Temp fix until 2026.4.1 release with chart fix
  env:
    LOG_LEVEL: ""

existingSecret:
  name: "field-tm-prod-secrets"
env:
  DEBUG: "False"
  LOG_LEVEL: "DEBUG"
  PYODK_LOG_LEVEL: "CRITICAL"
  FTM_DB_HOST: "fieldtm-db-prod-rw.postgres.svc.cluster.local"
  FTM_DB_NAME: "field_tm_prod"
  FTM_DB_USER: "field_tm_prod_rw"
  # FIXME enable auth
  AUTH_PROVIDER: "disabled"
  # AUTH_PROVIDER: "hotosm"
  MONITORING: "sentry"
  OSM_URL: "https://www.openstreetmap.org"
  OSM_SCOPE: '["read_prefs","send_messages"]'
  RAW_DATA_API_URL: "https://api-prod.raw-data.hotosm.org/v1"
  ODK_CENTRAL_URL: "https://odk.hotosm.org"
  QFIELDCLOUD_URL: "https://app.qfield.cloud"
  # Temp solution until organisations can have external collaborators
  # on projects, despite not being in the organisation.
  QFIELDCLOUD_PROJECT_OWNER: "spwoodcock"

ingress:
  enabled: true
  className: nginx
  host: field.hotosm.org
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: field.hotosm.org
    external-dns.alpha.kubernetes.io/ttl: "300"
    # Increase timeout for task splitting large areas
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    # In case of large data extract uploads                                                                                       
    nginx.ingress.kubernetes.io/proxy-body-size: "30m"
  tls:
    enabled: true

resources:
  limits:
    cpu: 900m
    memory: 1.5Gi
  requests:
    cpu: 100m
    memory: 256Mi
