---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flyte-db-password
  namespace: flyte
spec:
  encryptedData:
    postgres-password: AgAYf9aJ5X63o9KfZ9PncZriOmde7rBIJT73tAzoyAfUxX3g5nerdaAFW0B4jh7sFGFJwHUZU1Vn+JGd+YZLrG3F4Rz5ZCTiyH4II2t1Y18QIv/nlIMlYyQphKB1ZkPSxA2ICe45oqH9r4d7HHhNo+zPDa0HFtv43ahDsPh7Ahd1H9wv7aW4hAzc1w2VivmMv+KbvPwshp2q+sga5D0oBshtzgOZncpS6DuRO1HOJM8pyiamM116/DlxUa4kWQKPyc4guDZE9GZHRSvgmrl2hu2lvFFihV8aAzcAYQBHudEZfhRX/4ml0FvN3gqZP6+oi4w+ZuiF8aHiq6MuTgqF+MSbelhhKU0eLeGIi1DGTwdpQ6g3O5b5JtPsZmduwMRFdXeQzBBLbRPyFhT8wc5blI60Z7PNrDUbTcKrwvSdlbpPNm8gAhvkIdvL4OZQdhFrzCTNrmkD7SzRThihT4aIY82C4WGuFF+99P6crDwTFfAxoPdxCAZVw//44TGAbJHo4DY3hjAcx+IeRL41Iuy17LotDbkVOoPUFo+JJth+u2XlNwMpzjLn17zdQL7EZDOzgbaF9VjAEk/xNIfjlUKIkWC0dQR0O3OHzL/00O7xP/v4rq/+78jAcDDeLysn0Jfd+bUHOvzuKlDMMdOxuCEoG3fpBe1KY9PyHUGPN+V/WZNqdqaxB2BZIN/ATuLhyc9SE9JkDqTkSkrMRzeA/5mkWG93nOVqNEnJaKBZFwvlB1jLC9O5dWD44yBmRH7dAsQp8J4Zy9yxhEr95kokWYLk0eDCUsP4+ado
  template:
    metadata:
      creationTimestamp: null
      name: flyte-db-password
      namespace: flyte
