apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenml
  namespace: zenml
spec:
  template:
    spec:
      containers:
        - name: zenml
          env:
            - name: ZENML_SECRETS_STORE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: zenml-extra-secret-env
                  key: ZENML_SECRETS_STORE_ENCRYPTION_KEY
