resources:
  - sealed-extra-secrets.yaml
  - orchestrator-role.yaml

patches:

  # Add custom labels
  - target:
      kind: Deployment
      name: zenml
      namespace: zenml
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/project
        value: fair
      - op: add
        path: /spec/template/metadata/labels/tool
        value: fair
