# Note here we use sync-wave -5 annotation to ensure this is applied BEFORE the zenml
# pre-sync db migration job, as it relies on the db secret being present
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zenml-extra-secret-env
  namespace: zenml
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    ZENML_SECRETS_STORE_ENCRYPTION_KEY: AgC+r9odaRc2yEFkg5jMhGs0z8qCQG3l/BlyW2zR5h5dfs105/aFSfop2bLTwepMR4XnSbUv8nYscfbHby2wshJjJCwLGjo+ZpQhMf9lVgS2m4zVykEJC4IsGUilg/ZeZ0j98woIK3GXWfpwtbc0XicwrN6tdGD42UgE6NvXtuAeXf4Gm0qSV6bhWajcipwfGgSnI6zV9X7bRnOkkYyiEtj4mrdHrKmQcrLMwSZQk6P68dn7r6xioxpx1ih7+o5nJ1HQ4Gnt5kxAW31gppzX0Jba8hd/fOO94DWxBNDwR5FGTCAH4uORegpTpYP+vBUfn+IP13BaavaUdhuwlFMm3CEwLVUHRXBbSmpIo9hG8L+kbfCYc6vlSkvxbQb3VZDVw+BrbpSyP09WQI0wmkENQsbQhNEU17ybowEl3le3/MjGV4GWnuZBDSPh50ASAA3IGf6tZtH8tbLlDzpIBfbpE49i/QHIVnf/oVKV8XfC4C001WHvcERNBke4e5C+9TGLMUQIuHtx+Y9Z5SfZYt2C2DDo8z8ILzfwQ6lFs/KQrsNsx1bUyDlfuC1V1wMhPKZcv/IAsfeuvkDoG1zJRsefZ4wFxONwFQkvIn88nyvyOlonWIg27sgwyUnvYOhWxgK7cy/xQNcfZGCs6ox8F2Yaf2v/66k5/bUidxT5Zj8ou1ucCpOpRz3YWTh0d2Y18AzX3gvPiKuDhIp5E6nyJxQYe5s9ZSCj5Ea6rdWKy92TmIuYILBplHYBsug1wg0pLp8gcp7OucnkWdCRCTAuVPp0dafd
    ZENML_STORE_PASSWORD: AgCsjygeS4d/QAjhqGKQNmSPMA9QZ2nFHBLNVkr5JEWNI2pusJeT7wbT4eTpABZqO7KUFG6BhzyOHp3QAjHMEt8qWQTIZ0KHY5r4IGR6GP8pbiwCe03EDDuAkGRMnOE7O5LzKoGRBFKmpedrv8ldwCprmhGbEYmxoqAMTJfzgv/6aB6Lu9MmZQRTVN2Wq7Gh5MC7jXB67IhWFCxzjWHlEdvygOHc9W7FXsjbEkWuHVmvBAu6k37IeVQXMCvhESDEajz/W3eGe9kLFLNPeyxAI9M1nca61/iVFFohjH5ajRvYZ2Rz5Dm+EXoqxI+4F+RGkR7kY4uSJ9N+p+zSUOo7VDMZFQNE++BUWemRooOdODUnLNV2u5ytlrXWdeXzgHc7jM4RzelzKTzjJ8ywigpoNRz46vnqsYShtrV64K0lGiy0/IvOXFo25eQqSogXDojAQZ0q6wKAH7K+oPD+OGauLxEySYo6kNL5Xqom0zfXh5Hlcis6B7t8y/Ik35iqkhbrI2hlDT498lBia6eNn2ZybQeXpnt5iqaHQ7gKFV8oGIJm6oNUAnT7wRSt9NUmGKPLbk+XmBU/AymGuJ3JR4sVO35+IUWmhI3KH3FL/hZ+R3539X4tcYCy5xoVJ1SPIwvWRmb7XiSkTxQY7+SEAvb7z0DeZy8xtIUV7gXgVjWW11fsEgAF6WDxmlEmEUfzhTQ+JyacBNSYgvLzRFMU99XKAS63Q3ww4010IWxzvpvPxYGaSM2/c1WqlaHyX7ize6OeYMEgw9pQoLpLP+HX0BJkCpaDw4W8KbYJ
  template:
    metadata:
      creationTimestamp: null
      name: zenml-extra-secret-env
      namespace: zenml
