apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-zenml-secret
  namespace: zenml
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-10"
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
      - name: wait-secret
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for secret zenml-extra-secret-env to exist and be unsealed..."
          MAX_ATTEMPTS=60
          for i in $(seq 1 $MAX_ATTEMPTS); do
            if kubectl get secret zenml-extra-secret-env -n zenml >/dev/null 2>&1; then
              echo "Secret zenml-extra-secret-env found!"
              # Verify the secret has the required key and it's not empty
              PASSWORD=$(kubectl get secret zenml-extra-secret-env -n zenml -o jsonpath='{.data.ZENML_STORE_PASSWORD}' 2>/dev/null || echo "")
              if [ -n "$PASSWORD" ] && [ "$PASSWORD" != "" ]; then
                echo "Secret contains ZENML_STORE_PASSWORD key with data. Ready for Helm deployment!"
                exit 0
              else
                echo "Secret exists but ZENML_STORE_PASSWORD key is missing or empty (attempt $i/$MAX_ATTEMPTS). Waiting for sealed-secrets controller to unseal..."
              fi
            else
              echo "Secret not found yet (attempt $i/$MAX_ATTEMPTS). Waiting for SealedSecret to be created..."
            fi
            sleep 5
          done
          echo "ERROR: Secret zenml-extra-secret-env not ready after $((MAX_ATTEMPTS * 5)) seconds"
          echo "This likely means the SealedSecret hasn't been unsealed by the sealed-secrets controller yet."
          exit 1
