---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-route53
  namespace: cert-manager
spec:
  encryptedData:
    access-key-id: AgAtZKtbjujvnT0yD5OZVaCqs/2uTxiJhUaLd4+6ilOL5pBMbDbQtdr7/CflzqapjG+uFGkdxbYOnu588PtSAiWL/EDS5FWetvbpVXnLR+f34noySiOSoto5D6POi4dbHPKyZ/qXis3la1JyyzzYaS8T13wLQjpOBFrLiStdRVScY8y/62/45fy5BxP0Z8Zu/2zr5TTCr6M7XOzVvbzCn6rup1T4SgBbEzMxC2FUJ8lGoUfTutDoaNdGT6wD/5BU4yQh5sLBE2jgb+gHhqY5lWJQrWpqz6SzyzoQ2J58MTKbe5L5l1ICp/2RgcOOo1ybFNdjlbLAR9PlNrIEFwX4CHtXSsSWnZ6DtzOi4PqDhLDzqiaujCi3ST84Rn735iAB4BPEVeonZrr47e4ANhxdCcS28ZSM6g/FUroGCBqoYj7wCMHHSjuqWh8xhjjLLARIrNMeHeyr2J6Z4sLXwHcCFkOfOpi4lRG6XEmOqL6PTM+Lcn9YrCdhkDcYk4lsNwK3SJwHG0eIPY1HdTJyMhNqWNxpPrOp+tcYi236KEGZV4HjyntKVOwNPWuZ+Q1ZA6IRNVrjW5+RsbcIOx/itK0rSlJkmsKoR9SAIxxE8PpBR+pOF1XeEPt0xeYWSPzomYeTVSgiXsSyxve3rgR++71Pvzlu1pLh8Lx6PE+LR069K8EWQL4A+nXGZ6LHlX0blUTIEg78TUTjGCEiQfZdWsvQdSjUy0Z01g==
    secret-access-key: AgBYlnQO2Udu3OWDN4omfWPkMDo6mfPDQhDkIGuR9rcGPfCLmzWGHnoDXzQpoPikzrmLZ2mBUOR1Yt8iyijqi9yHT6oI2jNKo5LizD3VI6D/vPNg2NObFyMV3sYjHUyWRz8w+0k3WGlRjlqAy2+W4RhNp7XSPcV8hSn7WYX3uWJEkvWnt52ng3u6aMhiZlGv3QKaviWmi3j+Jz3zpJJzp4RzNFbFtKKF03P3zxZpBuMlEOp6jEZtTZK41ysLLQIgk7Vn97BG/Cm+DWa8kQLRyIfWxwb2ZmO+z50waC2O213m8Hp5GP6dQkbRv7tL+Mi14TM8fi0g2q+G0YSFqFDLVuigfLLOdj1t8kRQsdMLZQMExjxmdH6wJitlSvJRmNmk9b4urdbfr/9GveHNRMiLsAk9Wr+5TGcjmEjSi8310vDIt7sAMjdk334ZAmQD4NWULXBf7S2aT4FP7hx5hP1WKEblyZuX712LaBfyzuFo6y3XJtv+o0l6XeTtcm6KMr6gH+pKHVPXX1lCwGbhBdltuPKx2ilgQlEuKI9c5KpVBPQsyipu/oo9r2lNbU0G0UQ9PPjKwL0TUMFcdbyHd9Ou/3YOERWndBFiR5Lcoy/6fDG5EBA/pAyCqvAe2nuHAp1OTClnVYNOApno7lHbgMNODgJMJuGYwdateSU9KQFN0L/kroKnjaHfpTgPrNtJTx6Su/I9GJSOLgYe291I6NKmn1j6fjOvYR32vHnfykBJAiTzwbIYHKxBGAxX
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager-route53
      namespace: cert-manager
