---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgCzLYPNUorBZVf+JSlD5ZBkbPp3mb8PbVpajjI4ScSc4ov6Ns1GdvB9z2CcUyFbgOSZ7BwPtvhaUzAs+zZa9qMGmkQ9uzvAtuhkHBGGJsa9g3FB26F/xdf6JvGyP3l2QfSE/moWD/YMtnEJaXDjqN3bQsLvL6x0zM/Gd1QohXYrX4R6c8HsOcXceZVtxW61bPIyf3oQIP4UuWKQy9IEaOv2B+8VYJOuUcWSkXpG5K44R4v1nJwfip358z7tE3h5mRQPwoh2PDcH0e+9gQy68K8UWRXOjtb7i6o85iXolUoh5G7ZS+y8uoBB75czYvtUnOiyD14lnkVQX10S/2N9coCasbNPYZB0nYsPRHYI54JVMuD/2PgWcu6t5Kqls4IiXl5/tlw+cv/EE0RK3DvxiUmBOJxMwctMyqcSVKDJ2V9NqumThW1hP022P43YF8X4UU5IKCHos69MBvq3DKmnlEDcvtqVBwXz+HfWW2L6SgxHcn2pD6lnTfJi9ahs+s/3LItmGjjYAh9FmT9agWHNwPprByWCLad5aLnGeE3l7PEfXWIHQEsl3yqp5B53eawtpfBuWeqLdt/VbcvqkFVJxrO+znyC+Pl0pST76Q9Gg5q3/FCmJFxjkeSehpYsMxsG8TwW5jnrEGk4+2k+qk1LtEJNZY2ZKYTIrvr218cTBtVv1/wavNTeQCnqMIYKbV2W+QPpPeVWKFsWd7AvUUcn9c1Lw2R6XehOEvKz7LT4byfxYPt7N+GF6sjUVG6SPcA46weLweQaz0slU/F6yyUC53hYVIzdHqc2YKnPU1UrOfUd
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack
      namespace: monitoring
