---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCEdBGKpkWv8AMZTyg4UaLPDrT+RHFFr7ZhX4Gb0oEbyxWOe0IqQmj3Oe3jLQRI0D7MgeLvbH6fyQJTn7ErJPzKPlEj1m32oA+ZT6YYpt2zV/R6JqQa5IsJQmge7TGWBGRuv1i8zWrVhPF5byrh3i94pHHIW0uMqjBZcvuHqhEtwBt0yIEC1gouKNzKnJpET0S/R/TzIme7yMaIcNjX9wTItWkIdpHqXzH8hivD/8GIZYhESVV6CCVnuCx/YnUU3ioOqeB3QofvKzofTvtQYN54AJLXs3hWJgUWWWhPCWz99WoJ3LLGEBaWDS7t0LIQ1XB9H9iCL5WGhmkzakr4AWEnm/V2p9JrGwKg7Yvvk1x3xfd07r3sn+GL38Fshaluy5q9fj9zGPR5xhjf4CoEHwFUeFAnOSxf4mlB/tfkaaS7NSQYEcoydb/WdVraJlRZtsdtngxiaHEQZV+WCoMupc9lJNPLCxKEiMYeCzwT04dbsDWNIo1xbvVas+8bMbcOQxgGVuB2gM3MTP4nktNJQcvNPhicj+zcPLPpDM/RxC4fm1VUiOIEp6+VLNWdSXIs24uuDjyiMclVonl6OpkPms5h1GUNvxn/ZK7d2lMFGUjw+iSR+/EglFAoMLOSlqDp24J2dR/5wrPL0U9nl2amlf4A9xKe3qyvsrjWhPZx+tyYAq7r9StyCNVvV1gGTh0j9WZaP8UDnHVPwi13EWdcKI9R7gV0ls4p01nZHSJ0v1J6Sxx7VK+Rt+ERUHQ9AJyYWNlua9+avN6SgGph4W8Ezj+HeD6I4oa7
    admin-user: AgCW3L3adScmwgrbUDsfk0nDkXnGnv+fgeU3moXAqbYJcxSVnoMnWR/33ezJF5NxiasV+/H+SZhauab3JghN2lDrTonihBYvuLgLma5gPLarmRKH2KHyKheXZfWCmrFGSNYObRlTBQ5Zl2HXNHq9hwzyuuMy5KiVpU66kX+a9CFYAGAHjz8zTQej5z0xIhliwBMmk/KmDRb8WLDkaJGBBeWZOGOC0Lb8r0CLa6OqsVdKvFzIc4qFS4pXbKwd36H+1a6Zy/aLtbddac6Upg6OXOJawvTK1DeALn2Si2Fc/mBnkSzfVqQJSNyrHIYVhTeIEjzLndmSbJpT8tbf0Rg205LekvfMbSVERi+ctkJ7xr54hLyT16Wxpmc+KgdwzelUXFdEfAWnW+TU1OUO65ETsKfNONZpy8zUXinyNYZXYmqh5gYwonhEv7yrLQpYYsi7dqGxPGaqVfDQx8DvqDdsXiUeDptolVkttny5vsIoy1cUfGEhVkZKzSc3S5i3+L4hjWmIslO3BlLqHJlXdhOjQoy7s05md8lX+gkKtMQOeTT4yfnSLAPQv0w2zSY5jj1gTHpJS7AFTfgZOa2RCyAuCfwHUfL5ehWgn1PcZNO0a5IziomHvnM+YrlPQ/AkMH+3d/EeTwJ9zhQMK4z6dLkATT/hSZtSz3zjnSa1UUojQwKqaNMxRIireHG+9zyRNytPMOsxxdM21w==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-creds
      namespace: monitoring
