apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Explicitly scope all resources to the production namespace
namespace: zenml-prod

resources:
  - sealed-extra-secrets.yaml
  - orchestrator-role.yaml
  - pipeline-namespace.yaml

patches:
  # Apply the same labeling structure as staging, but specifically for production
  - target:
      kind: Deployment
      name: zenml
      namespace: zenml-prod
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/project
        value: fair
      - op: add
        path: /spec/template/metadata/labels/tool
        value: fair