---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zenml-service-connector-prod
  namespace: zenml-pipelines-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zenml-pod-account-prod
  namespace: zenml-pipelines-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: zenml-pipelines-prod
  name: zenml-orchestrator-service-role-prod
rules:
  # Core API Group: 
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  
  # Batch API Group: ZenML runs steps as Jobs and scheduled pipelines as CronJobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "create", "patch"]

  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: zenml-pipelines-prod 
  name: zenml-orchestrator-pod-role-prod
rules:
  # Core API Group: Manage Pods, read step logs, and use ServiceAccounts
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  
  # Batch API Group: ZenML runs steps as Jobs and scheduled pipelines as CronJobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "patch", "delete"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zenml-service-binding-prod
  namespace: zenml-pipelines-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  # Must match the new production Role name
  name: zenml-orchestrator-service-role-prod
subjects:
  - kind: ServiceAccount
    # Must match the new production ServiceAccount name
    name: zenml-service-connector-prod
    namespace: zenml-pipelines-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zenml-pod-binding-prod
  namespace: zenml-pipelines-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  # Must match the new production Role name
  name: zenml-orchestrator-pod-role-prod
subjects:
  - kind: ServiceAccount
    # Must match the new production ServiceAccount name
    name: zenml-pod-account-prod
    namespace: zenml-pipelines-prod