---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zenml-extra-secret-env
  namespace: zenml-prod
spec:
  encryptedData:
    ZENML_SECRETS_STORE_ENCRYPTION_KEY: AgArhv43c9E9ZotF7968DAwqa+rTmX+EoRKZUFiXOUrCGCU2B+B2nn6tfvY4Wf5fdJa6OzmuhCM/x3AODRRsBsjRiiqqD1IkBbX3IIhej+lVtrNujomCRNBqA4W6UFooomIiyAi7Fr2B7kPNrNS4ynFKVRsp2GAMJjsdO66Y5V1aUmdmA5FxST94l04MejeB2ldP5JWWfODnQPlY1920qnt4y5hQKzGeS5D1ENtdFsSQS7x9tE4R+CTuf0Vy4Q079XXR4fwHU6hnnLwCWfJf0X/GDoQf09Fp/Fa2M173cZDyCA2bp6dBgptEj7cLfHn5n7zJKujz+NaG5dtYV9ta139lH/KZwn+eDw0687FTqd1bETk1YPX9Y4oix4IPcXQhrr66YFZMeyegT0iehCQNjsFrQs7hEDQjVubetnMqeCQWVGU1aywGWxMHeB/FBoiZT8UF27rG8cVw5LK2BTq+xmtVJKT4XxebFfcOchrZ2Dr45xxviprEbYAn7i7YLOpQrXAYF8XrCHpnnhW7ZrEUK0TkGJFGls8LeeoUsQTrJ+BGmGUhouaT6FWYF5JTotGCMyCCcZEVo0eI0/XcwJ6lnZiNo9zd4Fwv2nbNuZRLHs+uCbbyTRNzEASAVT7hLGUWfL7y+9PifvAo6aXK2LWKWzncdnLCk9oU9pntfMXRfEAuNyWoJgBvnOxLrt/Shlxo2cKDc6YTklpBPDf6hhfLrAX6s/IRwmneaUUBXxtws9OojKxtV6lGiDmzRKCF46gjVUF0jj/Nnq5wL4r3D3nNSh+K
    ZENML_STORE_PASSWORD: AgBMYnjk69LQ4SCDN42Vu2PMyds8S4or0U+Inm5BOX9i+elu9LLmViforQWiGuNt5scL9E3/CBAZGLbxbC7c/w6zNBZxJtcBHxTbU5+MVX58gpICJrJHKQcXUU23oHas0CfsQr6MbEL7VqtupO/FRo765V4VyE8VfEx47+0477dd2K1HV6G8uyLBEng5Idw+Xk4MhNe1wVw399LzqQ8VDtGJMeH2mYfnXy579I4+2XVCe/ieBscauu9Vax5P+DhhDYspvCy/iDFv74Qi212QyZLipTlLdtRWhl/wWomn/1DNCEyycDJOS13MPSO7JWKlUzL1dm72VKUge5cnJOU0/1NETeaFcYqo4FYyx7EryKyEdSmQvWcV6qXIk8kdlV+qdQJ0GJ2HgTG6uUx1KT3h9De+Im+KgJ1INBLa43cvuEkmXxjMgnyyxnI2gKxm5mpXhQXQroRWTWiKabYWUg6D/UktJKEJW/Q3hDtIz0g/J8oBGrEe2SXerZHDTbWINznwtvmhlDZxlHhtSvd/4S6qoX7huTg7LnnVkMQoEKiWnIua2IbVqv7eBDZ+hV42DBPzLvIKROX3upL9kYH5qByiK5xlzbXPpRU8poH7EU886v1ndXIzIry4JXgN7UmnukYvUcAvR573yX226fQhJ6f8HIoiTNJmkzo1FY3Li4r77WzDG0pEsIMeLIsOJjBiU27kGyyjD0o9uSwcLJ2XKsqcIMfZy5vD6n8vLJBo3GHDRCIuzw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      name: zenml-extra-secret-env
      namespace: zenml-prod
