---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-prod-admin-password
  namespace: mlflow-prod
spec:
  encryptedData:
    adminPassword: AgA7xBHFXaSCNQ4fJ1UekNqmZkTBiGfnqmjq41QgZKHYFDN+kGwxZ8tNHW0vuKZTcOzQAffy8zkQk0r7VRO8fVl7F/JBJNK92AVPD0tsoWL9XVPYMtYvYciCpqfVGajJ++WsYaVY2u9xfaCuBPAaP0ECpmwE1JsQCeKJLf9vtWymUUBdmayNhq3G+U/w7E3O2rttf/UWxAswr8tX43efKWFHwzrk5weS2mMaFlkDdVbPFAGDlPnDcq/hlueu94tXy/n7RqXrEM0hal0+s5SEFi9JBrj3Vkhn+QLW0/w6TxmKhKYU2SxtcaCtORaG4L0NpjHPpf1cheXOolAmd+bgzhYTYPIqXY14OB3nsUUjZgAZT7tuj4FiMBz5XEVORtSsbw5zdLL2RN6eVs+f2evFXVGhUQcS7WjjKHvIY/ZDCSTHGrYZGhjmFZi4H/XoHvwM+PZDZ9wjcH11EnucFs9+LGFg1VRydVrQYOYxJKBuTfjXmSUs+eyJHHSI+FGNZeF9I80n40+5oAaa84c913+d1IT56/IC5Ra4ccoWWTO7PaTTgWjUVwPfq1FFMIxZLhZqSLvbKf8ikXU1xWivfqMqYI8sOhpQce3qL2jZcxN79uR/sbvnwM7m3iPX1ZXTO/h3OvdHiXm5g9T0aBpTeq/VFSDPj3Y8q5QjM7r8R0ckpd28ZKa9nIGR5YqMu/wqN3e30JGReyHSJtNXNGp001F1vUBMb2n4GBxV22L5nbM3+UgENw==
    adminUsername: AgAZqFjabZelSSAUQignRRFnqeoiy/vRxPLaaSDniAZW3sYeICSQRhEFlqgFktI87rV/ewX/GVhhVboPlB0F4p9zA2m5vUP52qC2W3Ix6tP8ftbW00pnUitQ6FPZGi9z8LITkjIynffhBGo/tRM0u9b07vgBHNfPr9OMImFrZUlgMwap/4hC5W1rNrc8Hr4U1BUk62DBwn5Zbkfhy/YvFk2vmVcZY+zaPicVaA9YiZJlyVFshItlU7dM0Nyydi/qppfDDYKyzmufoXkXXneUBMcu3slA1ARpMcFr5a9xVrwsCn6MMp0JM43Mzs+5fIEvHSFPqub0Jppot2j6vLqVGJwHSJIbB47004HhvS0ZDOW2bgEwt2Eo6ATR8y/LHqlEwA7dKOuiQ4JCyVGtMj5nraWCudUSPX6VCCYNh71fOm7FHGRsjsNLFWD0OgndgQTuMaBB60fndWm4KwK2Cc1sj6M7xggeBCqQjrF87iWZAy+Qr3e7wqUwQ+cwvHoMAx23wI+Qo69z+nd96w7R2FlvMvqlfvYCSWnLc0Lf+efNWyvk/61zAzPHt7Ra3ihZVtW2fGuuB6u9WYJn5HnOH7uSDNeQc9k196MAXfTn3rkYFj+zDHiuD+ygIOxWCVTgcXp4VpCplDY/bm+CfNGJ7tcL/iooPKI8p/lAB38/6w84jCJAoBmUe7ldAuIQ0niHGvPsoeoAMgRrRE3PPcXWSt6fMPAgQAQHSd0=
  template:
    metadata:
      name: mlflow-prod-admin-password
      namespace: mlflow-prod
