# Cost tracking
podLabels:
  project: dronetm
  tool: dronetm

# For default 8GB redis volume
global:
  storageClass: "gp3"

existingSecret:
  name: "drone-tm-prod-secrets"
env:
  DOMAIN: "api.drone.hotosm.org"
  API_PREFIX: ""
  DEBUG: "False"
  LOG_LEVEL: "INFO"
  POSTGRES_HOST: "dronetm-db-prod-rw.postgres.svc.cluster.local"
  POSTGRES_DB: "drone_tm_prod"
  POSTGRES_USER: "drone_tm_prod_rw"
  S3_ENDPOINT_DOWNLOAD: "https://d2ymfcf63vwwpt.cloudfront.net"
  S3_ENDPOINT_UPLOAD: "https://s3-accelerate.amazonaws.com"
  S3_BUCKET_NAME: "dronetm-prod"
  MONITORING: "sentry"
  SMTP_HOST: "email-smtp.us-east-1.amazonaws.com"
  SMTP_PORT: "587"
  SMTP_USER: "AKIAZYDVV4ILPVD5CLBF"
  EMAILS_FROM_EMAIL: "noreply@hotosm.org"
  EMAILS_FROM_NAME: "Drone Tasking Manager"
  EXTRA_CORS_ORIGINS: '["https://drone.hotosm.org"]'

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: api.drone.hotosm.org
    external-dns.alpha.kubernetes.io/ttl: "300"
  tls:
    - hosts:
        - api.drone.hotosm.org
      secretName: drone-tm-api-tls
  hosts:
    - host: api.drone.hotosm.org
      paths:
        - path: /
          pathType: Prefix
  labels:
    project: dronetm
    tool: dronetm

# Main application services
frontend:
  mode: cloudfront
  runtimeEnv:
    VITE_API_URL: 'https://api.drone.hotosm.org'
  cloudfront:
    roleArn: "arn:aws:iam::670261699094:role/dronetm-prod-frontend-cloudfront-deploy"
    region: us-east-1
    s3Bucket: dronetm-prod-frontend
    aliases:
      - drone.hotosm.org
    acmCertificateArn: 'arn:aws:acm:us-east-1:670261699094:certificate/e6eaaa9c-0de8-4222-b8f9-0e8c3e56f813'
    priceClass: PriceClass_All

backend:
  replicaCount: 3
  resources:
    limits:
      cpu: 900m
      memory: 1.5Gi
    requests:
      cpu: 100m
      memory: 256Mi
  # FIXME enable autoscaling at some point
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

worker:
  replicaCount: 2
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
      # Ephemeral storage required for ODM assets zip extraction
      # 10GB zip + 10GB ortho pair + headroom
      # Increase if we have larger than 10GB ODM total asset zips
      ephemeral-storage: 25Gi
    requests:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 15Gi
  # FIXME enable autoscaling at some point
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

qgis:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1.5Gi

dragonfly:
  commonLabels:
    project: dronetm
    tool: dronetm
