# Keep aligned with staging except for production endpoints and infrastructure.
zenml:
  image:
    repository: ghcr.io/hotosm/fair/zenml-postgres
    pullPolicy: Always
    tag:

  pro:
    enabled: false

  serverURL: https://zenml.ai.hotosm.org
  debug: false
  analyticsOptIn: false
  deploymentType: kubernetes
  auth:
    authType: OAUTH2_PASSWORD_BEARER
    jwtSecretKey:
    jwtTokenAlgorithm: HS384
    jwtTokenExpireMinutes: 4320
    corsAllowOrigins:
      - "*"

  defaultProject: "default"

  database:
    url: "postgresql://zenml@zenml-db-production-rw.postgres.svc.cluster.local:5432/zenml"
    # Ensures the secret exists before the migration job runs.
    passwordSecretRef:
      name: zenml-extra-secret-env
      key: ZENML_STORE_PASSWORD
    ssl: false
    backupStrategy: disabled

  secretsStore:
    enabled: true
    type: sql
  backupSecretsStore:
    enabled: false

  environment: {}
  environmentSecretKeyRefs: 
    - name: ZENML_SECRETS_STORE_ENCRYPTION_KEY
      secretName: zenml-extra-secret-env
      secretKey: ZENML_SECRETS_STORE_ENCRYPTION_KEY

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      external-dns.alpha.kubernetes.io/hostname: zenml.ai.hotosm.org
      external-dns.alpha.kubernetes.io/ttl: "300"
    host: zenml.ai.hotosm.org
    path: /
    tls:
      enabled: true

  proxy:
    enabled: false

resources: {}

autoscaling:
  enabled: false

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
