---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-s3-creds
  namespace: velero
spec:
  encryptedData:
    cloud: AgAAbNZwY5wvc3NKcwM4jpbTVQ6Mfth12R+/TZcn4w3fTqJiLw3DdpzwIqjKpnlPVVW0xWr58eC5JLZya+J6TOS78TfPP8pWGploiSMe80iKxAqGxQk7XyxAXH3D6he3Bjzm0pFlC6tzLg2XEmdTLbFqNG0uO5HtI9YV7Y1xyEXhJDvfEkZuwz3rPO5MpjjC/D+e8JhI4faPvqW7l7FoWHJ+/k3UPw9VYKcom5LdYIWW+cX2xzOedE7vSdsdIDNt8RtP7PlyJ2FHnMEjFsuJgVvrr0if1+89iN6wIG/TmjidjdabeFmI0dCoF1j4d0OceXuBLfH1c0YaDfbRXMdi7++Yrprkc5KoEJOCgJwGRBlGNHDIDKPJF+7/M7IRKYb1oCb+9Q1RwvKJTvcZs2w0wkBM3B+a8b0JLwdSXKO+N+u3gDmxRXt/DAWJLpHEN93VBHFV/UfYC/IwJRsfRWr3lAX1lUIZ6DmRN+lIQu3E2UrEfVBX8hRmDCw8ey/xYxg6QK7+wP808LLqXc6Szl+i0f86ajUwYJzfDwCDfsTR+iIr17JR2byTQoMbsHSAeGahdPvMlQuo/zvYjzlZrRkHh/k48XCyQRjC4Fsck3PzdeoQbgaGbyjdVqvphwNq0BXBfazQNAkesxbXgwGkOT0MEoil8CtC25fwwtof6fMqfbNoV7cZnIqpmHW3BlkJDXuiniVcAxIKgOyhXNE2R6jVyG+V9BhbztTVMakK/nr9z3sg3ytnkIgTulHdkwrGczD6t4tOe7rLCJJHjyM/F7PZd93nfTGPaduTMFuP5trRhZLV4OuulMIyVXDuafuNHcZGQor5N37f58risXMK6x/YPmg=
  template:
    metadata:
      creationTimestamp: null
      name: velero-s3-creds
      namespace: velero
