---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oam-uploader-staging-secrets
  namespace: oam-staging
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  encryptedData:
    COOKIE_SECRET: AgBMCy5BZrsptcY01bVAO4Kqet32995Bhk9iWr8Ifezpl+uUXI4j6VZ89RsIwCsnA4Ikc3ewUJhBioqrxjrESEl7VePg/El19AdRjVipsQujSc51gwwWZuENoqP5QPAaEwVONiktuXed3LfW/4irw9djJLeHL6JulkjPguBIqbhYh4hlxIhh5CXgaLTZag8HE77f7+9JZyi75vsJqTTYug01JQLn+vIu+sGmpLxGx7zCQWP9Bc81MWZSxdfxtT0mOdAzeuGTLiQ5KhXiMcwj/XQz3hcjmMYES5uCFkP9HQeAG5sJV62nfidSoGMAouF8f21RQiPro8hjusTGU62zC9lywhImatbD6ro6GQ7r1zbfA4XrebgVjU4q5BmxJdWx1U7mCEqVv89ZliSdbYqrYYeibxcAtSdCerfC8oSB0FTSMGgF+TlQS8kOqTeuymRzg02FKu4mJfZzeLTcaXnQBULAxjWyBgXQ9KFA99mKZsABTKoj31ln1LN6mVw0SN5sBecn8KfLuqQvFJo073Imddwdw2SXPrWS+NUd0mSCfCcS/ghbwzjCxG1sSiUSuVzm4KfKtfnMMCfShF8Lq79U26solowuI49vpe7TEF8Xaof/BTTsRVJvo0DpQGNSzk7gh/ZIU+Tz/E0Se6PKuMAy+A/yHkY11x9/pqIyqvvjeF+jf8vzRXePSz3qkfwgh8/X4nTFEV9FMOYwGyJmn/yiYWFfKanL8frC6XYgwZYFVllu0X4drbdwy+pFL8HAP04zGDGrApJMQkh9DIJhTv/s9eFk
    PGSTAC_DB_PASSWORD: AgCr5aqCS0htcx3MGQVG6LM9KuPf3/NCc4xe+J2AYE3xdSJkmtWbfV+mJ4UNJkM9aLBpFhubvQztDQ9O1XcfswN0qqJpCSgOdAX0Dj6JRrpWGEsvGMET2BhMq71dJMu2CwH/xqowqKoekH5XrHCK3/QvCsTvLNcl0YYOj+J753SC8T9fVfqco4/CbZ2f8mvE/G21gfY+kUzLgdeNtGlycME8eDrGo/BJ/CgifrGaMuD16WdOWhsv2DbclWgamJX9vxexUdjd3zRgiwYaEOm0S3eKvGwDuPE2ReoCEu007XfPW3tEWGW+c2U3K2D9ZJO/4YY4/LATZvFkHHPhubVKXwWbdqn8rHQYYqeA/po+RHJC/v8sHPflzEqA+ZHx5OMg+WAmpwaVvozPCtAwKYkb7XXPwfoRc6qDqA0Z69xiKV+yxYAS3btchMKfYI3MERgRkxes8wEBNzyQE16G7M8yOh8cSkWjvKmGztW1KgSVn0I4rIA8iMXgfCyKKL86d32Ct7f/SqQGCpfzurHr8vBznIv7/hOJq3Azv0/GKHfuUtnVfMHlZhiVHwuzP9OJvKtGXVV3qQ9v5ov3GZhPxZUN0iy+EihtsJNll8COXdAEK09h7poik2zTf9OtSCHJG7vibpV47cqjh+lMEeSbqaWYPk8xRjVlEBffBJa3kaen0yWpUbfoBkM8dWgXysCeUCv6fTTAKfs/eC4Aeg==
  template:
    metadata:
      creationTimestamp: null
      name: oam-uploader-staging-secrets
      namespace: oam-staging
