# Add or remove namespaces in this file
# to grant / revoke access to contractors.
contractorNamespaces:
  - login
  - fair-prod
  - fair-staging
  - fair-knative
  - zenml-pipelines-prod
  - zenml-pipelines-stage
  - knative-serving
