# Add or remove namespaces in this file
# to grant / revoke access to contractors.
contractorNamespaces:
  - login
  - fair-prod
  - fair-staging
  - mlflow-prod
  - zenml-prod
  - zenml-pipelines-prod
  - knative
  - knative-serving
