---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: windmill-db-url
  namespace: windmill
spec:
  encryptedData:
    url: AgCfimkN8LrX0n7l7zw3+qwTi0Uk98T8150pz3oxIeJ/kLnJ1gjDmjlp459UYFASZR5QMVBrkI1t6PYMnH6qixtRdsxfO+kQNaIgGo3eZ7o/XIBVSywtpfIHAAIUFNmwTNrtap/dVmRq3g7BIE8HFadQFoeGHemzREppD5Fbda59mlE/mrjOuagiuYMCMZvLaJhjm3Z4hihGMnilQ8ngIMDn4v2lieWz6pEPMkd/X0Yq+x2kROd+gYnS7DNAyTMM7V2wYKYzWVzNvhT7r+svadnc/EPfycwvssHyx97MuaTOgmNHIwQTjP9+GlpTViZoTOpV14r5JrsuQqIIx+8IMTnxY/KSZME3h3DjODMCwoPvBxxPhtJ6g6ejkdm10C4E/kJuCMWeBQTWsDQrSpTwK/tdFtURQAIvCYeYvU0S3dtkGCHQJsBUlKm1JRc6zRTg0lp6smYMGLeP6NnpwNzWxYh3//cvReTzU/5xYlVnVcRTH4tnpQfXIo7Mv0ptQqKMP68KUfU+IuHXA5mvc7adw0lxI10x4jlb41Jhxh/5W0G7nJc8jj/2q3XDnDP9am6KjoPAvZBSeXVedhrs+ig70QYn3xKOqiDht2CgKrbbKTJ3IWW+u/YZADZkQBOxoIi2f7s1N1b6VH75OZN8jjpn3w2JvUSQU+pC/HsoFQt5xHSP3iNhjgSGZfXK3wKi3XNP3mmo4pDL+uFZuLTXrkXXXBNGvO5XqnGBEMk8DemVn62VYXtQ7gPp1SiTdWjfCgKXOgVXu5YlSj39LI/hYOkZpH39RnxxfcRTAEWHFJLQWpY9dhxsxuhqiSf4Hjr5j6jZWsbUoWcJdNhycsJFIOo+Eql6pPEKXfdpqaEQNAy4MbpoJGtUuujAwV6F933kr7rLGSSi9vM1
  template:
    metadata:
      creationTimestamp: null
      name: windmill-db-url
      namespace: windmill
