---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: windmill-db-url
  namespace: windmill
spec:
  encryptedData:
    url: AgB/YnxJieBDUbFNemGBWaKKAUJ5J079V1D7QatPQ+VALAEkkDvaMXBrLiJtW7p25K4lCdXiqR4cuLDiOYGMbETqqkJPjIiT6uWbvrPaKa3WQe5jAtGV3lBnmnxVJUqRqiaOwEMfmejKzoW4quB0bjsExnfVrRv3gjVi1hnSQMDBWMFB9V5McZ9hsVCyVDPRm/+MRJR21IuSeldA6Rg1iJain0706ip9Y9DQ4ir6HhPI9F+ZFCZ+NR4yGWP311pAT0peBLgOky3uZB/U/P+elzpx0OhgUUP2KVBrwM3m5m7AjU/ANzBPtdFTwzWgott3cTNGr6kZqTvdtlHW0yT4MisYj6VDZq/QmD1Rad3K6+6MWvwhhttQJdb+SKlHDAX4fTQZ4ta/uMk1MfVv1eYFXM6d0+lUP7KGemxHiTHgGGUu0m5/qTYVPWTXLNICP1tQ3Uoe4Sj5pGBX7QOSz1wnrjcxy5dewAkozHeyCPVoUdhB81I2rQVvhCwJ8Dqna3ZcRrICYguTH93qLtZxCEOUZPR2RZh0aqg4IcxO4UNcMBcUk8CRxHHMrmxmAewk1k+Hs5MJyFlGizh/eZ+sHEejriSuQAmI/fmK4LU5dMjYUCoqp4R5wM6yP2wHBaRPDeRKZ9f5BOu3KE2YUYNYSUY+kc3MlfOfpO6B7RR0WGb+vxx5XZEiAfCLx76Uc7+IS0XpMvERX04XNklsEF8DzCD+e31zqHK5CqIYmGjKW2sWwpUXB3W0197KvF6s++sLPlUH57rY9YdT3xfbn5YjBdGL/o5Nf20VuGc52wQWuRRiL2rvWTWeL5bWeT2WH31Y1IQaccf2HfNcQZZ+lpc5Q8wEdV+OM07bPVrgtJDNw0JyvFxweMKow8VhcnjaaSNEO5M6Z7I2VPXe
  template:
    metadata:
      creationTimestamp: null
      name: windmill-db-url
      namespace: windmill
