---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: central-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgCimzUrksJY2O2tkG5rYvSF8dajfAVnmWKToDbPAcZajs9yO+72lm/m6O0q78bwBA1YJbXC0VKQ6GVWERiOM8qA6hLCJe70zuMdhimxigtbUx/893ZnuK8lj/58gC6QBvx9+vS3O9YXeeJvKRpXtPjmQ5BJa8kjGP2Bv90Kn2TFFXi9BYOlzJvlkTqYpFZrCkdXvPuTp0YDtIta4ntZq17zXJd/lwp7vVvf51r2TTm3wKGu5klAHUa3au88Y/+rSBqCac5dyxr3C23cQmCNKBryxx0fhLBh55hRbWCLtXkTA2vKeE4tIB2DE2W3gg980xZY0ipRVfZWbIKl0tUZsI7ROhQV6sM5xBfk9ydd1Y8+QgDtcXcOCrHmB0tyhGThkO4eo8/52PRrasqoMJGh8D7kbaDbAvtk9SFQmtM4cVcvQgkFrB4h1R4dsYzIYxwMsqyKJPQ5xmA5iJuD1jjsbX1VIgOKuHT/1qFuXzdaza2Jvzum4hXBsnULsS28GMwwU9es7m3urrF8dB2LRoAfpz38jXEglbyIbixF+UYEAGW36Fk2GbAhtWHsWZo0EodAEy6//TC6mlU+O458CdC72Uu56l8c+FrJk6s2kTfPzFfulqWkq/wvIvBP2QuHfdiZfNhl6fIu2QR4KN4eNL9ySCg1sWBKFVjrgnsqHYPdasTEnFjJd+i9zpxKETtgECK+9A7QvevlOoGRLR8kNdXkbJoSFIv7dFwSN2Qra837ztA9qJLjIZL0B3WVu5zh62l8ntUevG1bL9hXusCSJz+7JtPMOx+zg0KF
    username: AgAHAUAVfRNW9ET2+8RBOhyC2B+UQd6qp+/Vpc6JnXq84AQZR+ag5noBTf2hiqBxK6qQg5Vcc1QlC//h5mmEmJYYGgmZyJC+1qS/fn9a27Bv5CeNnHwcPTBGUEF7sJQ6AM+Jk5CLIpeAHrGZbOrQJ+1+KUpFDXiGFmq0dYwpogDrp5/0n1VIU/tJcJak0+MLBTB18BuAn2iJlntyZAqbZEisdChe+WwvSvPVMvtwIXHEkK0jn173OgK5lZNb4hXkSxK7Bd0Zk66z9kplhqk6/MJmnp6IS16/bCygtpG2qk4BPqyiDe3IusRL5s33dQlYX9bPcoKAvELL8izFWcA39+PeVeqxORk1fkajp12Klo2/0yqSw7eNK4L1/eztUsYhRjJEm5DCBQLokPSv8zDNzlsOxcc7Td7wl7+gDhnIofbU4l97hgu5ZTtP6L2xfvLbkZzh21zvTz7z6k2QPQadk4qfiuG2llT9ryiJaHbBjrwAQtYB026nQPjKQPka+ppbJbeI8F2naxzFaQ16qHDe3qRJyDP87iRBDXC85P5CYZckHE0sIoqJrN229oPiOBUUNmw+s95FGRcZXJxZBBJqXebtycbMu8CcvQ7oRtoXiLTx0xnZzv+j1JrVtwDOL6CcFRhto3604wRvecAJor6gAtW0Ef6lh+mKQuiHNnLZsnMf5FKSUZ8Vm0kC4OPKRgJj+tRyNHRn6D4D
  template:
    metadata:
      creationTimestamp: null
      name: central-db-creds
      namespace: postgres
