---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: central-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgCM+b+/OKom/evEGhY3z4F0ofJ3DH9IGRkNMguM5on46TN1jWfI8nPda4XctbeE8V0b0DqRTFEc01HXg1EtUHwtEacyb/Ziwnfg/ENCaO71gd/lWIke58fCxVmNsaMV4KcQSu4CCnBmSaoALi90rUkuVONf6tYyOTQxDnbO8gX3RNIAUY8+B8opBT8/YyAtGxxwo+UwUlNgKiFwsYz0QT/Q0wHuFSsjaLRiF8YG3nT5u6BLuYEQqHKsNdFzc33EKFFP4ftnQtokIj/X023Kd6gHz03bIXyltfuZQXazNZ698sU2M94DM2R8OgWjEYXHmHctpyVjK7PhrbViMTjCGIp/Jzl4BKza4zrG3i44ezYBVPvowAUE3BA7938udarqkmfIwX1KoQpPTo1TMAS5Dm8Js9Y7jFio2GVt61Qx08Vem6aZjPDO7vKcZ7/bE49ts4jjlw53IcpCkDPC2pjgB+qyS3PwaAuI8wqo8Q8Fzbw8zS4hEFuDMvm42vf3xmB56rK5hweR8evY9oMvulxEEEbz6AypwendaWU6/yAm6/6gTeVNvfxi44CLYMrAx//T7r2hKtFVRvqWSBVeUiaYlpBcVJw4okjSv98haiAEEd753EabYm+mHFWAT56u/HqyZ59UCzVuYvez/m/RGhxkPQFTlyvFrtLNjK9XEzd+x5RzaR6KdaracUa4gFUDOJjbN+wLA8Wfd5EJw68Ryss17TxlvhRtogFypYZjJ+BPhcUqKDO2TLYqmsuFNwf0LRdiradGHPg0X/AsNTfjc53q06rKbsj3B0IU
    username: AgB+0JaWr216OvzpW89pZQB0hZZFkDeERe++7t5n343ZsydCmNv8ZA9dr66GMWCtrFvradBPL51j/xMZbqMAzg17nwJvk2tjLfTyz0KGRnnuEXzds7Uh2nipxDQIM25iN4FWXzckobH7kvwzZ+DkawlXJrYiz+wazQ4i4JJQNXiLJ0wZ+ppwIoQHRuEptPnha5AmhF0Xl9FbZuDT8OFxeaM8XwxPJmxIj3ubtHj5BaJ8P2pxjO5UhRPJf8KfFUWSSkdk+ih/4AywmPgGQrYsX4qB2pHbFZT5ITrFPciIkQXH7zlLVy5NDqQ/6wekZmsvvpBGl2MVRbvk5YbXfkBNS4C6fiBTrIt8liL/hEa+MEDqaDAIKxXthvfsX6tNVo6X4TLaqD8RtmRcXsQQvoY9zXuTwiTFh6MxH69j/btOXse72xJ7uK9SRa8bzaVebBsiI6pYPntLBVA6vZ3lq2zeYesI6rt78CnGj+q6eCxITLq/hr6uQsRx6gOR0rWT6t+5GQnrz8VtoUDRnKGflBW51BWyIouCuUyEzAA8zmy3sruCJnIHIW7eYV1i02vnaR//CdYdT4Gbdy+0/d4T8IsCc3RfQ6mEmEdAVqxjN/BhWpP+EgK2BXbv+60mr8eZtsGLD6Huaz+LJDbIEA7UZ6IDxI6CW1OjFO/UOGI7YWSptUCYjTfen2r4Xtr9S2VuxWKORza4cjR/mBim
  template:
    metadata:
      creationTimestamp: null
      name: central-db-creds
      namespace: postgres
