---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dronetm-db-prod-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAfGwEMrxzBVOjellfG9gT5MtKafKKJXx6ciXGAImvQhItdlavIzu5r72FdTm+qV6fE81vInEfQ0AXWJ2mFpFlrlrUnP63yTQzBIw7CllgGtLb8+Y3gXym/JD8th3am6RN8c259yovt7mbOjAbngA29YsErFPjnjUa2D/N1z5wpFtH0zbKATt2hyXQtMi2Ng5QorIVhsON780e4PibA3yLjKM2zUyDGdPVuY85pQ7Aj2zeyFDr1cMxqQxkP8IWGCR+Mln1/a7sV6vBQqUByJ8lYwhA1BOEAa12pdu+G+r7GfGptqx58VF5Xgjc66Nm3mMGg/w64xZINmH4M5o4cJPuy20lP74TQTU5JBF/AHWCl7B/D4tkGFcjOEEyQsmMLwrO/bs0Wbm43ypI8ZzfW1rjXc4qDd+53rtjULqjM+cBVSjjdyhMb53agzHhYGL3HzHejK7aRa0T3ckPi22p8U4zDE6XM/JJ2XqbZKITl87zqdLLby1E64Y5UPz7Jstr82VgAp+MlJDxBFX6qPhhcn61IYkcQj9wyoawyIJLIfGYFjaytE0i2oX3j/FTWohhNVqIt62CibSfY4oebuHhfPSCYs93KQoZbFaLMrcsopdIGzZor6tP9x8+a/ZXm4lXOxPmfSo7qTX9jaN72Xya7xfpc2nCF4yuaDK6UA1+TBMVcUBgw1WyFkjq7HdC55K6wHxosv+4bU8+W2JtmXx+olb5fSap3RgY6EMG7f/C5rbIFekxSGFERUGfksT6cHhSy8ArFT1ZMQ6xVt8FNbfKLRYFCQerFpRhR
    username: AgCh8R/4Q74eiTT3PQ5po/XBv1k0SCnDdZlmxHyjTF6KN/zmbNf0DTDFbtu++UCeeUi95FWz2gCyN30Jz+YL5atVJUjPqQ0On4BJgMYBpocg5uG6BzxYEfol8rrvXcaF7w079DiL5vJdDDDRcTyKFIRSp+g7sAweq4TuoiLn9z7COxXNZdCgADfpdezy38pdFPcDNGsmPoziWkkVsMRw35WnfmdKVKM2zWBvG05EmGJp5fvuiomgXhe8Driw8rfae7uD9HCnYhnM0wCi/KMe2KTRChpwH4h1IW7qTtMd/oMN8rcjYm248oACG/KDX+e0fj0C2pmhpiX1lna28mJe9FUiVyDbTf3DJb0YKxcnwiAu/j68n/tONJAb/bZYne9KJ+yFyeOwDWv82j/3yk5wup+EdzTivwYkFzVgmOCGuZvbycRn+U2AkY5a7aV1pHRdnWltD6fIk8W4sHAvPxOAvcT0s08Hd9xST8JXzXQgoQ09hYmQwmlg6sVI2yMXpV1OCiTuuCKq5NgG1N1cx+UqNAuWgaMccaKb3JmhKD7a4P51vf+ndU0YyViiY4Fw2dxMCsQf30B4oWX3NoGqcWBvuYzKPlbKITD7PrDbT8/8YBy9t2+Az5LbA1SRAOxbAroAigkQBcNah55oggvjGqkJAo2CP7eCX+4gpC6dnq8pcNitEazBKiG6VvPNnx9srUP3b4OykxnUPNohHU8awuivRloV
  template:
    metadata:
      creationTimestamp: null
      name: dronetm-db-prod-creds
      namespace: postgres
