apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: dronetm-db-prod-backup
  namespace: postgres
spec:
  schedule: "0 0 1 * * *"  # At 01:00 UTC every day
  backupOwnerReference: self
  cluster:
    name: dronetm-db-prod
