apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dronetm-db-prod
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 16-3-system-trixie

spec:
  instances: 1
  description: "DroneTM Database"
  imageName: "ghcr.io/cloudnative-pg/postgis:16-3-system-trixie"

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: drone_tm_prod
      owner: drone_tm_prod_rw
      secret:
        # Kubernetes basic-auth convention has keys:
        # - username
        # - password
        name: dronetm-db-prod-creds
      # Required to enable PostGIS
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder CASCADE;
        - CREATE EXTENSION IF NOT EXISTS postgis_topology CASCADE;
        - CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;

  storage:
    storageClass: gp3
    size: 20Gi
  walStorage:
    storageClass: gp3
    size: 10Gi

  # prometheus
  monitoring:
    enablePodMonitor: false

  # see https://cloudnative-pg.io/documentation/1.22/kubernetes_upgrade/
  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead

  backup:
    retentionPolicy: "60d"
    barmanObjectStore:
      destinationPath: s3://hotosm-k8s-db-backup/dronetm-prod
      endpointURL: https://s3.amazonaws.com
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: access-key-id
        secretAccessKey:
          name: s3-creds
          key: secret-access-key
      wal:
        compression: gzip # this saves a lot of storage
      data:
        compression: gzip
        jobs: 2

# ---
# 
# This is another approach, but we stick to the simpler
# postInitSQL script above
# apiVersion: postgresql.cnpg.io/v1
# kind: Database
# metadata:
#   name: dronetm-db-prod
# spec:
#   name: dronetm
#   owner: drone_tm_prod_rw
#   cluster:
#     name: dronetm-db-prod
#   extensions:
#   - name: postgis
#   - name: postgis_topology
#   - name: fuzzystrmatch
#   - name: postgis_tiger_geocoder
