apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: fair-stac-db-prod-store
  namespace: postgres
spec:
  retentionPolicy: "60d"
  configuration:
    destinationPath: s3://hotosm-k8s-db-backup/fair-stac-prod
    endpointURL: https://s3.amazonaws.com
    s3Credentials:
      accessKeyId:
        name: s3-creds
        key: access-key-id
      secretAccessKey:
        name: s3-creds
        key: secret-access-key
    wal:
      compression: gzip
      encryption: AES256
    data:
      compression: gzip
      encryption: AES256
      jobs: 2
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fair-stac-db-prod
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 18-3-system-trixie
spec:
  instances: 2
  description: "Production fAIr eoAPI pgSTAC"
  imageName: "ghcr.io/cloudnative-pg/postgis:18-3-system-trixie"
  primaryUpdateStrategy: unsupervised
  enablePDB: true
  postgresql:
    parameters:
      idle_in_transaction_session_timeout: "60s"
  bootstrap:
    initdb:
      database: fair-stac-prod
      owner: fair_stac_prod
      secret:
        name: fair-stac-prod-db-creds
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder CASCADE;
        - CREATE EXTENSION IF NOT EXISTS postgis_topology CASCADE;
        - CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
        - CREATE EXTENSION IF NOT EXISTS btree_gist;
        - CREATE EXTENSION IF NOT EXISTS unaccent;
        - CREATE ROLE pgstac_admin;
        - CREATE ROLE pgstac_read;
        - CREATE ROLE pgstac_ingest;
        - ALTER ROLE "fair_stac_prod" WITH CREATEROLE;
        - ALTER ROLE "fair_stac_prod" SET search_path TO pgstac, public;
        - GRANT pgstac_read TO "fair_stac_prod" WITH ADMIN OPTION;
        - GRANT pgstac_ingest TO "fair_stac_prod" WITH ADMIN OPTION;
        - GRANT pgstac_admin TO "fair_stac_prod" WITH ADMIN OPTION;
  storage:
    storageClass: gp3
    size: 50Gi
  walStorage:
    storageClass: gp3
    size: 20Gi
  monitoring:
    enablePodMonitor: false
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: fair-stac-db-prod-store
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: fair-stac-db-prod-backup
  namespace: postgres
spec:
  schedule: "0 0 4 * * *"
  backupOwnerReference: self
  cluster:
    name: fair-stac-db-prod
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io