---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fair-stac-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAlYuSHp7BQkRZifDbL273mlLIXk7+aMI9A0mk51dFOdKZg9nmgk9qyidDI5IvaWxBqftEwf2Y+Mw4nFsoX3GABXI3VGI3dA4QOkfIF8wNhbDLoCeSSOtCEXldEth+J4AP1jigIg51r8eChAl9G4ihkrptnsdSsbcKHp94CrdWiQ4cis7ErsbxKkZ17IU6rGUUWoIj4CWMPgYW40vqiIHU1tsK0wQKGdKVI3USj77xQkHK0etLpN10pT0R+WoH8WijN1bo7+rq9AL5+jUusmgQMhqzwYp77rU9R07N9KjzmFF9WLv1vmFjJJg/9uFG4m/U3zHOETK3nCEcZEfkFgrQmJcolSHUy621SDUKHgBtr6lQp/fqQnngsQD/GcRiN8G1RiBZgmUIWOfndCkJGae/Inn8IyUEMAqHkTglh6iakBbEATgQ+3sB/UCpL5ZTiW+qqQ/UrBuGvZCypBejkyca5TKS6icmy3rF5PJizlndXGqaz8XnWttCNWLLitQ9QSXnkAB7cLdfhAmfm3PUsKQzRPVK2DVQQGBZgod5Oy66bRQ/SC9s2G1R2QzlyIti/UwEMhbLoeEa/9Al1bCrvoTrxdf0NNZfisp6+i1JLCl6aPRKCX8ngUVmA96ERPwLrtx5e7htyzey4kMXCV3BxjFMxcaiK0Due7HZdkx0VsKA5nldZ6aobduv1e6mjEvFNNSYuSMFZHteNjxqsdkTYEN5McHB1t2RDD/sMCbnx+7sOZ8bA4or8EknEbmqA1fKf6PnfftMnvVNO7f8eR6M96B18vaONjlJP
    username: AgBr71biGj6cg4JNxuL8woNOLHTF+/YzjZloIDPGzvMoAqmfgx+9LNGKfTPd8H9vtOJE7+dh5Jxe+H0+4A1iyGMilO1Xaq/M3hl8H/A7UGxCnSGX6RQCVI4+iEO3l0N17azV2M2tkO80ynVqSZWaxoC6+oRRPTnPJfZR8EtbIvn3CmOW0Q3FnTtj9cYcAbPfMTnMiPetgMS5QOiU6GodRr5YgnhwOyzkWRbGqTkkAkeSOtS/NaUzo6J1COuIjtnIIWgecUR6G2NQGa/bH3vK+3mVyD9Iit4F8YcKolGu+3ywgulPPJPz3Ue2NGtAeubLWks6lyAqNRJ6iqcsh1kRvawM58Zv+v4+6fBKSVlJxlfKvN9YJPBOMF5J9SfLYBJ1ZcRhluykPc01G0jnKDJkJWu/qF+AshubkkSugxDrfKiDXtcjalxPzaKVXRCNBKZoh2UUHUVccIJSHZKcCJ/POU1m58k0s6rI8a0RwNpwvuzcWxeJqEv4HNs5GI5+96PhvwK6BfcxvTKeEqrONwYzLne0PCdD4Vr5GUn3nmWtMp5WRMaL0IBWcy1iZR8kgpw7ULVI1k2aVL0Ain+vmzFGWZmSFHxG0yVUrj3oz6mxCQmtzuUPchHxsqsbK9ESJJo5/NNo0tRKXR0yqPCXCVhlR7GbnA6A1QcWdvMvYXKo4ZasC1L87LVKZ2V9PXNitYrBPkqtOoHv/AS+yVc=
  template:
    metadata:
      creationTimestamp: null
      name: fair-stac-db-creds
      namespace: postgres
