apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fair-stac-db
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 18-3-system-trixie

spec:
  instances: 1
  description: "fAIr eoAPI pgSTAC"
  imageName: "ghcr.io/cloudnative-pg/postgis:18-3-system-trixie"

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: fair-stac
      owner: fair-stac
      secret:
        # Kubernetes basic-auth convention has keys:
        # - username
        # - password
        name: fair-stac-db-creds
      # Enable PostGIS and pgSTAC prerequisites
      # https://github.com/stac-utils/pgstac/blob/main/docs/src/pypgstac.md
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder CASCADE;
        - CREATE EXTENSION IF NOT EXISTS postgis_topology CASCADE;
        - CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
        - CREATE EXTENSION IF NOT EXISTS btree_gist;
        - CREATE EXTENSION IF NOT EXISTS unaccent;
        - CREATE ROLE pgstac_admin;
        - CREATE ROLE pgstac_read;
        - CREATE ROLE pgstac_ingest;
        - ALTER ROLE "fair-stac" WITH CREATEROLE;
        - ALTER ROLE "fair-stac" SET search_path TO pgstac, public;
        - GRANT pgstac_read TO "fair-stac" WITH ADMIN OPTION;
        - GRANT pgstac_ingest TO "fair-stac" WITH ADMIN OPTION;
        - GRANT pgstac_admin TO "fair-stac" WITH ADMIN OPTION;

  storage:
    storageClass: gp3
    size: 20Gi
  walStorage:
    storageClass: gp3
    size: 10Gi

  # prometheus
  monitoring:
    enablePodMonitor: false

  # see https://cloudnative-pg.io/documentation/1.22/kubernetes_upgrade/
  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead

  backup:
    retentionPolicy: "60d"
    barmanObjectStore:
      destinationPath: s3://hotosm-k8s-db-backup/fair-stac
      endpointURL: https://s3.amazonaws.com
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: access-key-id
        secretAccessKey:
          name: s3-creds
          key: secret-access-key
      wal:
        compression: gzip # this saves a lot of storage
      data:
        compression: gzip
        jobs: 2
