---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fair-stac-prod-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgBxY0ZdSP8GozQQjwlmdUj6BGdnuMiwVu6aord7Yy1TH0/YxvLjfOMDXgLkCkxMNySlBtO/MXz66N7g8OXyCM/NLdzMDlvCFv+n2Cv7Rsd5+I/EzG4bGuZRSN3yp7dxRMuf/7qwfMA4sTCvrIzGgkgc2nIUAYvYI1qBSej/haGAZYcWJ2C4UzBKtV9ncTRrQus35jeR4XOsRfNmHEkAJSnSYZsIW0XKIkR3LvJb+h0mz1pU7XyI0dOnJSEyIoGUZZQ/uViC7xTFrUQ8fkwtJREZmvRjRpEO9fQNms5D0MEwuzLGvt5FDjmJ4lr+hjmh2XxOCAxFA7YfKkKKJQe5GrK7gQCinbZXVEWKZJfaUZ+2Bp+CD0t83gyeKK0cFzN+1QdgKi451YMpJ0702+g/KW5eXpr3saOefILORzEyfgfW18DhtsWjipEdIBwLiwVwCLtd+uIKUDfwI/KP+KZddr0Jlry9eeaPzPGnkaGhE61OFAmKmr1nELweLoS9CgQjx5zcVhpNOlL+k2GafAeIxZdtQ7WUwVTI9PWn6tLLxT7TY5p1sUUV1R7SDXo/UtAjBMyS8/0lqOIjaftwGstaupjb4nFZaQy4hPKUpaqBRkBUpH7QAoZHX5inIsnDE7s+3faFR5D6vZU1Wb20aHoQw47RJjylr2Ldq8NFM3j7YljiprYK7Q6FfCIlq6m0/ZED9SH273rHepiOjOfPvsVT/pjQLpXP/pCoZg2+33itJOzEBg==
    username: AgBvpWTeFEXIKr52vVoSvoh8T8l0nQn74IiB3QZIB5+VgQJx2epx7dpQ2sxY1pjl/z7dROW6qCQjBa0KFYA/c+rLLav0mZ3BlbTJgNbwBcdA8fRGC78t4A/b/o4o22zKkUdj9l6YK7Bqc24ZWEDm6g4CRZqFC1HWyMBH9a1AyCyAlpFJpeq+ulAMxwA0q78yiRhm8MU27bYZKj5OqdHbhy6vpgDgBJNaXFplKDbm7VMnvwpEYf/9hzT7GuVxVk3OyoGelYiGsn+UYi63OyWpih2V/MIbAbteC2M7VMiWtfB3K4eC+PEqViv6r6vK6j1Fat/NV3PR1cKsy+9U2HlaSqCWoMHrBaY+KfT0uXWePiyLlzLF0x4tLN0Y+XBimokBvmZEg4Eq2OqRAjMCoDfPDwri4sYz12toI8iQrmkcJy8hiSFmjBxMpSBpQbSyHC84Gpt6rV9+yXfThD6IN0hwKIAqd2EPDvr6IzjNG6MWgHc79IWqXbcIb3r2TPTfVlbOo8FtE50c3GUl2xvo0zTd6u4hfbJazN3ujE97vLqGLS8hFWKx9TxkV/hsFUj92TosI5GHLGWGtoj/d+qx792Ozwh1BtSW9PX2ERkdigJdRoTHy7uUQA5WmP+KAzZaPaH/RaldJxyZTKqQb/Ge2I10ml6gAKoCXD8HIF4BZBqtw591GIIB8hN6DsMThTcsnYWXinLvLfef3VOFQh3AyB/vcQ==
  template:
    metadata:
      name: fair-stac-prod-db-creds
      namespace: postgres
