---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fair-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgC3zP9QY8CqCPiKE+BuCruRRcbJ1hb34BAIhWV3lG88CQ1Dwq3npFFtKL3xnthIJNK4H6ZaQlLHZMpXwdYG4RZPB5Y3B0dIjcJjdKaF2lRwRmS2pw1lDS1lQY32jT8u5a68JmX8qJMwEEC3SulL6nClzRkJpwlfDSrnzTFzNEK0twZ69fJoBt6gPH61a1Tb2tN7v7ZNAUYcGbFA4PfkU77r+YV43CEaEFrypjPSuRJu6Z4KObg+NaG+pbUHo9BFJGDiA/RzF3/RMCibveQoIJX8dh1uKROEjWhShi+vFJNHDbo33YyvmLCvWTwibnZcYptiy1wM1GQDfkBjTiuubx575ceUHJbDxyc2Lz0sVM+U/OuAQg+UVbwvGP/H5EWHKnnehXQLZQuBIgIuDjpZc6lN/tqelx/7gsX79GlJeEII5jLkXK/DXYNr7g1V8aHBCw22LGbFuri6UHLQAbhBZvZd89HOtUO8D17g76WwKzUWcKTXaPn1SfnqhQmXhz3VMMoJCgtat1z8ubsZAIZfwaqXkem3HHA0pXjEnD/EY4RD1ZMdGv6DSblPdin9mw7hZttt+HM7DOpjPmlrsNivM+o7Hz73lE1dhVkA4BOjQlHZmhvq3WSpIqQrj1KK+WzRZB/VHWBTWq4zhd681wZGvw2cTUecGNC9xnUlAs9nOwnfp5KbC//gTlTx1JNi6IBPFblmz058ZN7ROUoNfwFQb1IEGTdDVjT6M2Do8Dmfh0YBZ630B4R/295I39OUjw==
    username: AgCly3nZdbWzIkYJd99xNVbOGMPU5OzBlfC11emKYHPUuBL7btt8Q8a6fC/Nwa3BWjRp65sXppnNL4mq3bcwBuJqDyqtFU87UWrtjp3krYDKX4YzJ+nILUAS41H9UPGbeqFGRBr/VuFDu1IsuwAvw5ckEKBI0F3/UGUAmy/EzMe+gDaEeIT8FQ9pTxixxRaX/2dJYBpZzQ2dnZOh2PeB5W8a0CWjUaJkwKF8T6gM5Sek2t2YiwM200LsXoa1t5a3KxGLcw1HQInrfK2dx4XfUe4/9q2QZKrfTSXJXDIA+e7p/aFuyeWDE9yy23EaVeJ6tm/TvZhcwGRUjkx+Kgp+oIDkINwnvuE5c9YY0rsnBrxaV/QmCermO+eveGHeQPkBSQCWAwMYwpkW2R/qOSNZ0rPZCpQit8gBl6OLKeTJkufw5mHqSTXcsK25vmgjqcGt2exMPajZ3jho+JmVtjfDdedosR2BQVVRKgBZOpbUayjOm9tkQ0Zv265+AS+MRfIPDdMuriTRhcxAf+H7UtbFXV3xGl0lwXApzrlpgIqiSGoZvilfMhjGbBAIDHg1NhNAejjgrssg1CUQdKJr6amxhsfKVw8ifvQyMj7nDZcIS9dIjP83O0rxevLU8Q/SavocJfK85yaG27RDS/zgZLAKni6J2V0OCpeLZsFF1ibXfmerb/gddzsQj7oBnICe0VbP6XqgOPfB
  template:
    metadata:
      name: fair-db-creds
      namespace: postgres
