---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fair-stac-prod-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAv96tIH7NyBUVuIsctqB4xXZPZqnvUS3e0dsxFWxjVK+eZlg1p+lzxozZ5+6i2l3hD0VxXnZJ8mkG4amy0pjW4436qqfsB8AhmgszPI3RvvLT0yUAJi8Igs6LAJo1rOEgFWNCvz0QU4RuaULmX6MvMFgV8h83j+TY62SGiIIQQ2EMZv7XYgnEBSbtlYJR73MQ+ZfL28n5gxKCfNDQlD6yaWcBSO7IJ3qk+rMlUKtSxdf4ELtTezOqh+3odvefOx7oId+I9xtY0D0maUjPU6B/JIPmJ9d9vjgq1BaaMLI38MjjJ4tRluPy9UgHoLb+KHpySqO3mOdr1h3ax687llWJBxj8K7Q9qIzsiGodAi8yuqhzpHuKjl+3L9J1fegtchi4F/J5L4yiuATfHQef0EFTvLXPWocW9AsroaOkAcl2E91XCH9jMbnscJ92JccwGkdQqGdvbV2fF3xS+u3dHG4wbtDii/YGlw3NYF5CTMuLysaZAX9gm+5Y0iormlIVd5LXXnIf63QUYLSdADAwFq+UUG/IGknfdjGTKlfOI7bEMapH33oXTAWeqM9DeJ119FVLKT4FKWJZkM1APAawQ7lTYAyMMsKaUEiMR4APRox3iTFM67OimuicY0FH2100C6ua9dL0TBfv28Mcj2eFgLdDnX7Nii/L207UMAgFojRdx8U6Y47XQzhkd3Uq8DKypYK4DJ7MZJnAsclVM1QrglrStABibMYQjP32jz37NbxYO4Q==
    username: AgDCnE6yLJCbav/d6zJxat9U8rLUZUK9CmCqSLbTnu7jnCfweAe/20I0XgQ+OtXiEoJLeywojnI/ihMIcOwWoB+6TZdOow2d4VdjBZuolmglNM6CzQBSLNCuNa95BPXlgVRi8vV+wV2xkjos73TUwmYjcVYfqD5EMKxezjfqE3gq8H+8+TbePu+pWb2w3hRbVNxMTdrti1Z3FRJ6908D+wLGE/RezYoeuqdgKEleftiJjfFCkYCc97LpIBoPjZh/twH8YCVXbrvgh7kYkZv90FpkS8VRWSmfHNNK70LYUBuMrCGek5wmAJqKHstUp7KalQybNv+3EpODlon7Wjo2FsyMbT3uOTGU4X0fTmnxfFhNsm/nhzyllPZRhJiqHB66YAm5qX0buu/4QmvEfaqY3QrKqjzQCF0UaDq/CHsUCR6jOSc6smrGVMKuz2TmgkNg5PciYBQbvoLbr4lzf0BvR0lw/DgeADgJ+YxPIBg3JwLRzgV+K/tQFnaIGqoAfpMGW8m85b0vYJMNgspsSZ23qa+YOwuqIaQ1QnQ7g4+DVp1KdGATE1Cp33zIxKWXZXF7mCi1rqNm/lv1kbkGRacV6XBnNJlGCn2q9d61pIeMYz1XDYam58Ietj9b+Iiqcvc2FU2ifFEV+LwW1dkbob5cbd18w26SpjaKQD7WZbD+oOL7VF0Kz5R4+vI66qauZeGnTB1qGCDgcLeb+GrlDTioaQ==
  template:
    metadata:
      name: fair-stac-prod-db-creds
      namespace: postgres
