apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: fair-stac-db-backup
  namespace: postgres
spec:
  schedule: "0 0 3 * * 1"  # At 03:00 UTC every Monday
  backupOwnerReference: self
  cluster:
    name: fair-stac-db
