---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fair-stac-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgCud/id4aB5uLFiaTPJlxRhkIikY4l/hiqUgOl2SbLbsj1jiWl5/syI9oKYD+hVhYzKH5xUsbGyT3ZQCqWF+KbGtH+sgbOHCRN47jn3FSgUfH7JcJHlQ9P2c1UoQkXCFAAgv9VwAc3SVXqd/hvzbeW1X46N7kTSUBgUClSDNVjzT3pOwxHX3IZ/TgAEjkuRLXB+WMKhwA6c6dHRTe8w9dp5C2mDNT6LFcVLDTR0CBzKGZuNrUZp7aIOt6Avb5J4QKXR/3ulT8HSROqTMDTRLj7kf66KZr5jOzy03O4MS1q+4B9ZI/jNZTRxiFiHmmwnE24bM2dKj7HsONxlP6RKlooCGrWMwXb4pqSkqcs9h0hf/Qgblv+lHY8T25ktMZwY0gVJrN1JJSCl5/swQBgCTg0ISz80bdpBxyMx+RUbBNmTSl7MgqnSl1KOU891+kLOd/Ue/vg7lHkEZ2NpoSSzHaAXahzu6xm+YCW1T4ZH/zmnwag6b58V65V1AyrrpaxvzP0d03ztxMowR02RgGl/6vOjOb+18tUG0npH44zeeiuYoFpNmxAComDlo05ZNExY5KBAGk0XH0MTvcYZuKm22f+6yL0C9XPeXoca4RSILWlGJse2mHWfC3AuuxoYqalUFElqSE0QRh7TiFzep/G/qMSSw+Y34P5mPP+g3YS+IRdOCyt6uV9qR4Ok9JkjoG0VJuo70CqgmXPYnSHINSFx1JAXSwRef1M1mu6mg0S5ilIE9tJ42960fUkVUXTCTkDMuTTOroQLgNlFVnfNVYIWJet/hDV/gryT
    username: AgCaHf93HKpzkNwosouWop9pok3V2AuAQ+tyMNr0uv+1b0V8CWhBKJo0fivZpW4XX63SAlESu53jUILh4K7Fuey4S94Fi+2uA+qEwjmGLAFdOk74bWGGMsUU9iWAV9DovQsUxgSSOIHa0XVQ3o32h08ivfpb9R+U4rwVU/rCD61/Uou9nIHMSaAYhDbYoTb5Ah8slPNBVtsQkS5tODVU/Bnd7HssMrhtIabuSiwbv5K8zmsdqVlX+a8iM4rYtFmYNYPJFd7/zdPIEaWxVVRG12tnwyzxXShgEc8FRpEOVNc5n/Q+0Nwtfj5BBwA7pVnyZkSM/RHDW6vWU7zsI0DDMhSzxS2jrmXieU3PGC3iyk44WuRsxSEYnIWTy0cOnv/PL19qycKaPauQgWOXjCeF8gLh12dnmlIGPX+iI3kFgfOecjoJoPSyZOeme+6TJO7bikTFhJPAYtPLAwdQeI6RwenuYQPh+LlOhB8cE6FMYWXgyaX//FBAoRhvOWwqRCLsSf1w3xo9OpyCfufVBYcgWcJBX3lN4EvnZ2utYsWY5OHacqDyhnbZsrqR7pfI5bHTcqddHwblIyBo4SB3ycRO+ajDbblfDHcg3d0rqesgi2+uqfwQQE3OmLpmtfK3Xy1Lv59XEGQ6OgoBOecrc0NPFfrT6S3PVjf1SmBzNFvBPvqt45Og3TSgRTqXFxKu3L+fPmusN4NBsLT5Neo=
  template:
    metadata:
      creationTimestamp: null
      name: fair-stac-db-creds
      namespace: postgres
