apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: fieldtm-db-prod-backup
  namespace: postgres
spec:
  schedule: "0 0 3 * * 2"  # At 03:00 UTC every Tuesday
  backupOwnerReference: self
  cluster:
    name: fieldtm-db-prod
