---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fieldtm-db-prod-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgB0sq/hHhRn/8oklZejSi7Rtek+kuI/R3kjVTpb5CORwkYgfPzBWeRWu9vwRYr4yWNWNKwoBSQwGqER5lQi0YCc0jg9VcQxYqYLzlTFiqX9tWo2UGhA6ySi/BGRlyt7+8RmCeK9mrRY93DQCd/o/pUtLaqu7yRvB7Jyc6yHTAMDgQWdh2KqKUNhUJ0n3lR14QLVTS5xJaTS96CdwY14BkbR5A7c1fYTEzjt7qhPRvRh5fxHDP7gp3drW6ONPzSFlLG1BuJttlchwkju6gfMYMfeag5svMSXGbvK2RYSqnV/1JDi0CVyrRd10Z/ZKZLlxOGagkFSrtPxmlwaYlUSrGr+hCJBisn9oUAOixNOC9aMJzDbruh5XZKwkQ0MaBlL9Zukb7KcWhKlMwhA/4gA/Pg6J0iEF2tWi4uw2dywiKUV+2vS54aISqICvAJ1NpuJrL6iSBlockL1T8rRlMbVpWb7wCJrA6KOv38cybIF0uwbxy+bmLxNwVuTt4tlqDAzMMKVfVeuEemMhihNGsRMlqXg0GUTdvls0C91dWjHuCSYNHN1eY4evJ0Kse5zJYk7TAERB9ila1864NqkMZHrOxWd6LMMI6iFuAj6rYw1CE+9qGf6TWtrAKlSMADi2/enhwjrRMDwPe7oDw70YF/UwYId0SvR/KppLnVUxek70vzvSlQGlpmib33k+MfrEEF/w/AUGdBT9spcvTqzasw5gzw2hY4DL5mqszpPE5tSpFxAhHZCaFrpZV+witDj9wnZFUzFsn7hAzLERoghvAqZoo+ds9tGMqnE
    username: AgBs2GEeD59WT5ggei98eVtNwg/HF3OyTYXjdsfFXFlWVSoznJxiibai0RIc7n0vbrMiaRb+kEzYjYYLVRccnXn93KewSrkVIN30NSjMSnoJ5Ydx83DOLRooHvnaH9Eba/XdiFJvIkMhdjIeNzoF571hM/4IE74HzbuaDfplEZmNKHKsUZX6qTbkm53g1splYQ2zgCfAOSzK/d5AvBLcEbvVnDFVK3V96obZUi7jvhe9enxMKWWYtp6CwByFmL7bW+AzzwCiBWG/zG8VXv6hOAGr+pE2vjE7Atdti6J95isvjz8Yvy/fDCjJBEYikBLNNFAFVfXWR665uSn8dE24BmWhQkJxbU1mdcPmENtXAGZg5sBit+mMGrVQezUDFLA+rkqiCyVYP/bPXiJC8mAdy7/r+hSGZY3u+R3IgRENRkV9HnGdJVsC7cjaMhFgaqAGDkiNIhHET/mLRNIDk2fD070y3Y3KWW/XbVsCagBbPwcj9Qb+JgpKFHHhqSTrqwAT0x6dSrv6XwhIGlh4SINa0VGLVDhC47gEMI4tHNLgVFvtTkp4oXYk0mEgLLdbmVmedGBsqjfSI1ruyYcqnQQ8SCkm1sPU/icl6IKCBCZpFXrFMIQh2RQ88ZJ2JwLb4X5y62nnYUvKt+9o4lK2KuSjgV92nNkTxAG4E9HSzxOx/6zS9UzY5tfeWKmuUw0USkK9vnJGPENTGI7t7yW/L54JPnkl
  template:
    metadata:
      creationTimestamp: null
      name: fieldtm-db-prod-creds
      namespace: postgres
