---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fieldtm-db-prod-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgBFZ2ZfSIAjzWPBqeORd2sNhtFmw9TYfKg00+walzzAg0E//6H+daFWkQoF7ouZlzxcpEcqBsJn5hIP8MUeW4aBvfvxsv7ZF3K0prqQ3XhszBj67n40aWS3c2c4DXJq1ne1N1INXsY59L8YqqTXdAnufTl2gBLzcLuY/HhHv6k+NEZdJK4gA2OIzf838pYmTgr+YMzivxYmmGxswPzL0wsQGHRJtFkdgoWcEQQ9F32BzXxRDObeNimHUr32rbugUmUEGedBlxx81fMq+TmNAWsxkV3FiWK8koEo2AWorZC9eT7nNR2LVV44rknNVJNShJhj3YaxpZHzlsb5sRYghZGrea1GumodS5mao7zCU00WZDN/odsjoecj4GdtelVa1Zmsqij+X4yvBzErz+XYhB6gYOUVo8Px0qZg70oPmsQAczfXtg9KDqZDCkwujy/ODkM1acvwm3cpZF1ZVpbPSygJBYCGrv+3OfDaaiA2Spq4A1rgniVC53x/IDQSzvPG/UggpL0Ev5WCApzNarPTpmRSk+G5KIDw1mfgAnpNeBaBv4qGtqgQZWanuvjecoYGjo5sSdeK2LeQFOqf76X/agDs/niUIReM7/wJwtvTc/4sg7zIEzaaThj/ZnyNbgFrL3rB5mJQmTFsLl7I5TALBzrD3jcdmdkQ6aBoo3n5Au/9ZpsRXSBhVE5y3Afgh6XrDSB+/DMUmCQnN+i51AxLDJmQx00NqKZwblrFOJsiE/0JokTlsTMQJRdb6z4yCdprnLbQoFOMctZur0DWS1J/LWA8Ml8hN3ol
    username: AgCaL5gWZtG/FSzm5alPGSlpSrPPr0m2jM0VH8KsJcmy5wPg0bZuKGT7T1exbmH7qtW8D33b4DVMS2spsZ662ekh2QAfqMKLdqL5+G7mPtp/dQEiHHbQonXeLEjv6xir1XRRJuA0vR26wzf/LNiGfhEVVBp//NzHdrT/AhvtWktWUrgCy0eCPu5HUlaIlVltgBdHT+oiaoLfU3WPF00FHRukMGySzCz9/lDd3GsJ+4IYkWaw1p8PNm+llYn8InMogL12u5gJqrVwJopmo679K0AC8ZSdmhHZfMd8C4j8i84IqgbjN40pweNeGDa7zlh+Bxwow0iIf8qBwBmSevI9qDW2VN7P0gmdf2thD31FX6I5AInaWgymlKHXug8p6Hj/qamYlafOjsxWxZqtDtjaCSK9p6GXQ2xIFZq/Il5nN7ilOwzp9RO8Z6DQue78b4I/9/QswOgdr70EOTEz0DtS6896lPFH1OdSVNUsh8fli0IB9o7zVrCO2FWrQWfeBuLFXlrqM5zSBVgp13jinJ7Ec4ac2AHNFYL6Sc3JHbTDBRv2VaGkKsm+RAymwugNOerBSDYX19V4hEr2WK/EZ98xsQqrXoou9a3kMmvOvdOdRzENq+7+0WsKzTC9a8VuHIi1uvBl/MVg5kUec1U1KWdYopob99xcwVxVQ8LV2Kc3QpjGKl1ddFTTeV9T+107zcp9FVxCxkFxgu1RpkKva6LtsOOm
  template:
    metadata:
      creationTimestamp: null
      name: fieldtm-db-prod-creds
      namespace: postgres
