apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fieldtm-db-prod
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 18-3-system-trixie

spec:
  instances: 1
  description: "FieldTM Database"
  imageName: "ghcr.io/cloudnative-pg/postgis:18-3-system-trixie"

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: field_tm_prod
      owner: field_tm_prod_rw
      secret:
        # Kubernetes basic-auth convention has keys:
        # - username
        # - password
        name: fieldtm-db-prod-creds
      # Required to enable PostGIS & StraightSkeleton area-splitter
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder CASCADE;
        - CREATE EXTENSION IF NOT EXISTS postgis_topology CASCADE;
        - CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
        - CREATE EXTENSION IF NOT EXISTS postgis_sfcgal;

  storage:
    storageClass: gp3
    size: 20Gi
  walStorage:
    storageClass: gp3
    size: 10Gi

  # prometheus
  monitoring:
    enablePodMonitor: false

  # see https://cloudnative-pg.io/documentation/1.22/kubernetes_upgrade/
  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead

  backup:
    retentionPolicy: "60d"
    barmanObjectStore:
      destinationPath: s3://hotosm-k8s-db-backup/fieldtm-prod
      endpointURL: https://s3.amazonaws.com
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: access-key-id
        secretAccessKey:
          name: s3-creds
          key: secret-access-key
      wal:
        compression: gzip # this saves a lot of storage
        encryption: AES256 # AWS managed
      data:
        compression: gzip
        encryption: AES256 # AWS managed
        jobs: 2
