---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flyte-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgCjSVDd7IfYB2Hpl32sOOQ9pVzH/xpCMQUM2fXEG+g2FC051RRjtlWMESfKW3AltmbQwWqG1EtpuufDSf1L3KU4BmMT6fVVWFxbwcv/EOgxf5p2opY9HHYEYuOIO+UhXXeAppbFTAk7OauSBN6wbeGZqTymoYqywJy9EptBkXkTiclIa79cGjMx85VfyHRfPauPw4xqacvVDUM9QVGkPKC9Hsd1uByy8voDc3QaoZFfwAWwLvNkh4dCQaTGkV4DdpwXPnSlmXbhU9mHlX4vPUEmN70S3d1BSaeBPldOc/MekwW1ctKDm2MdF2EiNKJie1fQEzoCzRlAdbCMizNAU+gwnaRw5bOl1c+VQrsc2+R3jm1mYviamqtJpLfd2y54LtE5+PrRxQmb3n11bMBBK+OLqO77xtkHKXAJUg4x0mtKRnYo7m+ZD4JX1TfnNrn4wmMFfrsHN2zIULD1Mbv8H5/5OCz5Sa0p6PtD0t44pgq+692F29X0z+8EnCoJKVeyu+EdzCKU4NL32Jzh2po/V61Q315CSRiTsLEdDg4yAOvMLEeoK2jdjK46CTEZLM90XwOmLi8x2HMoY99UAZSIEVfiq6Va9/b/ASK66XFzg+jJ/s+MRtHDN+f3D2mqIALYiRPTWvEwEtuImZfM6skDf+Gf/UD8a+liqNJloFX6oGe69Dp9bgWjYu6pk70pk+6GR32LiL8CDafNDZEbMZhs7rZNx7C5xUMQSyX4ME+tav03SE8lLkQh7QsRxjFatA7FPVS8JF2l9MknqSfs5kRQD7tYcLkR0eB5
    username: AgBWedDzrFhipHDkli4aKvI0aTp79kwAR3w7ghlEmsgLjQ44hYzFjL2gnl1Jhb/wQyUE01QMLEYQVvXvFJ35Wu8PostaschHZGrNBF1JgF9nt2sg16rbaAZQoZj0WDzYIQPbvHtNSQrcFrrkIeSaljJom200abbiHlllDfbQ47qBmlZ+Kx0GzUX/3V5IqYBqSfI4gbRqUTI26APlqrhj6GTG/1e+8pw+4j8reAzwwwL2hUsYXcNVsDWO2+0kZesQ7qbdeKldYQHnl0wDHo4LRmb0XeTxr6Aa0vnjL8Zlg6SL8avcv2hSlqTUcIb5ezzys7FzUjmpdunN1Sqh4OfLyI4EpIEXVdEo+mg9MyqkzXk67cxYgQbUdQiHg/rZsp6oYWpH193yRUOopK63gzwo1iyA0DLDrjGTdnuvNBUCBTyJ2c+HR+aFPe298wYHkDbGu/sr3A0xv+guSffVHQrNBYaC3f7x4rHrWlh26s/9mIXyehlY3Qur9tpaDTD5Uu8dEOtXKuNADkEO8+lmozg0n2nppAmPqZAFst7/PNppXXYsg27zDyxsh9SeXhHl346fn9C5bXmb7ypRwVznBvu7hQq0GNiYev534OzqCOi7cm04BOe0rs8aEVnvGUFC92eG9+RtrEYmWqp15nPsX9iQqTimwp6lPfj0DwuwZqar/3wqah0b3aDP1hyowlV3tdErOZ6VfbiYPQ==
  template:
    metadata:
      creationTimestamp: null
      name: flyte-db-creds
      namespace: postgres
