---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hanko-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgCiFUfxkdNUvcfUzI0Molltm+yNBAnMVCVd22n3T+f5KMWOkoux4G1qOv++AgJi/LLK4IsELhJQiufzW4ZF0bTTW9xPF2zY39aGp7VOUhcn+KpIOeTE3QOYUc42wpJ7doTQQF6tvlhyYyyuIHNkrbfhWMSrd4G4p6uDWKyfb0kV5JRYdzorNZ3vLmEY6J6yVi4P5ZCcSLN0+GG9ZO7uPI3QFRUUcIGP8PWA2UpGgXi6xm1u6J9Elw+kp40epQDj7588kPKGZ51OUhucFdOAscU909bN+8SUG9QRaBqHvpxBxEEVAFEZY5g9lfeQnn9Oe9Bo8uZzP4BsM668IL88Gegq5tfeF1eZfLdObn0KX2yNycMQSAZanPzHIkiQ2szl09f6d+SFqk4WlxPbMPV880EYVD6j2j5Ha+UJpLfCH+ZMpQCjYrHzFyeAg0e0ryfOb1FfOMN0i10xeDRXWDJzHaq2cCi4SOTM/Uom9kgCCTNKRoa5tzLfft9Tiv0hGg4JswtHOpQvaeXTgG+FKGZkAeIlbgl3B0KEsPf7f8CIfnMbfvHTmiPnvkFVOfVweFJ3TrH19d0ksRnj7HjcCxvsVN1Ks5+Hn79SKnk9JvpTnnL9S76DWcyhGv7ta57wiMrdXmOrdtRAiWcoNknNOMBPO9YETv2Qc6CosrqH9pVkDvSR6PMS1tNqn95Cg8qK8hHPNhRecUeyNzUXtmhzLPuGDMtKXdJQwPl2rLv1libsOWzfIk0qX/VOdQdWGEPu60+Lr0GN4nspdRJ7zFAYRBlXgNnpTMd6cvKL
    username: AgAsPXtJQg3INdhh7/HIqrlD2Iw973pF+1ZYUaZgSg2dP5zrCsW5og12KmVJGs1C90qB7HEUQxjMDDqp0aY7KgcRhDTIXIUYYcb/CbRwLhmNWSxEqvg8l130HcCfblz66296H05Ta7AiNFSGxkC5/SoU1AkSEV6psMCTVq/aT0eXYVkdcovtC7QtTmuRGUUWatuhT4EjOdE/VoWHsNwZD1UVqhp7NqpbYAqwV0Ob4aL577w/cAp4hl2403ZkXHyEPEwSWeU/H+IUWEr47xxEzoXGj5PMKoMPHZd/sc7IlQWvtsY1WMyzjfcSY9FP+Ebo7RBp92ti1WUPlvWnIlPNCqiIlcOTpJnl8/qYASdQtkN+Sz/oZ4keMbP7Jp4srAKSztOv+dW79Yet3tMrfAFpFHrGTaLbrsLrsOin3MytHaE+F1onJtp4tbg6JQp81G0idiTdDQrLG0ia/13z0YJyG0u+ArmfVtm46QtXApawayquhRxXe2+r4L8TrXUU2RBKPZB4WfqmuDZ00jAKr3bZXoNejmaVU0qcfBElSnev1r0Idosw44anaYq4jI2+qA/uzYhjBbR0jQuWRA7V7dN1I16oLEBw7nQn+dmkaCVtYepQGJjqnBP91UGeaBNgt2GDX4l2ihgLvbf7Ye7yfyMBhOw4NMeyWLJMlKVIWojAMhpKk7BirfJDqs7/hQyc8GvV+1NqzKbv9A==
  template:
    metadata:
      creationTimestamp: null
      name: hanko-db-creds
      namespace: postgres
