---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hot-website-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAPKFyzxqSPhGORi+Rik0QRLthKRWpiYZuQi47IJlTWQfyFnpXm9bd1xuLKtTqiPL3fy8+reyiHgkmnDUgQ/AWXnGL82p9OlLTcGIcFzevzMmqp/eyY5thy4IHBHAWOmEilAxBrgGQ9S5feKJoRfnn44+nz6hnetb/XRQCBrImtOOCpc81FDjOs2PkLTJ9Gg47bH5a+dya/hzEJPEthY4kbeWsb6up3EDrgfyx67xngf9b6oswjwxgN5JwoRtBSNbqSb+QnEmW7uu8slf1W3RTEexMdEFTo5CX69NXYnJPc93Cbq7e2sLXNIpuZrg9yw8iIKswcEeKmEDtyvqEFBZul8kjmwYBj+IbBCsClAZIzDEZIUDLgKl5ibhQQXw4WxGmEtT1NyYlvGdBAC1BZwjTK/1W7vADLgHZ5Y//8hjpKveSmC/x8TZGEH+kBDbrR8C4yqVgglQjhYlr8UNRYzT8c7nimcDvRjhijEG2saPGuPfY9z6M1XIcrK4954CWNDBmm2KVk1chJHwpqQ7GWcC3lMKq7RRy5ZBxuE8RSiMqGCnUtSDX4iGr7BtvsbyFbx+g5H1wxtMgXTIR/cLLrnhT+R8HCHwy1UQAcQti6UEEZQM2xoWqsT7zgWqZ3vyIS4M77eb/yWxPgeh57NTiDgPXYiITWGesBWnSwZjCLz3BPztUI06VrIaY+bD+Ja/lOFpSDzJ3NEI8F/5Q4tyjeyNETkK+ye4y1IkmcX2hhGvzH7ajQbqD7A3QxhDUlhml0AJqMESMjXMSY2qnkVFI0vlh6/TvfVS7w
    username: AgAZ+pTNbDFf+4hmgtM5Q3J6ZLaBFV0sXxakC/spEFv30iFuuh91m6nKdL9ALVgaiEPBojmiOuzTzrEuvUF10sOWW5pOAurJnLsj5Vna9HAdxwEQt/wHKU5Uf4on3X+HQAmK7CxcO30hJNaYKhWv1IWqwsBD/iJ6JLcenxUzkAN3t6Vz0fAo2CSZ8JexKWsowLgYD25JPblmC+tkFJcoKth9nZlYoV9Ju9xgBdGwVNdO5XkhhoDACBxGW1Q5PFROOIVlYpm4LYlt/NwW/f9QzK/JWy9qzLxbehckq4tOBNbVywlY+F8qjtKZedVI1ZA+lnR21XbBCwIp1DAfgFIqqyRV8g9chweBsjm3ETjsw+oq32O6s8RD4MYvubxxnj/zxDiDDG/0vbsdJOwJ9LraXZUurC7dCHquaXM3BdjjUWdQDRsaTpWW4JIjSqFltSmKtL2I7SHln8JZXrg2wlIkxjO6LT1R/SR0/C314nnmU6C4LYZBSJe2VMTyVod/RemrnUVsu0aJPeckNlbdIu6gdDBedz+E9QZmsRH5gOFjUgQhpze7ajOamBmVc2WY10zK71yEeBgNdgL3jCUZ0Gy7zZ5zfUT+eNHNxwbcCyxXq+ad82vnLmEYr7W6o7trfDw1lw0HH70MscCixfvE/SgCOafacErV2uHaLzm54fIiI842Ik5nTaSQ3pa1rzPcKVaujv9vT+aPm38=
  template:
    metadata:
      creationTimestamp: null
      name: hot-website-db-creds
      namespace: postgres
