---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hot-website-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgB8OSXIwORW7VlkuODnqZ75khRm+1BW5n+v1N4EgtpbD1UJ8COTgIV/G/4ROSaNJJ/3r3xEQo5m6GzMiIvDFBvkKboTvBhmA9vrdo7sO2csB/6UTeK033rVbBaoeLQcedY/4NB8hTMFPcTh652THVOTeKfHstAtgCvVzF5pYD5GwfZw5Xb5C8dEDJFpb66ymle9z9hWUOpOtZbcYvEuFKPunswXTzwmy4/9Ow+rSf5Uuc8vLJvxVC0CU5npk9RlRmCl5ldWhgCCJDND5EicqT27CuJnZTJQNECCy7ZrcRcB5cLR3+NgvPdxSTH2u6i+MSiN6rM0SGxP78KFbUUoyTmkON33tdKfTrk7wuDonGTzzDkMSWpr3PJX8mYbNQ8D5M/L6Yj7A34jy6hW8u/ZWwqYlQw69vi5cAcdAR3t2UO8yygUUFYqofQCbrQe7wUXNfTBxnRAvAezeOIUP1UV+sjRA5P6g69B6WNv8PcU2qoZNSX2r+93cH3uuUIe/Ifgm7bxk6LtA7aP37RbNPFLvsHcP0rKsTk1lc7gWcZFvwgd6572PymhZLiIiU9VvG0hvANu3+LsfeuUR29+eUIseZA66GVOkganAfGua/LdkEYPuWaZ6M6GVB2wJoE6hUN9XQiNCu4vZB8UZP5L3w/SPnHDLJhfJdmAKzDIwSY0Bn8rVsD1eQt/K7gyC0+SiAl4EhUEUjNGpRitJOi0XBaqDzyMlOBPtUe+wuIRRCDhyNXiOv0w13SmtXHTdXh9xe/AEgkEuKzRNqIN+I1V6MQPW3XtJVV5hqat
    username: AgBvtaG0CpKyw+Llfs/lh3kdO75HEkW939T9r/z+7ZbaXObTIqSOJtjZqc8SnBqVEYRfleo4tQN6ST0eWFSIf0cavhg3lIE1a0AMnZCT4OHyBhZeI58IhEiQ0nvGYbUvOeCEGCfB807jt3sVLNCX6aaz+WGAt9mx7hh8iGBBC5guV38IR23IvSwJvjxZSiZ2EkQgudaPdFmTtqXqfU3B/MaLCjd4iC6hyXbOZBfuxCsKXkzEAOoy4HQaQ2aY2zrk5EbF0jyx0YfGcWheNG0L3dDZRovfLgvuEJ2zeqroFJMguqPzVlv3X/LxZOwKCZsLjF/2PpgF9MjOmm1vUCFrVIDJlLnQ+aBVEC+bQTG6Qy48oJvP0XFpLyk711qiljagQPhG6Fg03PuDlt8ah2MP63UKFNPG9MIxzudONrtlEqFxXLKH/m8cJ8OPkMC0bB+/pkgqXO/Pg2tl4tWD8ONcUMSH1mAPmP9mo3E1gdjyalDISlpyTwuewKP5kCkpTTNKVTePU6kmPV7/EO5d+VpzKVAAfsI0F8Soaoqv0dGpAil0tF+QpkK2SFkRV/4mwrsq3l6XCUp2a//bz0lqd7Swc/dh7x6XYzkuUM/u0Q32OAHaakqCqDW15zV17a+peMfk4Y73T/c+4G9IG+VDhnUasN7J6nmlLe1ZSdfMlvWy/QSDUESAV2tXeiqqWHh54Li8cAMf2CbaD08=
  template:
    metadata:
      creationTimestamp: null
      name: hot-website-db-creds
      namespace: postgres
