---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-prod-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgCeomSGxmAstY+gFrL88ukcxmTB7XJn0J8txU7dy4z5CDsSDjyvZxu2VZwoRCHVLJj7XjU0o3mtwNGZq3p1YhuC/IHVR4ykB4URF2BnN0HN/Tj2jsrMOxc0MXrGGePQzkF8YaRHNdLa/xdIeAkCDp+1xNjZUh8j28L2wCKXXabQjB2yrx3JYCL5AGcu0DJSaa+TDXJrPZpbYhnwdZRQdD9vVuOddggmnUIpeIohSOOOKOOcvi/D7jhXvs9B22zyOzmldEoO4Z+jJ93o9uxuWLbMtNLtbsucqwLs05ReteU6p8pwBB3IzXy8YgcIecpIkBNMHP2zco5N9ISwSADp+EtFfzMqKZ0LwH23kZXSPUlraHvSYdR8JViSPPNrYDRNRk4PHWoAF8C1LV1EjWgKUBNXesmLK5VeF/3UUBtoRiIXfugwFkmuDV+JiBN3YYz8Iq2kgERY4OSSpQmY+0cPjptiA71MXT/jbspEOg8SIWKo38OuJrMWKuUmrqX6MRP4FEpqnbXKawIYF6doDnP4Pr6+KmAx24JEYUtvQR5QEawy8gMXxdaG3B2TLALuZaG84hIkAPGxarOYRgupinPY9PybR8e7XYaSFE3TWycxecxwNqZu/bBXdz9EQcv8WX3ot610ZN9L8EfGgUrxIor9Rd4cZ9TOI9RzGeutqJHr51tMD9SS9ed0xK9/XsNZBBBxbgSmeKtATctr0ImPlfa9EUYpJ6kBBIjxxQY7yAL1l2UyFA==
    username: AgBDJeuB/vcI7VgcYbt32BIlv9p+dy4GOuNLkmmMIJb0ecuWaEVqlc4QUfyot5Oetcpyg6mW/H6UD+XtSwvD3RX53GeHAvQLwIOL9CYrNBfMRLWvNp6Twa5QwrqLSRMFlWeFdZTwR9XOdqvKw/V3Tu7c+gltzT53L0Lh6C4f7VWT2Qj1TkFPuVG5Ei8U02CPMWDb3/mQh8vXrZ2XLbYLq0JmEqmm79RQGYJsw6Tcz+MPeXZRFb73S8byupE3AjMeNWnjhlEQ/502IK6mo3+oSdvu08lJ+tve/C7QfQUQPDtPQ7GwV6+yW4fYFnrD/k55YFlKi1Vjufg7thNi+1wSE8uo1jtg958mkRtQFC1hgEmYWpsGoi5g2RaGUyF5VkrYRpMo5PWd2z+xzJFXy6rWS9unNUCZA0bHWkCL66L+3cwDCTEFNN/wYT4j59iJAX70DaN5p2vC0rKtdXLkLKExg8NIVkWB69eEgVzPfearTYB+LhnDCobYAhstI/X7JQozG8c9LsVtpVROEWyY/jlQiT+Sw7wBXuvsa/QNxr3vPO3Rg+bIrW6UaJQdmeWaH13zh5/bgNnXsHLc5KaYlI3fEo09dfEM2vDkBjQEc8nfzwoG857EfC17J/nUgaKjfupkBUF7eut72VixjntkaeUeCII6zj632VFpcF6KhY6zd4S5Dvp/rul46A2eTqZBzT+Q2qHGP+Hh8nNV+Wuc/y7FWIEBJjMxjA==
  template:
    metadata:
      name: mlflow-prod-db-creds
      namespace: postgres
