---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-prod-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAMGHWJsBAbBtVCxXHwtAtrh2xZFrNykaPu9a2bwtHpJ4bcx/PAoEbO5vRXM0FFwkXvly8MvWDomAEEIFtM2MLyDWzI4Zx3MuglzurFnMN45uYJb3c50gH6erFfCP7poUxYQUymt1fCYqPzwULBk/An2vVwOIKkflB7AFVlta88CSwXMqbAm1dwDYe7yoYlKngE+PqINTXgtgnmOgHJ9Gm9JgPv5s0dK7ZuTOlrM9UP5JGk4QoMQqqRLiIxFaw4E2ilkKOXk0A136c7RVL3UHzWxwzpTDtSZqg920xywAni8E7nsNXBW9oIlt0yfx3oDx/T7U3YEfRHr98Ofqe5ex8+8j8hD4bp9oKdVfGkLU0W1L3MNMsgOC9R/uv6p4ZqdrZB+MOP+J28j7K9WgnPPb6ADh5fFim9o+JE9ItcbhgOfOG5v7EGS8qobUgIyu/cDDnWEeNPiqApZ19r+GkwaU7CiEeVJ0DQNlEdtOD6OMzHo1D+Id6VCbW+hjZjrliYWWXJCUPafNElP87evDmW/1GnCI6eAK8VroTTO0cm/naW7XhBXWKNnmmz2UVKmcOXzrFuCEAgzNSDyNhltywNBn3b5f8AH5lQ27YPhh8IUEn13O45ttvzFdzAm3PxcW3yLKQFcCCzP+2xy/y2MDGUoL17pDJMKVz9YQek1hzCvNi5fTDhUIfTcCbbOJ/MLvhO77Tn2wOMV/ZUsnmm3hZxmybIHP12FvmKaTtfoCY/phPfZw==
    username: AgBJlOQ0ZWOM5LpD+itbXiWp0Aw/LAFwO7pH1RnT+h/5qBIV1MwBWV8B2KpZwKlWnne7QfK9lKhXT5wLADFyk1WGwsN+pISD7S/6bb4sgq1sMHvN0KO9ggcsI1gIAE1owu8cJ4U6Mx2k/k7hEgVlh7gJh5Cewm0ZHYgZ60j284OTOoA7zi+Kw3Rtf9FPZw2vMcopB6lVSWj2N2M6n6EYk6WTL3bcf4J3Nl+32E4cwK64BKSVIkH/JyEcmDTQM2XY+IMYTDR2ggkiP3XZfpknMwXVkapcumQvQXu2B8m2nuK2/mnLp/Vl5148Icn4jIrqqkAiL51zHCxDaE7ElpvOsJJ0CoT4BaUEwUe3IH+6RtupkeEiiRVS9FWtG8eO7wcpl5ru9MhgNpLxuN1in9xNDKaPqPKT5AKt3e86WTLzVUNc3hzs2FI0Pq2g0lYWAciuMKkaU579Hhmg7MG2lYlngeq4SGjrXfTkKHDUXxXNkHaqF8YPEWLlB/U+0C6n5W2WhwXoKOmR3txGEWfo5sS+vG2ZsixVCuBlCNhOsH9x4OWRq5SnXm7MPdm9hc5DNS8+cFB/wGR12XsIDtXC/4F76JU//MHkUp8tuHHyryki/ccN+NyqJur0NoM3eSJ7XO5PoBiKJqbXgRd97ltwQBvWbYDVZXQVnyu4q57uV1Q6bc0xkxFPFIgYoMGZOHiPjXmbzVyQ/0TJWu4=
  template:
    metadata:
      name: mlflow-prod-db-creds
      namespace: postgres
