---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAzpfNl8MgXot93t8qOCz8xtBD5YKOiUP4SrgG6R6WODbXhEXwn39PG4NoVhYPw6cegauaFT44y8piTelbICVzocz3aR4JI2h/rEU8tKWJdReNfWDCJPtkAvt4Xl5x6hUTFjdarZUHhskMsXhKUYOCYH6Jy1Mkh0E9fT+VVGQavWGgrArpHxW0RKW2TmbVyqS3reE2z/xf2mpONb9spyBqnfLrq+X5pPMU9Qzu7GfHbQUBKhQMWiF53o5NAFdNonnXLibEEmuSJesBB/CmxeJTkaHSFJz/ZNgYmjdMx3wQ+aMJDivdN6Wvykd68vK8QMRrDciukeD6+FDYwJtqSgYvGG3A2zmlj6kOvXuQrL67wLtSZBtLW0P+gswxstm/JGCks02PgSO8AewTNqCwDFwXawziOV41xm+DSrrUVBJGbB7hFjvnZkkkmbGjK4XFQy65Rtlm6/DR1cjLFTiOBMSUUcuaBa5ZeHWmFbPRG0PlUMEspqpTwj5dJ2D5uSyL1MM1Ue5vSv0FWPArqOvuwxXGlCd4w7xopUZWOKIh0aiNbSaXzdoOctw5o92IVRwXZrpkphYOH4gJXGee8L7Oy8IrsmZK985pdSW/HoC3kO0bhNeYLR72JJW9Sh4zFCCuNgt1CECoKCgqSm0MlzWxIsmn1aSShsa6hpsYolE9TGNh00gLS5qjIKoIL0aNgBmNoOpEy5PpB91iYujqQpuXrTpF8a1dauGM11BmqQYNp0aCmLt6K/p/vo4pG2DXGstttWxJp0yJJaTXe1irMn/oiYTfoxJJ0E3R8
    username: AgCa6sQynYyYYGwSIb7MUwqlRHXAVviZIBv+6EuCrl9zeRRv+E2V8+CKrfYZhR5ocCpA1dqw9CfzLvSY9Dg48vVfUTdo61TTQ7mIAonxjHlKlIRbNJVnUu9oWQB3gFhmUXotpgdQ9SXxb+C4zo/RUd68qg29tAfUsY4tiAivdofAfNPp4vPGY1b0h7Q1NIb7AaW1txeWB0OS5YwzqIfK6x1kUoL7xXkOZLlKKcV6mDVP7DAA+a/91HPJtbY3OhHTiurXavxrW/xVOikCz95vPerH03I9VYRaQ/17QOcb4Oaal8HXJ9YazBC4uaUr7ovww0AbN5IV7qYXZKg5SqsSRsExpEpvhP6IMt/T9SQ6QnRh8X2MRdBLW9dOhmX3OgoIrK+vmDHpOoUqNEDechNrg13cRwi4BNCx1imaiEuxu7CDf/Cr6MieVkb2R1wvz/cl714T36kz1Ba4y7JatYos5/baJHVoiOinq0H6sdhHnBKlHOy465t8Le6U9enWtw8i5yJxqtA+zb6Rsk3DtZKlPAovwsNwNU5euzhgpkq+cNqzqeC3azbdWgtg3lgNaGZmuW7kcDCd7XzQ89UfdjdF7idbahEKAoiJn9VAJq0Qomegj2ovR9PtxhOvsSmhvq4Ni5NitDclzVGO4UYKNchp8ROZkiwOsrM2sE/ieeJw9LfS3ZrN8vVDE6KhnLG614dPqnQVdZwEDh4=
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-db-creds
      namespace: postgres
