---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-prod-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgCG541GYRRcNjVhiwhpyGxUVi6YsGVoDzMwBOaEp7qXZWGWeIPEak3oGcBHcbRentNL80U+RLNft22TmBmokqotgrQ42YLLL24a2lOeXkv8M1elyBG3pt7o0yQKHQnJ1pG3QC+zi00dM6opokX4CPgx3LhR0AaImq2HrH5rU+IIB9NaU1O69f477iuct0jo2V1pLFG4Aa52f4XEEV/f7E7oZHeKg4o1bvM8OnuMheuNC+RXQVzGXo8FSixuwW2Ylk71i+Hu8zPQbcSsrFz79KDqDp4v5VY/+yyhDbn6r9QcudTxJ9Mgm7WMPA6tkxOphXiS6Cufz7qg9tVfE8DwfJW9ims/C9TtTczOU7k6UaTkvq2CNzryHBk702DznwCFmCoz4NFY5tHyYMiM0+9JZIuCGjB/bwkbGGBGTacTqCKLeTOy+YIMLtej0P7t9RsFgdgZC9k4JxadnZiJKVzganUk/mWrf2txKoCZRe72UmBVJKOm1DhZe8iBNj2HKkjvY1DTT8bsRA6Y35dxs2eayq7MLEeJiadfUi29L8bIFE92LGtezgKHW1rDOcoWBVHiDbUimRMnsMIhxhWrzM4nQnpPGXjTsSwnaEb18Aa84pBVmQ3hWNPLu+Az0ZzvsSZiMSlFRGvB/ZNVE4s40jabdVm0gVyg3BfAHLpb0HTC//ktGLK/6vbOxWyvHB7e1rF7NgXuqh4nkH65FQwbOc/61jisZ3clEx5YGLlV2H1I3/etmw==
    username: AgA2N3k0uBybS7dKcAaLzqSHxJX8WVLwnHaOloDSCNWmVWgMUg+KVco+HtWFHZ+kO4HE9RrTPhOi3FQBwPoQtFYC1uaPwRDUvrsGQI5VEG+zoE01PfJiYbDoWQ8qLD34u6pHpcM9LYxzes4o4zAGZ1PGjHRuVr0POcVciEal8LZeQWKjTKvtdkTdZkVYnAEIsTfxRVhMSSYLCJC9DSctUMugjq0zLxEtsSOxoyQRtJQbJNk1lGu9Dk6YuY/0mdf8AdcchHOkIorFiyJHiSupjgw6Cme2p/lB7irtlspvrdjnILnsLY5gB3Nju+9uzzLwXj08BGpv+rGjE9MMaTelqmvrNm6r5vcznuaEKc807ikoBPnO+nQIz50oV+lHsIeBltDvyIcSApp+/rzgyC0Ps6Mhc8AhgvUnzpUs1y9qv5ahXSPr0u4w21cH9CUW6zFZkydp1AjPEZXAhB6KEt05jXI0Rc2K9MuJRcNAO0dJziZnwikgSIi5u15KvMhP9MixZ20fBxqPyCxFHQ6OROsiYQL6nR3sxez9Zi86aioXqsMNalKfXtiN3rQ1Onm0B3DpA3d/Rk723oyvNcKURwu3UWL3NkYMs79MZUgbo+XAGdknP4kPQFo2zmQmOTGDjxfPWGZodqrAiSkY/Bk1q1Mucs+qKmiOOkGEb1w7/pA2qACJBJwdYgsAtS7rh1mOFtMQrLN9Nc/23rC9b0CsiKrMT4IfwttOzQ==
  template:
    metadata:
      name: mlflow-prod-db-creds
      namespace: postgres
