---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oam-uploader-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgA2mDtN/K3iiria1Czzu6Jl4FhxRXctig/p9Fufti2s6DQUON6Wk/6XjS6mIURjuPIIhj253beB7MYPOwCLoXafosMRSHOj/uCp9P+Mg0LGMdc8cHTqiTRNDEswvGqf592yDl2DoHNB2WONGKfVp1pllaVlUMMfnkDxNJCud5jiwCTW6QXbIiC6g6k2BHaV7TYXE9XPNlcE9ZtbfZeO5pxybg394x8lFU70x9D+9DTGzMFcRCq9z25OfQ0OYJkV/RQdtp07qR92SPPcpDkH2nxaq/a9WGmSXgUyKnV13yLUb8iGZt7dr5vb2qlmoAJRX2ZzwgqndXE2jm0e+ytS9R6APJSUOim+RDwYMC3MK2ynSAmbgXEMycIx2A/F3ezApPlVbLKjxSIu58FVAJc+mR55Eltb2zEYT9FXUGzZ4WAqSIehHP0MOXa2GBTDwHTLI/PR4+XEORCgLb/560L7RFGyk1CQm7AcpzKdVWmRtwvA0bBtxZURlJfg8Yh9amDBJHHx2QYNrD2eduN8/A+c6VEk1ZPS0fQT1AUYWbNuYpOt2vsVdttRween4HJlYuzB5T9d0jqakzZKAtQz8qEnXLd77QYLLzJ9qmO8MQsDPIKnK5d+zh9lO2t8dN7DeNfrRNYjeQrOFal6E0zct6wXj/PO6Sh4O5lLxMT+g6xaHeTWEKqjViWz1N7ye/aEtnZvGzqAYyUJTrh2B0Ovi6/0wYKvk7r99mk/ft9Cd1mWj588qvUKFoiwt+loiN/ezKv49Yjy8YTw/GqQlzQp7uOXFHHDO+zDEeb+
    username: AgBSQdELXOgJmLTfvoe83Hpdylg25BeYp9V4dWlPB0wWqYVtEukBVPE8QMH2BCjcm94VW39oX2P5qzdB89cdokuxTDUTQcJAQp0YvR+t1WiBj897/cXk0MRtGqHCGNd4GjufqpD1OErniPB2rC1PtZCtNO3aT/opeS92o0e7sHNmVQ+rNjc+G6GFcgoswR4W1MFuQnNBMLl65U5rbp4IaDDEe36j8jkqmVIR2A4vIIQEo0Rh8k+XSnoMfUKKkCl+pmopUvAJ0/K/TveZn40xVpmKHito8x2QYbCf/d4UgBL/yLEPjkmqAR9H7J3OSRqcCCKRpu6AULw7cmgJTxt1AXs0WXvahmLx6BWSS2T33JJ4ln1h2jpVr9IpoFzG5Nag0b1A3ccCyhgir+aGK6Fmn8rNGfER7F/yykxYcneINzyUFK/3Ws4F5rjQUun//jSNoLDDXX0nRDfumhSvtblddvok+vdAu4qzBV+EMtvCPhbe0Hx1c3FJnrQzLri6D+1Cophw6tRe44HPrJ2JQLYNCDRJB6qRmem+umhO/sEJ/nnE7rDQNj7pz/TjoGc+vkUdvGr+8WWuKVXsPypbx6ZfF3DtGLTwJ/EOCKKpv8nKJbHuXHx5DOD6L12Xfa5fHo7VcClIUbPhy53VaAVVBD2V5ETgHMF+SxfxvK4Rd0krJ6I/TrCffTOt34pLWPgbgE/if0FSwKkI512TpM0FEb4=
  template:
    metadata:
      creationTimestamp: null
      name: oam-uploader-db-creds
      namespace: postgres
    type: kubernetes.io/basic-auth
