---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oam-eoapi-pgstac-prod-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgDDux9OG7l3uxk+eGBFyv6gejO0H4f5f9hJJtfffBlN5hzIGQ+HskVTdChGjlo+uHAUnjBBw8IP71KKby34MJHNRzw9DxyBizjNz/f0djXnabi/SA+pRBYY6hvnI9sjvcHwudDQxCSWdn+tdIcToPGyELHghgN9e4PS1x3pSMaumaIUTwI6DnZYBZ7fk3UQYhxoVOw8g8ozny0bDcVVIIW+IDyzjcG2OfdAFJGY38+BQxYizwNBRUkVNvqTCmK18J23mZYPhv2CUcvoC96XKreOeGI1A4ZCeYeGYtuWloOS/9D+GfxLrGapqtWcXyvJ9BO/i9HrejTSWL0Oaugua7wi8O9fn39xzvVXRZwL4ZJi/6TBA1mDVwz6dMRpS/tZxW7p7X/DLKS8U/SUUhZPsVuyg6GMqMNkNiGH+SbCExx+54xt7potJm1ToyvWL6/SqR2k0cJxht5Eial26PQ1YzxXWUQPCuFMnTyRoO617Y5BtOJwOsoWjrhnIYtiyYtnfMzzbBMYHO8RZkZ6YNHkTfoosUApx56NEoSri6JnfIhKZCnutaTZn/4bFIZnoKQBfmW8bfb4VBr8XOQ10QHe+IgrsmI/dVbGohEo/MnoNKk7AorCYtMaA/4PYyePQijobzPjkDUrRsns9ZEGgbuRfpjqGNeGiLhSfadi5wo+ap4C7q4OjxrN98TUZ6sRq1n0HQ6XHH/SvXb63N2tWG+WsMrGzGW3qHTlJH/TP0wPWoBpIKlT9iTVz0ph4GdEfdsKpmEYGa2ZWXEwiQmFXEgyfkHfSYbuvk0G
    username: AgAKJ6B2ItdJ1BRUZFKphkBAO5ktCCBTIQE3VW2KgUS6YOfrJ3xHnwUaUAKbpuDqj/wwF4LwoAicPvuUcqR7I2RKOCf0ypfFh8BSMqLYyXPXH2M/Gq9QJ3szHLFtSeytDaagCO5MVIJahThUUZtia/U/LA3Fdd7t1tgVfd3duavU3XF7zaqGXIo923FpRfeQQ0smzhLVj2BxoKFIgNd71i6puJznWRhXOq1FR0wbDxjqTIsEF1VTey/DT047TtImsyya/LWfRUldrtQfP/7jeKlMb4HRyRO5apl/p25tP9qK8/h8Og7YT2A71WYcBA+0i5TBrIzS0ypjSrqmPSHrX4RlsP5R3OfrYfBIm/ytCfisp99on3/x2vniI4lNBF0xnnELMR4QS3XzxiqOC3+vHfDxzPfBaDPyAm+yCxIi0fSKCud8biSWHlPGcmhnReWPAWP+8uObIqbWFAOsYjJCHm4vKRkE2J4c4+YY4iVl002H+8x5XRmevUf3w1+iBEgR3mRxvGTQuwW0v7Q8omAFA7MbPyAxxGe8oHW2m8l3K9HBHQOrin4YoLK9lfzHSn1VE6/5rfiZE9gKlmt4R082M3Xom0SWHCq137ldjixrM3oPWGLw4/K6UOhVIGE48LUyEueCtSHFBtT5mTkP9nnUflb7cWy+6ND2+maJwqWSUV8Mk3EtmT66AxQu/kfOFfp/WOfqCzEdkAxwtA==
  template:
    metadata:
      name: oam-eoapi-pgstac-prod-db-creds
      namespace: postgres
    type: kubernetes.io/basic-auth
