---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-creds
  namespace: postgres
spec:
  encryptedData:
    access-key-id: AgBJdsuS3wd800YmGEk40nbmyrfJMvEI2kyQ4JV4eDFr1jgtfxs3VaHOs+maESHgUjMkQTI/R2j81pysa+gQLyU9RPBJXVw/zVL44GaBGukXlKAV/0VI3WAs/SV77sSUZOymwFtrp108zkdh7H4vNHqhNYTu+dfB8C/KkwJOCX2uUiWzR/KWWzKorxzW8TElewpe6t4rMBKRYaS3I20BZquqlfbvOFP4/XIcvs+dj8mJ77weEf04NDgZM6uXi68vGnhuTXFGFmPueyOHbdInLJDT9YkIhcwiJO/pDn32fEkOoDsv6p+wYz6acs7X8/Uq5e67B1+7erMqn/VkeExLXCrgxAARkEz0+lkGX+qpVoDFimwyiTsRVbuqmr6EinlKbCm33H0oP6WqJi708gTK3omEL3iFz4m40nCI/wuGEpXRKNLTcy2r/g0t1dP01GqF6s4dCgvHoZ2keGeh3C61haWXYekIBmGLlVhqyWKysT0FuFwX6ANuachl6/c/AdU682SRNa141q7i/wJc3hn7LI6mpe0Z8jPBCb0DbosQartVUyjLIKgEERRlFhoXtcrrThC3vqUYKd1smB57MtaVy5Nc8TaqKje0XJZCJImZYw/7IE8aoy0JVWeKD4eTLOPlMfWR8L5aM6ILRY0eY1yHvkIvF4tKGFa2rdtgK/rnxpAVwzoOKjn2tUQHZNh5IS+u+JJOjmWw4dcWYf8NV9JWSVbFm0mWMQ==
    secret-access-key: AgBXFvUviQF9AX1JjnFg22BqqEXP9NcBNBse4fXRbtlkQ2SpRFruQZF35jvu+85TzpajiObJ39L1ADdgxNQs4aJGa4lp/MuNaNqHtB3eHfgHZv3Ptn2mXl37Z4ikvk6Vj4djN4YvXJqoMzPGvlJiAs4A7VSedX+9ZXdCGmqcecSbZykz4kZ9kaimvxoPQsXtNsMTc6mixKp5d0pUjmLnfKLaZZaEsL51YtMm+E45l29WS3XMTq0mvFY43VttZvEoax2bpko1xZKM9/PwjChi/8FBOcYWIvNtQGwtHqdVDq2if7idDEhXEhyHSbAHAPrp6yW18BSEA3GnA8RHM8c5jDxSVqQ4m5LZpbbBQydQqUCRGDxnZqdtwkP4bZ1Dn3n35bIxszeCdz9dcKkSq4fxW7onJAcKi5+9hiT5PHtLI57Lo+25XnSvJBG2yam9rHzVAH35Yn0Z9RLK8E4VuQfepKxLj8mcgwl48HFLaI6SmJqIFNbwERXA52LyZPEQevXdqCdQmDl4/+50Aa4WkiEZwQY/QWH3a7AYa8GVPqo91Ul4JnX60UH8TGXQttUrSuQvH/9IQbQmx5Ea22xTyilzhYml21yAamLRhVt2QXBbsIuj9guvB+ndHVMngXlxIPyt85zoA1c0ME8Wix9mM1+oyJI822msIKkqL/7J87hMunyVnI8cZDRkSXpM8WbbYdJ1U8ECDuuXy7pPe9XUxSAXvobfRW/5pAsKAUEx7joW1+5FGuLxw5NTdDbk
  template:
    metadata:
      creationTimestamp: null
      name: s3-creds
      namespace: postgres
