apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scaleodm-db-backup
  namespace: postgres
spec:
  schedule: "0 0 3 * * 3"  # At 03:00 UTC every Wednesday
  backupOwnerReference: self
  cluster:
    name: scaleodm-db
