---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: scaleodm-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgDDac7xFCEXPhM2oKcfaIHo7TAgkeLpJj4pt0b1K8a+3SDhKLZ2wMrIY/woQBsPrOgO+GZgvR/N4dhVymBW6cATC7z/20QT95gGU61UlDhZIMZFpmgGTyy/jp6x1+Uwdv7bA+HiUZ1ssFDBLZ2M5Ycdb8B1de3xoBj9Dt1FHox1zrIC87hqP5dhwPtorwjaVyjPskRQYxyYTm5Lbx3yoyYnnKyUv936QJfJrD0z28Z+JVDbzuDcXhZ0Gr0nzU8Z+8620W94hFA2GOSinAPlyW5500zlEC12nHXVPJ/Na6yuP921MeW4AMjKSQ5BcfNfRrmE5uR8hKE3kOyPIitq63pudyGB/p2cK8I2gT+mCDs5zTl9SAmEwEDNRd5rZCB8ZsE1he5qBUZbvHfN0MXJca3UnVSE0kf4Bp1wSACXqEIK963uw65BXh6vp5thLsArQtw5dQJjL8uVcV3YgKhHS6Wcys6rZF+QEsX2GgyAU7VwpXouK7q3Da6ob2028sV7Cd3+pi7HGS5RIsxpLU90sZTlTBAMIiKPGClSBLRUVRS4H+Hrro2fZ0lIGAkDPqD/CtS0THD2ShgGqsaFQmNcou+dS2mAcZ0P2zMZlbHVqhCJd389ADHioOYktLFIkOEpjJrA98pvkLw27zpBcqctRsgPPqEi5Rw5kuVVC3nkumQadNQ1pKRMKezhYYDZiD9NFQDYzqQP7JbXfYc47lm5/lyHOzNpKNg57vLQWpZsSOX2jqoINthMolVvKtzDwAYcOfCUpar8Rbk/VXFROvLCGJryIcBW5XGf
    username: AgBgI+waoHaeEZBETaZuBJwiieTVtwNHokAzi01XbSvnFp8Jl4ploF6MFFf+vc84WAEw1vrX1b9mutO4StcVOysE404peYHlgojyPIvyB+R4PQ2AC33fhaUgDaj02NutlGrjYV/8I7xCuBj0wjfHzsS3nifuAdKX9i1Jj5+8fMRHowk1wO1p8aLEb00t7p7V5VXc7EYXRKZvCuLBF/fmntQoXEMslJUTz/Kf57VKcag8KeTXNNttyiNwYJPUfaLcO23cNg1D8j8aVwwCrvojvAG2hQnJChNd3LCa6hjYZO2LS5z5o0u0pd+kNyyj5P7h48wRy8dc+q+CuFBSLvxWgtp+I/8r2Xq3zftzF8h62Wxd61cTPm28XbQxcuZNrMm+gmhLtyn6APGDzI+dlQtbtOu2097gYsmgF7aOVye+gPCsxImqZkmR/E0PwkHvTyVUmB/r5FM9OUTtJ/V1Alrv8Xuc7n6omuXc1U3CgwmfDQLkMCFjDZhW0En1k4s2bO1Mslm1+pywWmZTFhUGq5fLNtHcx55gQ8zQI4tw2X0nyPHqgF5ZDLIa0mfG9CRoCuuvoY557DfSgOGQi/bryYY/umsl8pQ1V7IJOFQ7zA8IwXYSwt2UBDVDn3rybqqRPFmO173B2E2hbyhol7Iv5GudM83VXjU60Yo6tZFo3d3XQbYvJJatrBkLVh4DuIt9aXDwcxT54nPVog2ulA==
  template:
    metadata:
      creationTimestamp: null
      name: scaleodm-db-creds
      namespace: postgres
