---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: scaleodm-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgBM3zUzl99qpwtmvzk7dWt3LPI9YA/KpnrGAahJBntCSM6n8Fn603VxENjnGfpjy4xRa0r8lRyWWyipo81O7bPEyOBd4GmZvrdV6Wo8I4foYxTQmXk8hFks/pKQP+Pld+evCsHbEmdtaUycdWKcdjNTfe6ApGdPHQ+5CtlPTnnLMgB6rb2fYcKGX5LlepG5jorJhV4/5i1tJeikwhGfiTUcSk40Nmvkfgn288prSCbJ7hiGxoR/2tNgnXyNrmzpzwoK7NZp0V8shacyjlbYeh/NmEFdoy+HL2t9I1F6mscsbkTA62f+8/fztsKVxQI6DRJtMprDWacwciJLxzTEjlypEXv1Hx+WkwVUxORx1yE8Xj4YSrcrkC9mhw1SgZNoF8e2v3iggV7GOazR1L5osJWYS1+brXFTPtTNQsY0758rOAbnl5FTZNMrlwwKiIxSwEJ+PF0mWM6xUKHJDzdqDIs6ZCTAKM4F0oZo8NrEIDkBTvx4Ar7mS73avCgi+2QymZc6EcV24S/xfsk1NWJKuyIM9iKDV0hy+Wf2BYQ7M97GaWSMymLB3qk/DRQBojSRz9pMOaAq866z65YkJPytkMJOtnNvkZghu8wMB1VwAxDyFtm3cMy+toXk8pma7p5TrWD9G2Ut/pPBh54GqfHX7BQMEtvmJYoiaAH7uumegrIg4CBgNhmY+keyJNst+OfvwQC2hP0o5zwuYEGRaHIxGpXHLyLXa8SS6hYTEGZrMGVOTNgGD9hkB/rL4qK2fipOz/bzeb6F0ooWXPn02uaSIDDl/ioADl3/
    username: AgACodDoa0JxwbsuZVqgI7hYQrTE/dVowcB9k6N+O+f4GVv/V+gtHbi3Mqiyiv2tTymJrU5zhzJolR0R4wIx+y//vKsbKkEpRuXAXTNPH9G4bx4bLG2kSdfyO4ZjPe0j5H4mwh7KpcBDcV2grDh+QDnKJzvK47og3rXPsTO0nKiiX5aQaYkvPzuLedN7V38ZiQWltwTcpr7TCdYHRH0L7a2nDEzrHRu1xtHeoVCuYn3hymI2jeRkR1Rh7CtmLYduBsGKxnQ9FZKx6FTLRJRfSOe2UIy3FKyI86buClVgO1jY9Lk5AP8gfy0jg8hvxwa0UHClvqwmSiTcUeK/iSwIB/Js0RJ/n3/jdEwAD3LxkSquRpMRl2hzW8QT5FXMomrLIoZQBWRHBGJ4U87SXXwJKNrlE1C6enu8NL0VPwz55O3+q62gOgQV1uSpeEcLJ7o4envsDfBhkhqlNX7poKobMu/o/K+g+o8Z0wN3kMEAtM0j2jDq62/0TDCC18qcoynFFOSi25nNx1Jhn2Azg7jSGHTvta/JVNuWERUTxARhIl9aYcC6OOzH+m8htKa3DztgrchGKdXCRV0PljKyA0/wmWl82+hJ+Y94EIck7HUOzSkTRNIJrw8xaKpy5ZmEBmF7iy6KybzJF9w5en16qMlRhVQfvqv1kZYI9gGyNcoPZtBUJxfUfLdyTr67MKExyKR1icncb4ww+xmJRg==
  template:
    metadata:
      creationTimestamp: null
      name: scaleodm-db-creds
      namespace: postgres
