---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tm-sandbox-db-prod-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgATgSuCojZ/cXTxExmfOXdEKgsG8yBAQvwR1UvphMYCFybkIWesV1Ty6Pko6FfHf/9vHw6morxMProZpi6OMIiHnhTdlG0USlXmyQp/LIExizlat8JpSuYPw4aZt92ZS3rPIFRu7M+CwP1zkQ7NkmiciX3UnULSnFTH1cPQH/vLxtkndXCYvxMNIKUTN8vhf+qiFZp29uDGpifoFJVKIODBZWypy9Ha41FZ++ZWgQuZbBpi2Rp1H58vUl3i9Smy9AXOnQXamoduO6SSfHkb7o9cODgassnhmfYqOi0+z4PdOt+30p7q1VPXhK8tx8saaoEpGgqBGRzfbOZ1SOIPOEoKOrky7JVmdgNqE0NJlw18hgsITsPmiMu+8Fo2mFeBT1k3Y9ppCHbYYf6j7JqrQwTSvvMSzyFHeUfEtgF+lRiJR+Z54pTOfv+qzPe3IWUVaLspkpzJt4TXBVDqIBW7oNSAlHtlZ2IULiZMDqrmo56EpKrVFXwyTZJ6h5FapxlBjosGbwsEJmRYK2t9wfupFocImgZ9tULNIXw4OSB2QFv851Q3x0XpFtO91dbVwhcrfdqKCh5HIeSbQU7M18SXJYOiXwMTd5nKtauqyWu0a5FdVabrSo5NIcdBjFGkzMhu+U309HU27gSvW5KAHRMus6/QLw+jGOxl3TH7naAsA2kU+SxQr+7etXIYWv7S2NJNcnA48KsnkXSID2o+2K9QMC+w9gnkqYNFGnQ=
    username: AgAky4H9/jMSwpuhrnNLUc923MbnsqeBLMAPnbOWafhJkoyIPLvJB9kqxrlj3sfOn8TjPsT5bogrcQGr67bhLs0aKbmKl9PDLDLVmFNyF1Roslo5JBQdKSvEw3tf312QSV/L5h7UP/GjQOeDe8AYq+xSfd4uLKbEQuUvKeMnkF2wQLGlAM+3VGzLi3QB8o4lmopNaHoMHl0CNgpVQ269hwTe8DQ44/OOm3IbdtAWzC/ZOmjaCfdYlgJNzD53tAtJoB81GlNpBbYpm5470k3Omu3Fd2U8WcBV5UuyX7O1WVLKDO2KqjIgxSOrb5uors+5OpkMpk9I3sDSYhVEcbUluqB12r2S9iji3FbiStgkgLmQKDxB2BZ8RMzoaJ5Yfp1DF6thaO/hXAIQG7XiB5l2ypcW5F58klNSWfdFH0GW921+AJSYG5htPgg+pOhPa+a+UecIgZj3lMCpOJB/Kc6LQxzYb4xl61UMCW+nl5Lc0ZGq47NjYKIHoRqYtGKV00xVOQodlxW7Oc3VTzzJXhmiq+GBpjPXF+i8hwL0OrxGoxMokA7+/+W6+nlg8ujYPRmSp5gnd/vMXFqB56L5sl4AqKn39YfuQMy1hwxwWsbmDoRnMPrrS/zn26Rjo887J9mX4gl1H3C74vqGni54bKOzCoFeZTDWXd3GCgygNWYHSlniDrYmBot+ynyLawjLja2gC3TpHKraH9ClTEm+5Pgv
  template:
    metadata:
      creationTimestamp: null
      name: tm-sandbox-db-prod-creds
      namespace: postgres
