---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tm-sandbox-db-prod-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgA2XeYrUun76xxbhqAdzXNutAIJo2i8pEdive+qcP1HchgfSzVmUQ1zokjUaQ+hznZSSbt/oadEl6YEVqNCIzm15id9zHBN8MwTrNFe1XoL7tQ8eS1PXW0q6AVl5IoqubkhcosI2wC+FPpk2v3LIsshAh9a+V+xTUS6MQKp3qOR+0frJOnOxhkP6m6G3TnN2SFnPsUlvYTPfcNxSchkWObiUuzkZ6ezv1yAvwVvwKdCUN+Gc9R6sFb/zOufWndt3eDFfZayPaf+5sdQBp6ingUt3VrcvnM861pOK5AmKrcwVIVeIwwTA1nqZseuiEMd69n5Q+oCj7bM1jhDKytP4ulxeRGe/ZBRbxRJj1BH2vopnRPGBJibRxuynH4J3lkS10KKGMW4mj+EzjTrAjK8mR5ROOBSd8hsEknVQo6MUaXmDIt2xEGlgnuToj41cxRfewC5wLZYIVW7b2+qZXgqIquGuqxymjU00aM3iwpsoqp1rLZFFXnEKSIfDFizqh2liC9OSijzdSqLC1uRZJHq4OHDQQdMP+0rPZ8tKkf5D85o8RNq7W8mIdPwwm5M7BbWNyWKMB7i5IIjwOmaBODi9Yhvk5wkZgPm9ic5Qe+am+OGJj7tThEOE/XOnKaMy/2PyZBRok79ERgiZYjwlnEdUVgZReTaCK534kTbK/CfkTdURxkiTtYSMF+ZfWk4eeyNZj2ClVLGK5CTA5LgOFxzE1BOPyI+J4C/yrYmsyADvnYlbQ==
    username: AgCt8tNbnfIxbw8bDBkAw0Oq7G3fjXc7zho9P8jqvsBo3YO4G047rTjJWtQZM0yRrCm+wNSHolPDdvpwknxr/dEb6yIAOpNXqwgs2RGxJarKpq2yRKcSuyj7PpPOYZR87v5QKw4nufMOGiVNErjVgfNUvqiR4YlBnnZPQTeNn85f2GS3RpdB2VsLbsRqihchS30/3gWcCF8N0jBpi+ZwjseU7LHg1+5RWUUgcjVgNS1uVICwvI5R2kbLw2IOv74osg+h4tZROUTLCupAROKPC7Ovef7+wIzjZXfjJCL8GuwSl0m+qYA+Qr57CSZdXldToq510XnqIl462u/oyT0OfWRMjWRfiw29psxj1InvW/GWwNmK0Ue9DKZ3V5Ks2Ihy05TP4YGDEgcU7VwBPv0ipmxQGliGBe2mAub9RzwKjniDs8FZMxg0iPu9T2x90eKbHumnZPMYUZFToonHUmm+RwKzchayHZ5uk/5HMHM5fZLLfU1iez0oCVKvNUUmlU968Sr+U6+gnCIFK5+PZgwBTuWuJogR6iuqrVUjN+DVFAVRvIpiyf7zIRumetpiBMztbbur9huiPhhNxPWriwVQd8+boUDotLKE29GLYUzkvmsEYxallGB+Hjfn/SlXY8gQ+Tj4VT3LAbG/ymbm/oWJqxTVptzWlagxJdD3O52CuRDLutw2iyd4S3Ge6cscUnZ2gVp71oXHxVWOOpvWl1Qn
  template:
    metadata:
      creationTimestamp: null
      name: tm-sandbox-db-prod-creds
      namespace: postgres
