---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: windmill-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgCZcuwjvurBQEc3ucSLMmKPypQgRzUh67j4nHInauf3qY/Npqx9wjPMIgjbvonsoZoUKbmtaZQk/WrjsIQcOp2ajKiMOsufaThDzcjifyq+hwHGXpUWcYN+lc7mf3SXbIMV0/79OjYd/WtOkf7bBDVdMkE0lFScgcgSvaARuqrZnbjO7xdhIGBN9W+/+XnPWJRVssfE6FRgtH1QtHJLusmT9A2cvzzl9wqF6d1Mp7OXeASCNwXiGEaYJRIc/wrYyUsJL+occFVZVS5xM012wXtQl8RQgC2cUmJ544BjC+1lIVYDmSuEjxnKMHh/tDBGVnA4rR51JLo5SaexNRtM0W3UmGpsSkOL1qEGFL6j7hyfhGFOOP/zaPN7mrgiao74HvXRoKe9Do1LToTPS34oTdB4sRRzqssDKjduIjAUaUqWoBjcvNBLUw8PPoPq+TWWG1xGFPn0qLEBanoClVczgor64v/jxwRa3XPzuTf+ttbDLu8dPtu34JuYiJnOSSgKOP3BmHI11jJVFhYxt6REAN31JJVYON1MqWt8GE16fKqJN9oxmrYo7UA/YdSGv60iyfuRKFFUvVle+5ASnOTxQqU4axVr/pCD/EnP1JtibG/+EQNf0E8JjUKUC+PFBuTop4/s9lBIwUwQJObO/WEDoPPp6Ir7kbtDUQMppOrjTdwDTNAkvygrUDZBgl1Me80DusnfN3TeB+PRBNzDsw2gi52hjpZyWfaVv25JLyFPDwzyV62ew4v8kEh0wi19L+gAsSmI3rXponJGvS18i1b0OzzrDu19yJPM
    username: AgCEaNGRKg0fQWLl1olY+aizMgsah29x8gdVeJksM7ILDNGjr4UiEHArdfMJhDvNE3Mjd4dbZhUbjjASWTeB4vFyC4hr7kKEXF6T6ajWbd4m0GvT4KXq2ztUUNJ8xE+2WCEd18L8/MHglW3aCz24OsSskI07ov9qI9xPzJiVpKndnEUWxKCLU3S110DnXhhn6nGHtHjY1aU5KOBdfq9zsNOG4TOBcd8pxkHImiHlLNCM4vzLKogPub6Y4HWcZbNxZ4YQs3ALmWHiwA5rkCUlYCqPxs2idrsfVCdRCFfhTK5b2uahV0dZNZ3WOAiYsUXgXFitqlkrUPCqfhvxbXUGQJhrFCP42eoo9MpG4Ylt+LC2WNq0m+THI0n2oXyrL1nIGOLa6+4YCCNj8duKpbKLPPx+aJZjnrajxc4iF5T7gKjS56b2Bcy3vNEDr0bdS01Qalu3oOgaMZBOOu81PY4bEu32YJDjwTdWhw3oXDWwRkXGmxBMtwOXwiXLDq47ZyPNFX0gbDtshCRTfLp7J8l0b3EZBi5efOaoQJFk/djGz0ZBZRqAhTzcuDUbZ87fMeENIIKN5N0ewCDnqWmXHJXfW1ymJ5GxnUlNDK30v2Ugb6PZZNP2imIQPlHyKN+aJV0UgbACjvKlZQY7SOV4JA8JxbkM8II/hL/sjxeHCnBsy6aRcJb5ABFlUShI5qlS/Bw9uQofqyrrE2kTJg==
  template:
    metadata:
      creationTimestamp: null
      name: windmill-db-creds
      namespace: postgres
