apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: windmill-db-backup
  namespace: postgres
spec:
  schedule: "0 0 3 * * 5"  # At 03:00 UTC every Friday
  backupOwnerReference: self
  cluster:
    name: windmill-db
