---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: windmill-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAwD7x/EVXw/9Xab535Ns9+3Ok1RPdueVVRc28dlou0saNV1LyuDG8JavzDeLuFFS3J2UZaRO8I5DFPQld0qwG0VkpRmxYmkXpWJSnFyj2XlUrTgrda9HdfcUZMr/+wL8pWDeSy8QSrKBwOREW6dxpuKVLnXm9yXy8s0asjRl80yCo28Vu0mb0tlC9is++E789XZ2F8mVN3rKOmyTpioxAuTXxgEOTA4Szt+VUTA7j355tKy4X3Qc0+Z37LKxorqZYiBCGg5lgvdMrgTe1oWECeMOkLFAD8MYF6tijRF273Y+gILmH3P195KPQ2MIV+6nx/Ac5VZnP6EWPMEce2inMo8a/zIjYRZmv8Gu9kkBEWxr+BCSsAWHxnmH5syeAC4RDD2t7z4NWZeFn+l9T4IDw5q4kBJbf0iBqvK9zJcj8mIvhx77FnGbosSg/yrE57oHsDStfy8gNJIY/yLGSh1xeDsBgbwXfJTYnvqdDeNH6znB+pJGpFBZSQxB3qhTvVAsgCctagX48U13aJSYTHCKIubKGp+GokMXe7SFLUXFg9VtjGsGu2Bnds626TO8vzOmmbqEJkRQzlfxNa4kzWS4DM+DxbNWvEKkkI9+bCiiJs/xEodc3+jLDeqFjdm/Zw52BERcRTdlCZpwQvEUGSQwk4JWfbl76cPAD/Jn7HFb4+xGzm4QEbxd8nvMEXs2hGrmczPOwCvM5H9yfJlG0rDwoYiGgs3K5iqByh1a9I6qD4CY+pSe/A2OT21cJWKi3N6ZaVUOG7W/cNZ6cdywf4zrMXzjX/gYdb
    username: AgCj1cC6JgL9RCHJ+wzB/xs1GkkVY6CYp3uIGzVROm1mEU/thAnfsRagY89K271ptEzphsjnB/DBWE1OEMdzb3xgmYJGgDP6iFR/AKTkCoTVWACHYqpgc9g0or+frJB9W08gAfJ661orQGPTM9ec9AkCokV5TThKdWyTihH2fN7in5+W9MF4v9UIe5ev3ii7hXxKOtIWAyfrhT2kcO9iBFuA2JRayMYjKFWvN+7Xqh7diGhCKJkwkhkaw7M3zGEnR0XdYI1kQA2oLctuDY8vds1j9yFnhrM6T0yip/Qp9Jt8dxwc4UJUBr5YwV8/dLi9jY/8Ok7og0eis5jwgmHF4WtflGoVjQH1bNwja54BF13zifn1zDsanS8MAxHJKQY+8XSHtmOfVXCndAdpqUxg8DIZdnpLSmNK5eONaHzuiGF2ZIzYJStia8P9gvvls3fNai0TjuMbIjYqaeJioVMGK0fEr1szT8YnsMDHGZhVsnjw6gprh3K1lwYg2CNVJJP0qUfm+hvpluK4g9/RPaPqBHH4ylkA1l4vWmMVm365FMvopBZu89yhpVhEt6iuskQeitathIstoIKUH7Swde6kpoezeedbZJ99TIh91kubHOOGSY80tyAd81Hca1uJr1x12L4if1qn2YZhqAs8z7+r1s9sXl0NQvoTI52EqLt3lcKPhyFSxJ21+Wd9qq5/pcOxdqTdIIa6UZhXRg==
  template:
    metadata:
      creationTimestamp: null
      name: windmill-db-creds
      namespace: postgres
