---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zenml-db-production-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgBlp7velOwzZB+ppMfonRS/BKCEu4WOwb2ZqdxaToECAy1nnnfnu/WGYJcpAUsCxW1cpg90QZMqB/oyzvawakyBmDuk8uj8N25QlCCawY2KgfgtxXCEQ2e7UCOFayYxYxuU0/OU5oiV7WiK3gNTp6Ms/DzlSHilEzQAI8oanlYsKcXtKtImYBASlqKyJYeK5ctsMhTFm3wE9oaK4MEAkkG7ZQevyquzDy6T+MJf5U2mErnsuy+0RMbaKOjQei1GGOBKNXO+IINSWmHO4TB8AAV2ezQI09PNBaIt0MonWpJ/xDAhzWurcbi5oHwXCnBVEzjuNVCAfnTsypDH1mDOcOphGY/Lij5AVGs+DxuQCkLO8D/CQaPj+Hpv+xqy89CUHzabAtdzbYgqQ0u352Sj3UhFdOHRnOlsRCuPMWrMzsApwJHQkS6wguo+DJhas4WD4gx/cvVNHH1WvIrNV/AQoyLMJ0GUmS2SXUiDlDfvj1JysETthP+aacpWFmbk5cbkInvGlCxpTtRuTcyzFhXjuSfgCZtszqHJQI9KO7DInJ2kTuo0vWii9x9AZMgYSH4wm8zZmjjZ8G/7Ndci3Qizo+sfR8Lyd1/4TDfNj4yKS95EoGdCfRmfGsnTbbIgZWM4nc86AxMy4Mo3ij4uMy60iCpXUfmyqhbA4H1eaWgX+C/P/VfsHAtnTDYCximmfUpBkBvBqObfC8+IRvT63s7nqRmih8MYgpJU3rX13wljXRSrpA==
    username: AgCeMD0jOUig/joDbKgmq1Fz4J00SZfgd5Q9YdvqsusHpWPWNYS0eRRI+N7VagyXfLSv0VBhHoo5MmcWfNrSWBukfUtCjy5ruPpk2ilwqb9bHpr/go4duoINTHE5PShdypDPjACRCFBwt+De+q2CznXz+VXtKQ+3adedJ1S8UPHdGyVyMrzJXBiIeTSw9gM8qgfrW7kaykCf0PV1cQN/Rj19Dr1xkpDa8dlMx/pgXhQPtURlSHpjwa9DcUYnUAVYB2CxpyAy8tGBbfGanxg5a+ycz8t7ltUsf/Yij010NYwuya46VR85QRDn8VjsgFEMhKUWOTbL6m4zQD8pX0TERziaUJEIM7SxO3qQBLKk+hRZmJMLlBUZafTYgxZlM7/VAb2GELlkrtkbIp0a48xEMv+L5bgTrm8HlzgRy5Ezxjp2qFmXNXSYt+DUmAMSyu02nhy4Vway3AUsSfuZWe3FEqD4dKAqpZpOaxyXtj/Ek1YsIT2K+yqsAJDch9pqIgjOuqt2rqnQuz8sHJfOm8BfU3dutXF8a1Wc6ShXlQTfp8uvGdAwaSQ6lA+3jSbTjQaxCUQmUAXc8XkSYOZ1Mz7wp7qPy6ak8CZ1+cZm4X3CSAJwqF3bExVfR1Dn/3YB93OGynd6lf8zzwpSFxkTSxX/Zz2Lr7rBHwrJlfM306fn5g4O1/1NRqhqhj8HS8vuUM803z4WcWUnGA==
  template:
    metadata:
      creationTimestamp: null
      name: zenml-db-production-creds
      namespace: postgres
