---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zenml-db-staging-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAc+fnCSbHtAlPWi1j37TIuEOrxs8V3FfJ5cuaywKeaJYEY7fyrcUN8prgaTjxLT/Ea0QYpcGXDeujve0Aksxzza4LQmAB5WXN7RoYQzlhJ1Bf0CGmEpPtkg9HT+gnmwOGfvuSvvUEfrORZEZoHSdRS+XG1m6iduTdOEh2QFs2Fwr4zXtd7r3bo2ydySaDfL4gI1Ts5TUK25Z7g5EVZ6B86kXR43t9x7SgJkuS/Dz3pdnvuqpbIRJieMJudAfd9xUhUl5Kwp2WDXfBybLM9DeM6Z0+ICZHmSlP5OJvO8F/g2VA8OJmHjQj7q6luLjFmIl7zPOKFd6zJj0nFmQVFFwm1toKEUOQYr5fZ1qgW2T8R57D5FRzNC1+UvhUr+yNo4/m9nHjN0E4bYoVmPDfrE8u8Qv+84SwTddyBuCivrqUWQocAOwuW1Q/kxy34ohdgT69slIcTdRugTTv0Zd9ZV7MLsev78LIqL5pnJo4osbE3JOFNSagrp5uKzk3VS/0ap0PkL1nGUSWWry2V6VLilEN1X1uXdj46YrCNMUpWjq0Ie7Ar6KJ3tWq+vaYojbB8BMngBBh3Iv3IGOh+HwxaJhNVHlikuR8EBc683hF0QdK4WD3bMRIUKQEQQpcpj1JxpuQCT0AITOhktt4M1SkzSPEDtiWCjTSd2Fzswd5BF8qhkF9LnJ2aSxJHWDUL6sGkv2U/VoEu/uX+tlpAAt/TA7LZZQr4Px+u84JkNMeaAqzyngUn96Qb/i/Z2Zre9W+Yne4G8Meajn/ChAgwHhmSau4hApmTUS/F
    username: AgCdVMTkHLA5lmeko+4uoVi1gPIUs1A3sDJFfosBqhYbBMFndJqjRJe6S+fYH8pr1HMXM4s80oxW2wS3wXTM0tJ79SSh2alQ/H3wkF9PdyPtCmnmN3BXoSBnptDQ0Qd3jrqg6tbKx1RQq3BGGt4CwLmV+y6Wzk4/VaGW8pXV2ARQNM7M9hHJK01GbXRIVPqr9GfTRRiL8A4ZN4St4o6ogSh7SH9Ig45XaBT8tY65L7cpmqkw/bc0Hv+kD9Fz9S0HZOhrpnI/EOPClrTkfCwiVX3MiVIONtVCyB5/05rjH3ew9aGe/GrBSJ39CpNwksi0U+tDPl2efRSuzSVD3dDTRUq+KcPhtQeCuDo7nvyDmsPChkMLbqTHA6qjj2qIZ73X/LfWEu+pHe//ACyW+LDgOn/Yv7lKzapL7tpPguAw7fOk7pVcUSI7HxjUuVUzIUc+lY9wFsMnEOpQm+HPB0vCmerDL8Nj5T1+btrjhML+SjPLjra2vz1Wg6FgSwDR5PfVBAq4n7Q6+Y8sLwRNjL8Sg4VI34kLi9X7GNu7GXeikUEUDKnAYbA2AGiyhRdlcerEHRgBAWTMU56piDQPqg4VmrCeVIe0OHZahF9lUWmxXkM56SIoHUXy6KhlcWCj0Fla3l1bsYMsUATYA4yc7M1QAehmlpn2E2zgTxO6FWOKAk6622fs6UTM+vui6luq/Iq1CYS4086/lw==
  template:
    metadata:
      name: zenml-db-staging-creds
      namespace: postgres
