apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: zenml-db-prod-backup
  namespace: postgres
spec:
  schedule: "0 0 3 * * 6"  # At 03:00 UTC every Saturday
  backupOwnerReference: self
  cluster:
    name: zenml-db-prod
