---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zenml-db-production-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgC6bW4X1PwUGxAqRmEvf+3y0ogM7oCSPBK7RDAKos6gSc51U1yt79I+u1DsP+TH9D+NiQmrXb2S7DnNsjVSbLidniCa9zqoQIIoINoPIb47IX0qJV2lsW6jOb5MyYzRF61xt/KhyaDPrkl+WWv6Vyc5efuxjH/9K8i5WYrdigdeUn/PXahqIQmMsTf06wjnIpiynRu1Lf5dOx092wWpfCo3Sp1SKsJEVsEn6DGPdULHvHwV2zgcquCj9tMW/69pMEWcl84pCzwQvQEoJAFkUMmOg0e/QY+/YvRDCZlAeNOFFFXoX7j+bpOsgurFqiyQkbtSX/OUQRpFYhIUmiocURHhwZNpJ8SvjwG4ewcariiQBsLZqlTISFsZa0qF9qbEdro0gNzwdU0kIfdkRdHjvCW1DRSRicSpgiGMCwSX8UlfwUbdHh7iGAAtEC0XqnYIdD0dGld2HBNrwpy9JOl1th0+X4Ns/d97MrceDqnVBwEZHFLJP4G6yOcbMsL1cJ2B3Nv46nwVHp2VlZq92tY7yYIF7DGu/9LFgIzWLfAQHvlwAjS+O7QV2l09nS6ulWkoPK11oZBI5EOjgStui2OsFTRm7om6qulAhN5mjj7UALMV3HEC7cQgxRIsDjzmh3G7Z8Km8M1t1AbLIEnjsCivqF0GekoJCKV44sWxPlYEzjhSaKniMWK6fDUk43ea6BYAzBHO8mG7wbqZFN8dusgfiMH4LGerGEa37V0StgVX84BwAQ==
    username: AgA8O+8OE6vugEl8pQ+bCBCoSM6Lx3iFarvRgpLOOcIT8Cpl8/S8IxKYmVxyY+zTO4OoNEvwZtBtP41bPINmOsAKihbCkpLLBsJjBcbuAn5nGBWVzA4UzSrlFL5tvg+b4v85NqPxCGEopnncxC1LWnA6ARb+CYEsvLh6jDx3NmztqFsRY8cvz680CEluPCJ7XkXqww4Dida2dWkgUXLdQjUhkMhKPyos3H/UWFzUb+OFsOMoFqGnK27zj7Rh2OUcsLIPr73LRD4/XUzXfBQkRvNq/G8Ewmo6GQVgso7DpVSPluRboajc7SctJPnRb8x7oJx5HV/xZ9B1nNalMl/bBJGpPXizSCQjjRvAGPRuZVMSOEN8ordvsAstHl9bxWg7vmF5nEM5WOejS9rYZAVmszz0GWuTVboP0S4xRUL4runBifMIXs6rOSdLo9woq7rBoK+IbOhhNJn0wJCqL/vv3HmqKjfgp1o3xWemDI4VqzmQ3r8HGmqvpaYqe4onIGg0CxDujIKFA0XIOBpGqUXtbQJs+xmsyfHtnL+Pxx5gL3LNKqk1toOjrO3sro3GlPru+0v5pGWbKq20zjyEOgQtse65+Dj8yad9Dtw69I+RviQwzU1l2ApCaIFxIsZVrksoJ3+s2aT5c7W0CPGZmgG/tHxiaPAHh/AUqtwKsPeCBZwhz1f4aFFcCsRG/77LaV+ne3gGRFgffA==
  template:
    metadata:
      name: zenml-db-production-creds
      namespace: postgres
