---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zenml-db-prod-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAdT3+1i9b7+aOTeBoPfSn33/6mTcXPQmR14AKDjwcv3Qb/IukfBzSRDI/KMk3LfRpv6RD6Op07f9uLjUOPuPtuhQlL68ubBuWHAJLDKwbfvSDyxSMDK6eTgzNUigxwfnxqvLowOqH0eF/zSk1s8zYZE8O8bLwAxSDBswRmrxu0R4JmudObmYGkJNWMnhHr3vsajddfZQ2hDVJd9NVGjAoEZ62cK+Cl8QOHVe/EgI7DHq7wAJYR8sHDsOkS/QHhXfvG++egfr0dXFHG1P+KHa+B1SjjvPolC/H2LBR7g7+DQgjqnOvgecpqdpMzHrc8Pf8Dls4nOSMcuM1J+dftNtTTF9rMKVfJoNJgIqEl07S1ckCEXlZBQAqccc/BO2Czi9Frc0BsLpQKANtdeSjvI0puY1DDsB9qavkWBpF7w8Q4N9iifF+Oc/MbljrE+cHunYGn7ViHXNA9ttIJ9EAQoxFRbahL+pdm4puk9plukYTMYuC+r67Sn8ly3iGc60O7iWNcy6Q2eaqcYw3G+G6mvOH9t41pu+xMyvJlNKNwRcFG/+ftKzclbgEFS2MUxaNMYsAvLocQBn5/2DPi1d3ID/no/4mw/7yEZTf6lFetMCF3ASPr7AlCNLTgEVP7vl7S4EbxFv9LE+bOwdySbjGGI6FGjIw8BdIQ5ELUoDO9TGpdPNrUui3Opbge+7NvjenQz0Dwur00GPaABYnnSiVmOxIdlYYuWeIT647JwOBmcNReph8++StGU8u35pVrBB2pwsE7MlsHHY0gt3fdlzcS9XIgQiPaZKr5
    username: AgBnHn7xm+riFRgO2jHot3mbG4pMxBoXU5IJE6Adb4Z/xopVW/EhkZimWo9YzmpJ7h58vpu7N0VTv+6iKCPDR/Af4UqDa2fpsQHvg2hHlQlhyXblBdSsPf4zn+86SPJgCZV39qQPsHLDk1+fm1EC0gQiPIEixFuECVjmGCZbz/Oefp5By/7uu8jeGfAmuGgoRrmMnx5PoRyzElveXhTxpVc78a0QN1lQ+yJj3vEMXLR9uVBIoS2zCCb2KMAsTIXB26TYEA4rMmyP6fPaf0tdvr1r2P1AsXHlrLDjOJbKQboTBs/3E7nt+UpwBOGBm194HnPYt8ekoK9JxIx4FPnJbNm1v0F0lfZdUT8QhvpsxoTZDvlaFC1zqAj+wO9iAgfPPRi7LeLy+m6pk6vYUUtY3P43R86CJ0UMBau9wIEYKTOab7C1pn031iOcBrPXlF6X7VY7i3vn12IfTEnpJIZjeQlPZhhwmXF+3A2Tk8L/Cp4d0JPgcnlKoXJPBbVts9ZPZgg59XIGeN3gQpwEBKUmGWNGF75fALS2Rl97MpEhJXb49ZfP/qjWadx+6j/ohBJsCwZ3A8WC2BZK0YPJoFX2E47/bKMsGbDmGM+Falbsv5aSfZaQrVc3kWVlBNDBtzRZ7BBvX9jU+xl34ATnSkbTrfpnnH1Ro2C9SdD/OabiRUNK725pRFtVvXATn53F1qG2Uz21dI5qFQ==
  template:
    metadata:
      creationTimestamp: null
      name: zenml-db-prod-creds
      namespace: postgres
