---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-aws-creds
  namespace: kube-system
spec:
  encryptedData:
    credentials: AgBPDudvExeMGbAaFxLM9SbBl7if2ogATjSoCtl8tYlY1MjzWeMOcldF/CU7R1zM0p2d6/fTungBV83gXi/lBws1mPzRSipMNBPfAXj5iQ5SYo7NN8++mRcEGJDnq2Cjr81RJDEsJfdZVWb0iGqKeggLGHna63N4UvVtcLwpjryNZGVcZXOlrPE48VhXz0xh0OlJRyWQHlpjhwHoCiiIbni5ldZ5L+alHTP4nnk4yhRDAUPQzBHUJxL6bYyaaLYm53MBqyPXs95LenA45Ig1Jy38YMNQT+nffeUeBQT1PoDMo+Mh18qk40lSPQTJngvsfehinJHW1+XfQzI6TjXm+uILZr9Z+EkCuRa3S2s4WDVjW8RUu9b+Vok5cuzLGsaXcEg9LSQANelo8qQva05teyKppzEJl35oPWUmw7/aqoGbRUUXdFkZtxyCUxL4+OpokIT6H2RzCwX+weMG2GsTL/tz61XqoSTGUVNY+IjvTIwIPP0jh/Jx9VZIGurTF3TOzM0M0Md6Tr5vLgx6N9oQoK0rfap3BNBmc3Vxj+jufb8jX2eZVFAW91tVoFoRmImckAy5vVPvQvitPOBYcS69OHPfuo+4HtwXKg27qHjt0onKJIbgjM3q93qVs7KlvFcYVNHlS1Q65KwbHp1UeaHJvcJifAUPmtDOQACHT2OaiKm3lLSkJxlosG+P9bfzbevlfpnc5mTo9Uk6TIQsMPoSQp2QFQY+WRFoptUJEw6SXz4x9O3w7mtkuzjClD/I1UW1WaHqQgw0aUrUsUqQkn3oj5sysPZh5/gx2l+ZS+atOuLNIUt3BYoY4bdrBg1ftJHpUfoxQdHE+WXFcwmxWsPL0/uuGheuug==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-aws-creds
      namespace: kube-system
