---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-logs-s3-creds
  namespace: oam
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCjRk/46j/FIBTlZ6m3tDZi+Aq6g0iFHLmRtI2xVJP4BDnuvTFUCe+4LX3kVJ04nUkXd/bts4z00aomJJoPotX2k7vj9eRCmhyJz+cfLnYms9ZubTNPv+odUqWoL0J2cdWKQUVF8H27pwhCREhsQgViIsrPcFw9ohhQVXlvQ4nW5Km5sU30+VkWJE7pPYCdcKaBnPFjdveHMmRkFOIJOtZ2jQkfWXWsX2o9+CdnU3wazlKwRFReFjBkpB/fEp+9BosZ8jNNIQEygf/fBKqMV7/UoCXDHl9QEMou+DSh2dF+6woSZmP/pXoR/1mc7fcuyl7yAsiE+DrQ3untFyaMIxPh5BYhqY1omk4GwAusnJX7XoF6QvF6X07J3sjSf6Yhb/U5QxVPJ379rhuaM5oRJllDekiYqBh75jDkuYsKphTwO5OjBOR7Bd0C14pm6C8rSZmt/ZOOIU66aQXKK7ukY7xio2Ndtj7ThZupx7mTxpZlnQo1hYvMm/BBbP7cACfiPjiy4V5mACKEysBAMI4I0K+Wspa0y1QzZz/8IEFbI2yl92XKY21jvPTJ2j70VmW9XGFoDbDZPG3WPxY08JtMVoDTKq/wO3GliB+PEgY8oEDxlBp7rl4SBfgDTKj2siLlhQ93KCUCfAY1YJ/ZC+L1tVb9WvQQcTHgAnpEZuqOghX4Dlwg3+dKDG1nPXAFo1llU32bDgFobvQdI9KNzeTfXE0yuI36vA==
    AWS_SECRET_ACCESS_KEY: AgAqlPPV1r+GW/LVz+ViVUImTe7iakNxMDj7QzDWF2Yq1e111Sx8apjqCP/qaGXtQlenUG0ClMia5WAkkrODnm3xmbafOx1dcx+Ydxl9GQvrD6Yxts/awarHt7payic8Ebb1MjTYSg/900BlPmD3jiZQWwKR9icnlsIAaxpZZEMN2yoI/H7VRApKyJ3z3ArZhy0dcLbDXbHLv1wrTxTRalo5sFqITsmEoRnfofz26wHDtK8TWjPXPrsLU3JtjLJ1fsgXHR0X6opEl1MMMTX7RFcyLMKZ3X3MrrTzgCAG0zuDzYlljzyODC4DefHg1HbF+jc0+Ph9jVVMSxhIk4nUyEcxhrxyj2HypX+hVO36utCDLzifMF6mR7N8IhJrO5u4ZYUuDShvMAzZZeaphTBmnQsq7/9+waTB8NaQ1kIErlobFwHX0Cf2TVT1ocSgE9UBsTJ9ZXXp5ITIDmSH74j54IYCsnGtXRRUbeyIhWe5Wjma5zLhCvOyejwbT8nwSkussnoaX6LM/frH6ql9BAbDVegLozHTV4SuZcOFWRpPGn4ET/lLUoOLMnaS7Kc81w/7fZjHChantVBnNc0MEVmk7oDr0f4dgqIEgShuWwtK0NKwtP6cXa7fh7l6CPusNDuEQ1t2OR5puv0w9FpB0cwAFDXiIYH1I4aU2uBlEMnp/sHHH6oQg/YvQXEGZB0HmvdkzmznAKXrjDwbBBWtydVwE3yitSL5WyEusHZrp4IAkgSgRJPIXqCLRMGK
  template:
    metadata:
      creationTimestamp: null
      name: argo-logs-s3-creds
      namespace: oam
