---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-logs-s3-creds
  namespace: oam
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCWxK3XPWCmLEkgiRMUxdlC5MLYPVhmxEfQbkDKn/YEfQ2wH9vR7tDmBVgtz7BxiPQyOZf27rtGoD06ZZIlQF1Cro7bPWkCs3lE2akBJ2YYbNzJKcc8UGgLZh2IexvwCTgMNdtkIGgWg2SZXgohTLS1yD1bilAp0Pr6+T/UTizfepjGDy7qiJPTT38M/XoropwpySHJ5YY7lHFhwM06oCufUBGuBypeQqRT0aYtTIKEU38bQlGr1QD9csyKpzOSr8mk2uJihqBtWodbpQaDfzsGHO+g2nJHBqgjzHfX63R19y1d/mdqkq4zBVVlCHIhqFz72Z72TKnVTMvjQ4jqEsQXes8PpIDvEnG6a6+kUgsaFyQoiNpbNf6lB3lrzbm8EGkrJ1ExzTDqx2s2KSgII+JjGBXKESDRB7Bg+48tHBTUax3LDjjaftiXs2/rUX0N0O0BsQgNr670b1172/h3Nq3gKaPfP+5vGUMGD5w+OAKi6lYI+VUcOuDrM0lgv7zKgGQjJRFTkCmIIce/v9oEYwvVYD+M3+DByvlGu+hIGG4QWhe3IKFZiU/8RwXi/NSbPXZZGOOW8RI985hw+G99LnyZmOK15rsxFlwuBA5t6X16oj+paxiJNIYdjXFjz/tPZmeSS6TvYD8GkbwulMY3/WePYgSj7mjbtg6LJ8KRATfedNcNbq/evG+AVdVmfh44rOg4RK5honaZHeuILy4FUO3/kw9mHw==
    AWS_SECRET_ACCESS_KEY: AgCRXRDNTmyXZNGx7OTTD3zLT7AkMJBSHoDdL/XagOAdmo95V9geJ7QPgW168fELalbYOovA7EPsrBb9nsex0xAxhXh47w33ZEpFoKSlumU0xihkUv7gL8uAaEiRFRchSsP619Vi4vwzQSi9AzMZFHn1kaQ27NgCfPVFSjxlMl6LFKgKg8ZPbCakph2XgyjZiw35SeFMYhqs7e2sj9rYMFPyhD7v2OPxaQv1PjWBWwLOzd7+7IHlF7g5weDLELaEE5fhL4WbjpyyOzlBSbObjrL8iEXJL/Nq189Hahu2G7kh2T1oBvdniaxCKh5ZoARZeeVJAYSNSs41LvY8hpx4luoqWyEt87M9TplQokBxFnVftfZFlsQ6MsItD7okaNXMvFWKC1Bc2FC3mJGmwAN7ua3eqLTX4HVgOFuywrwFHLEApkSzEHbuArD/lemz4/Xm86/X/9eSmY7t8ObK8E12UCnZewH1/lN8kMx+yvj3Kn6itH9WewILUVgjH6ddRjXA/I1G/easShJge0kUsw8JM3lygkwEd5sIWShZ38rEOX7RcAhryo+p8FuLe69mDf1cPIJNwwgCGcojwHh9EZYmrsP/a2ebMMkznDQWzIb5EHofKWPAH8EoB2yFQ2fC34rhhe5KNPiNaE9FlRbTneTZEoZbV+uUJojUr7d1sLKwUCfTZn2BR6l/Ulfcz/XPJMy4CulpNz8SN7q895dciBuG0p9GQLe0GkYpWJzwrdAUDNZoyNjTuHEh3hYy
  template:
    metadata:
      creationTimestamp: null
      name: argo-logs-s3-creds
      namespace: oam
