---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oam-s3-creds
  namespace: oam
spec:
  encryptedData:
    S3_ACCESS_KEY: AgBXKedXiOxEb9qK8GW+H+vMu3QyT+5OGEuexMFKWjqAXGdjd6dIcNNfVkztH5GHSMTvHbal49ONLlvxg7ifBUoRG7n0FQNQedNIXPUxFFNrb3ErsT0LXBSDIbXpzrO+Z9ypKEH8q/yGskhujdMNJWXa7u6BCQp/BrV52UIJOTtK0Pa3GzQN4Clh1zCvGMVEGff+xHI6wNTiGJ6MBTEdoGnu/agtif+87aWuHPHBcT8LiAercPwvttjVXXP+wB0n7e825bqM3zH1sWCo/eaOU+MauKaEVTFYDK33dM5tqZ0hX/M8aZiUkmp3u5q4dFeBxhbAv6A2xAfMazclsGNqRAc2pryyjt2rSW1jjRdvexk/8E50cAZ9xG1alVUCTwT81IDnIzbsWH5A0Z4h2b2EeE9IJBjkhOmD5lYHW8Ro+BWIEdbX1dGQZJpkkxgCUXatHFT8sDeIzYfN2bEeZ4VV0F++lFjguFqe9PN5fmaiQHQkFSNrnfLL+Q43ltodFQCH4eat7lr4zeuukL+zl1Xj8Lc/qVKlJUl+uCRb5pv9xe/t6nrOTRvMEacvPq6aAkyaXdwCCM6VhvWTHFWnFUyC1V6m8ernD2nLm6nRao8B7br9PQoGV+dZ5TECHtn4mj1X6GaajmSA9wjm9ykjVW2u9HsShcvMQrLXrIXpnQ+aFSZGW3dJh52tUOtCM/u9cISjp7NDDONqYj/AG3ihUg+bC2Ci3jFURg==
    S3_SECRET_KEY: AgB55FKNzqBFhlECXJc1pWxrBPRTRYxCMU91KMHcq/8RhIrTikKLH7mu3CZVLuAWMloTgBikF2K2zmJ0d95HYLn/2cnRw4Zk3NClehjr1IU1GK2ygMLBCIqM/OQaFYTxNkqddhuuP6mg4T5/eKRw7vHaWm7+AlpLNkRfxetZY6cTtkkjEIyfDyHDGtA4MxxgmxDnCX2Bp5i7HZuEqWoyW3bx25r4+G0Qs1s9jl01Guy4FAfzdwb83mr7OvElWdv/lX3ZpyQW+e65Lvw2zEIOtYzi4cLVHMp0A3NklmHB3WWRRfKYhGVtw/kmoLR3i9KnpcQ4htcECie24jy0qmawyqctWK07a/IFBVvfHRdVZT6Zt4/t3UjkloQMOig4GPygkXTMNf1FbgrKY1miN/P6wdz+zTmrfOwuixs/2lywz7dHpIlLL3GEi+EZh6KxXGONNnshSCy4GmahDZT+AwO6kWUoRXLhVBf0HbHxoYptxXHDuH+5aNnyLrKaBGTz/4pObsq2lu7pBbnUxmAYksCrc3gFiS0UM8Jm48qHyKisX0D03D2fy7oDzobU3RoodZu+LFkz3VVXvxUiTPIzEo+DXDX15StVWUsqvKnnQEkgDu7jMo1z6Cz428yXHvVCzk3alT8i9DmC5uk1kiNTHT9QQOogpBuR5ut3+ehoKgl7kBIvDlndthNloJlQLqMvUw794gANbx20+VNQ8+39GNtefaMMDo9wv9UV6sLXTljuAnZRej+i6M0JcVYR
  template:
    metadata:
      name: oam-s3-creds
      namespace: oam
