# Sync the current Maxar STAC catalog into pgstac db
apiVersion: batch/v1
kind: CronJob
metadata:
  name: stac-ingest-maxar
  namespace: oam
  labels:
    app: stac-ingest-maxar
spec:
  # Daily at midnight
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: stac-ingest-maxar
        spec:
          restartPolicy: Never
          containers:
            - name: stac-ingest-maxar
              image: ghcr.io/hotosm/openaerialmap/stac-ingester:main
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "768m"
                  memory: "4096Mi"
                requests:
                  cpu: "256m"
                  memory: "3072Mi"
              command:
                - "/bin/sh"
                - "-c"
              args:
                - |
                  # Exit immediately if a command exits with a non-zero status
                  set -e

                  # Database connection configured through standard PG* environment variables
                  # Environment variables are already set by the container

                  echo "Beginning sync"
                  hotosm sync-maxar --uploaded-since 86700

                  echo "Job complete"
              env:
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: oam-eoapi-pgstac-prod-db-creds
                - name: PGPORT
                  valueFrom:
                    secretKeyRef:
                      key: port
                      name: oam-eoapi-pgstac-prod-db-creds
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      key: host
                      name: oam-eoapi-pgstac-prod-db-creds
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: oam-eoapi-pgstac-prod-db-creds
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database
                      name: oam-eoapi-pgstac-prod-db-creds
      backoffLimit: 2
