# Restic / node-agent required for filesystem-level backups (non-CSI)
deployNodeAgent: true

configuration:
  backupSyncPeriod: 48h
  backupStorageLocation:
    - provider: aws
      # Do not set this, it defaults to 'default', which is used elsewhere
      # kubectl get backupstoragelocation -n velero
      # name: hotosm-k8s-volume-backup
      bucket: hotosm-k8s-volume-backup
      default: true
      credential:
        name: velero-s3-creds
        key: cloud
      config:
        region: us-east-1

  # we don't actually need this, but deployment complains if it doesn't exist
  # needed if using CSI volume snapshots (not restic)
  volumeSnapshotLocation:
    # Default name is 'default', which we want
    # - name: hotosm-k8s-volume-snapshots
    - provider: aws
      config:
        region: us-east-1

  # ensures all PVCs are included in backups by default
  defaultVolumesToFsBackup: true

credentials:
  useSecret: true
  existingSecret: velero-s3-creds

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

metrics:
  enabled: false
