---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-s3-creds
  namespace: mlflow
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCKirL+93WTKehGtfgLBD202rS7SdY500lGMIhsnZON6OjuJYkYxaFqX5vpPHFhlD8BkQ2JcQurbFbFJJUjAxjJH9z1ndEIjrRT+DnsEG640K7ucRg8oBzeG++VBud4Kf9wxgVuI8+81zZTTlJXivHNKGMkbgvYDjPqStqjHdjp191BjmkXO7eOh6LGryEOjLKsUYS0l67xMbbsGAS7OTXWVAxAWLLEue+IH9TX9ww3t+zS6KUCSxCWf5ZbpZ+7zsc3qM4uXo9N9+dlyepioMmmFtPwj9n/11kjQCrHD7nzsdLWELJ46t09hsREpL9gd9uOk7sNxTYeahJ9ZLyZWnJrJNjqWvfVxQBBHLgQmJ88hIApX7luuyAhlhoxLim1JtHQGR6cAbarKgipNw/h0Vn+vKoFQLh6c4//AgU/hUKwLHAqMwpj5vd8wteIxW64ypbXVwKimwvMP25GqvNbQQwWY9v2oQapX5JfJZ4PeoE2OqAgIjQJidOgfyjqQReyLE+3/uBLAGeKwt3h7GOqjZcqBFW47Wc5+fXACh4Q2QbbGNnzsk/ssqgrmOjMBAnfPduvGc7R7A9G+Y32tjI8nHAiqq0EClysgjqPfYIRQNRyuugsq/K0Ofww1/FOmLtuuHXdNuSQLhELeXWS75X3UQMZWWQvbNJKXid+30p4p3QN/Ka5dGe7q/KiGY8qHDvohDmSDzoZ6SrLkYzBkLQF2LatFXS/xQ==
    AWS_SECRET_ACCESS_KEY: AgAlopuTl/GjgBtKKAmchH28iws6hakaoeW/7QKJRW53nurzM11i03v3ltOPVVhwCq2aK+x1VCR6AMG5P8u79yrp4HOztBxru/R7oF2e2R6J5bSQ7N472uUwIk7fXWzSir8S80Lv8ZQfkmiqKjSclmvK+zK/M2if3tNtX7PY7Qrbz0rqJR7i8AwyP5AsKOaTot24NczwgruY6qRU91M4lQaTugVqcQQy//bItGWBRxZPd5yaZi++mm5k81GPAcX3KuFldbZymW+hslqMqrVkDiOETl5iqLhD6XffWSZVpLcZkGxeWzgpIEQhwGEmEhmKbrfRF+ZPna3DP2NwB3Nug1GFHuCnOWEbFhlaSr1XU7Xe9UPJpv9zIFDUapuQTT2ls8fFehSkSxETvG42jjwK+K5dN93eSx5QqeSOOtxjOq7KfACjEgtOqOxx7Md1kvX/ywOFZRr2mrD65F9cxny7ocI8hNhTqsapIK5+Qj7tsUuykxYSyt/svNiOw2IpfW41uP0ihHp/OgfBUcA19X6ic0YWlJDiHoKa/rSX15NRbdRMM2W+8Q87m5jL67laZRc3EjiU5BPuN2uIwKUzqNgJbose2h/wiEHg8Z6qUv/G1MplV5gfNLEjj8ijak6QvIFkUsCOeQpzKZWcP79vOehHc11VHGusNbiSZHJ5SrMM6Cf3aLGZXkF3UC3TQubjs2SoTBFSZQvLm/bj761kkHkAzl1IeTZHfTcICTA2k5kanbR9k5bwlCZPEYux
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-s3-creds
      namespace: mlflow
