---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-admin-password
  namespace: mlflow
spec:
  encryptedData:
    adminPassword: AgCuy4HRfJiA3XAyNICphwvBLiHJAM8UpsDF8a/vPOsxV6Dt7nB11w+HoVQdZHvXvSAS3T9FM639kNq7obKHyJ+/dBSIVlmkv3LAa1POdRP6rkdv39fXryzbTGND/WDhUSnA46ijKVc830BXW7PPIDS8t1/L9ZSVS1Hq4Z5wuEXu90yrwOt/MD7o0f7/AJEz8sFkReOZ8Hx2XJlymg8IMHFNwh3ANVpBCE4kZq9W2ipififYOSz5DxffeG/fgUZL4SMM5Fe3AdtC/g72ZolcifPd/JlHX94S/+mlYIamc7cLjcwatbnoZ1RXI9dLbAC3VGxDCKP17xNaAYBV1HDcBd/cV68B9UrUAebcjgBH/BOnIumiDtMOwZqqrukNgaqCU2LrxC2gETLJVDvOrF3wlB66K5tDD2i0k6aGlbHitvR/XtVCPzeamzuPKFNlbFiNIEnHTWCnBrXJ2Grvhs2zE4fB78EbGvGsH04i7krHaJqEJDDOv0xqqyCSGmWme8DVip6AYKklOLIeZpoPcD1oYj3HzVNBJAcPr0LMocpU8/+SUf4Tta7vvq9tDJPyfoxFU9x2gfEPUKILmwPVinQUuAPZ88IP67JGILqjPMYaxdKp/+k6OeSSlRUzRUMaP4H/SVqef0whGa+5wkzzC15EXqDcpLGkNFjfIFVBpXTBK+qWVkLQKhtTnERyLLUOf+noxlfHcOibxXAWm+/wnCwvD6Xt6oeIbteUUIA=
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-admin-password
      namespace: mlflow
