---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-db-creds
  namespace: mlflow
spec:
  encryptedData:
    password: AgBCl2TzCd1PcuLH0KBPY8Z5qwp6lRwUbKjkM7ReMArW/+PHLDmEHcXNLFn+THOkqkGFjPW6I8szGD4JCIEd/CUVHRKckVs8GxjxcB5UuSEkzUAmfNInobjF2IiSpcfxrzWdpdA3WW0fiiBaMuzLSAIA3L3nRu3Rw72O0xmyfkzFYTY+L3DqFQseSxH5uwru6VuumOat9142194isJFwv1t+5SslOQ/T824oC7FI2yVXWsMWN24CU+Fkz2zzSL8FnM0nxeOPvwdVltIBwIzWM46uXntmREw3+dYCfm9Ept2wA3rErxuL8lmohCTmVFSI3qjiekbXa9SWGoi8vG+xVisYX4XRMKymQhMNcJDZdxh1p889+B0GjwsFspjPmqN1iR/BbrgLjUYqZSGW5ISKitZX7CaFM1p+zZ6fCVWq0HIto+o42rwGjAoYejugPdjqZ8uUlpe10BKelREaVawWCmBC0j2dmxl3Wk5DuFTXd6RVXq4K6toX6tKPfqzhckBiz/tRv6j+btWAWlbA52iyEIq5byrUj2SnzxNvQ4tRhb9Yg1ZgL7ADaQnd9sagpvKdAPyfiNEEqMRF7r2de3OTNXnuyexjmnCdPg6E+6alin7RjcREkzyV22bYiDIe0VrHacNajxe18iZESMSYZiBOpqu1xqa9Dc8lRMIYFox1JX8ouAxmJlaFxMDZrUIiKivRsertywKiQP2UNNoTo8OLRxRxmCKfETE2TZmAi9eBtQGq0FT51zK1KO1n9+xOg2PayMBZc3kDlSeFxhA/DaEiFsE3bMEhHXxm
    username: AgBmoZauhEoEeMLmdj4yRT5tVXYfDXIdmBlFa4lYeFY7KjbtO7muBoRgINsc09KXonDinPmbW9HXh2vR68dNFlvL8T7keINEVeT8tOW/Nq7hF71Qpl4M0A5I3ic3a5K5Wk+jaLz6aTVSkyJVmW6iEvT+i27fLdATy5jOY36lmkQZmdm90qG3T7c/qz8r5YHr+m3acxerwjFilXe7sS3lxIfXOqYkhB50hzA6udWco4sjwem1S6P0dDO/vFlPgHluhZkShPDlky6isUM0CddLyoeLeF/dA3+C4excv/1s9sv1cAg+OBdoH7jQ3onk2/wV83zgXvBsWldxBiGTZwC99t3TphPjuErIlcwOgdk3GtEAhuUP6PUQRqULvj+gsqcJ41qL0An1XyYzufnN4jJnKowXEq+qtXhOnLCxVvDJxpHPD+FwRypaD/3DC27NAM8rVyr0JPfBmDY2AXtwcJFSggklZ0uer50qJdU/dkJSP1AQXSR/H83+dEZEsNWtw7aLaUqMZqg57ggkgceVboFA6iza9mJ+q4Hzj8S4xsfs2lha+2cHaBHfsDwpf1+kAwxKcRbjLwpMDg+WcAu9G6LKWRuk29JolcDIT6Pmhudi4jTribGePrlAikuqFPu/PFYLUDniXQnbLXKlim2nkCZRwU2Soo6A8R26l27+IW130POQ/DZKtGQK8md/bOWsx8uJrhjYs47+n6g=
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-db-creds
      namespace: mlflow
