---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-admin-password
  namespace: fair-staging
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    adminPassword: AgCOLhZW9MytMAlpXaaHGwOXsR43NNkRw2KTRM8x/HTl+kBH4XRk5TSOohxKLkeQqJwkKc33qrbXpQ0lD8z1wu7wUdsWIzniv49Q5C+bEMqSrkp5o0JTabb/N0OUdZO22amfY9wqj2U13au1C3xncGViqyD/EETH5yFr1Gs6BAJ4b4z8Gh035cd88JV2hR4MGPAIBsqq1bu2GFE+LQEn0+hOFTM31klRvFBE8Ted+R5NCYoqiJHNkLyMX8Grr9uxQRRlkCFcDervnkasqji2STT1QOX+xNrVm611yAoFtzrMe2OGTHjIs4WlRKg8hCWSLiUgRd+jud83y//c0818mb7RIiSy+LKJ/a3FVTw1C6zdppN40HhnbeeNO8ciwpsS5SqopeOuKLiIg3O1ggMeQSWj6uPg1DQmCl6A83Bn5ZFg0tDeEUqV/XhMJuWgWl/vZUvOoyhf1uz9ID1xaHPzqGErVtPNaDmo/AdeG5bm/AZC5P6Tm7/8BOPoEjyX+MxAmqr5jrwYM8ZDw5txiq++AcmAAFo6CIlfIEzrg++LD6MZlprD+qAfAtshg2aJw9gQ1BOywNSLuuZq2EyhT7AMbwJqgL9xcfJiQr2N8KCqU9MQtXC6uJ5XWDgvbK1iweV0CIU0rN0m1yGNvUi6JkI6epoHJYi5UgQf5UV6zWmhct1w0u+dNLDRzhQuNprOk11Z62JYORdngPHzGFjtyuP/0/sTe0ifsjE=
    adminUsername: AgAzjeeQvkzsIigtkP115aoErgjyUVdjweKRcS1xZBX0b5hFCqAPOkd5yGVFpHwZFPwSXvPl0S01LgDlCHQ2Y/pGU7h++lBGDcRAKvXfTi7kFP78FI3PxTgxCSrM8lsk1JpPAiQ3fps7KV6gDONDqfild5ccleu6nxqaHHe/JD0lvssvN+bo430qiRTrXsSgfGMkbav69DlSjY9U4Q2/DZF9odgbcCOovd89G5x/NHrIgn7QV21LShhVqfxy7bt4dK/NZffRjnEAoe3o7zxqY/K27vF0UveQD9VqxRbdwm4UNnItH98mAXrizYp8ZcriQIG8pDg2b4jWTJ5+2UVIEvOFzAad2qP4i0VuOzlOXNJo4iZ+pbr9iWDTAt20iBIYLPll0EUrUMkdnD/GPHonSoV+RbwMioDixVO4jhVOjrNOfAVqAnIVCDR0bn6B19KlA8/0NgNZte6oYDL1A+5zeM6e0KmGyVdQ9ezeS1NfcL2bwiDmfPEnVKKwNPJib8Hw3tRQGWlME/m8XiK7BWYXnd5izsRugQb41I1+PPBBmop/k0CHnZ3dtiXAXiQd8VS0+PMsvqg6YOaM52Z8kd+dsEes41cqhIpTS3lasS1h1w/nUq0EyBkyszN+WtzFdeSXsSISUJzyyjZlBSlQs1PQUt2ZbvYSGVvgSe610nzLFA0QYukVkMBeRKCJLd+RZqaCP1g/nQ2RnA==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: Prune=false,Delete=false
      creationTimestamp: null
      name: mlflow-admin-password
      namespace: fair-staging
