---
## TODO: For now we need to manually apply this with kubectl apply -f apps/staging/fair/fair-api-creds.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-s3-creds
  namespace: fair-staging
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAlLnMv1ZoRzDnc1fd0mKcJydIbDdp7NGIUWTmzGYmadHaC51odyKIBirI627b6tf5hgQrdaEFL5JgJXj3f6ok1lxa7yOQ1BcVAFxkiHVtzUFUYkER5c6j/cThgSgI1fv2l/RSOeIawwbVe/py4xxJ3n/zc6wrvuNlAbubTQZMDoHYilAEVVJyovCBwcxbzee7MpDAhyDtGAWYB3o0rMhAYF67kcurR5auPaM9HbRycOGOfTm+x8aaIIK7Ytl6jqhYGXXVlbzNvfc7a4kkCZBTC7jMsASanfAUvdSLw5HdJJusz5Pjs5fftNJXmpmOhJ/CW17154VwFVZuZyNE0gOlDeyeAIVLbckhplygEAqdTd0I7rwQnGY3QQYQE0rb1yDUQQp8kFd+K1XE7V+WC/C+DvdS13GyHL6JqNZrBsxKlq2OLIf6Uy9TZKkR3wGj8mWylnSmphkQngTuH+WC3nUmBg0urCUTmjxVrSoHKR7Lx9KiKXb865TZPdXWFQ4DjJ6I6VdkG0VLXhCRf2qsdCchx9hwacraMC6dgwDkOYNM7VcMSIKwDykt8a8iLUlbY17EEWtotGpfmqzFnwoLsRd/4KIsfQ3wvm6FFJ//4EMuRX8g4xGJV5fcVDk+GW4zpXl1CzCbFaEofTWc1+HnuXt4o4pWGQJ+XDB0AG/FVtuQyXao0h+RxX3SP+qA7G4ARxaGhuIoZ1yeRlu+NHb98y1Vn6fh4mA==
    AWS_SECRET_ACCESS_KEY: AgBlxbPwH5+o/fLE21F2U81sqvDG9cDT53LVARchSIR88n5ll3uJDRzlG8GBsBAYdmeINlxrnm6KPnBDagMx7aiZnYJRikpIh5YkrbuNNJNlfFlO5jurtT0/fM5ZKJ93YTEtcbapl5YfL2fDmrDVnYjdygm4+ZjHKO/PQc/DFTDP9+KeDPhTwoun09waNroYdN5XnFZ23B7QfmstobckCoV3lr+BESZZ+uynbK7YZxb6p1uAn03lClNLfEF4F4nAflzIbFsX/Qts9bk8ZPiglPdb565Ucve5/Sv38w3ntUbqyD0PC1yRCr0xklV/O4CN5cDUOakOQwybRbMt4ls5KRWiYzXIQz0GUMldk0VHFXoSqasK2m7SPPf462HJJBh9b0FKmkqthzcUMoW0Dc5XYP+02pFIEb5f169W5o7IJzx7FD4Y8ATY+OcpF1dM4lVyU8CJW8JoKEkZjbJ5ejFdsRm8ruxeBVX7EujtNwTIaV+9SUtkBgXstzkZ3jgNYw5qhWioJFYWr6W81j8jc9QhT6oAY6/5AxYIg5x9dx44x6hgUac6OSWNPx78ZxqjAbCILED1XFu6NvKIoDa19BHTc/y+2Ka1+4JrhqBsTKpkzM7ODWOjFCABxU1tJoBH2yG3PQDoY5vLkrbywEBlmmcBfbFEvUORXekqRcnNgLzGKyvFnIQJ4TbJjU+W/vmYXFteE2gSV+yEVhfgOaXim6yU4MMNljbltaKyhZXRkWsqYd9+qHt9NpKuTbwH
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: Prune=false,Delete=false
      creationTimestamp: null
      name: mlflow-s3-creds
      namespace: fair-staging
