---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-db-creds
  namespace: fair-staging
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgA9iwFyAji5yIrcmQ5bk90K00Vvm6vPu+2xMtxWRqZh9pb393FUbnx3tYJq/BEZs6HcUwOWqiFQcF4aOOC64oQBLfrlbjZSnDU2eTagTC/jr6v3Tu0VLLS9DG2zeFevHpAnJ2dml1Br08g05WU/m/IJS09e01PGwvD221XN7OlTOK4iA2KlQZY8imqE69+zlKtHpuDkzIUwcnJxZw22XUIpG86BMx9dAU3f2lUwy3/z6Vxmt8Ws3lqz5KAqYJ2ovZgji1SVtIwP7/CB4GFCcPbxqARxE3iDtkIuc38SzdZH52T4rhJDO9kq7+vnSJ4dKF9FtRyZER+tXi20TbF5xJr0GdbclzYoDvd9MlzfzEf9PP1l0bOXbsOAs0kPATdwEgIhOG/jIWsCSfs0LIyjIlDXXFBx+5vdgHjOhVm2k9QCHJWqZb+haPdio599AOQXUpFFKKAXp1CV6N5HpPMncM3+YpFwWCI+kS4dief0E06Fl5gAjqLzq08AhR8tazYKKZr/YVhQ6cqtRfUdgGrcF8QrtjkvzefJBbswxI3BsZmkcYdOeRvTEt70XejhIL9UDzdRkZH8v1JlvfpNOyen6kLVnUUbgBAoSCNF9corL49066GBr/Gb0S8kzNEx9ljVFor2rnXVsJHmp5lnqHnJTGLfbV31qJHrYvVqBFbZQs5gnEGezJKtsh2zUjlPZ0LTtKOs0VVuEKKp5TWK2uQUZ8uG2GmXNCjJS668ikSIm3ydetenJ7ScO5uFKY/Jz5JF7hhfxe7Yv52/T6RKLswz8AaIoRnbou2E
    username: AgA2EkdwLQt7+YS+bl3XuQMMuzXbWyafCcKrRTDDZvyA/cc8uUYRzJAUpPA/3wtwd5CwNBENaDQLMCWKDewva5lixiISA/Vk1zT/VsX6JXYijKxwmoP4zRIKEIMV3avfvwe4p37HwQEj+qhJ5HRfkBQPN8FOrR4hCLZH9FpiAhJ5dMsihFBhnMEl2V69PFYFYl3fzu7FNP3v8xAEE8a2MLJuEEyxsmGca4frzN60j0iTODWU5qzjo/cbqCn55fzvJe4pUcx+pkxJdQAcHoW3rDcuQ0elGBkLvpk6DuQh8sPyuyA54bSxwTDJKd74B02WTZ28VXksbj4F5EOLR3HD3phfRVz7hQy1z2m8cz4juaHaWaSWxppDg6XwztgbTWcj/eJRdHSb/E7yO5Cozasddn50o4/MJqSe6xsCOiiMOiKblAFIJILadzmAhj2eJqEhMfQog7mGsrJ78uEh5GlBWbzPh2UO8QmgEqOLZaWS15pxllluZigruX4B9a7iZLsjfH2T4GwMy3QJPkVM9fzC04+MdXarsUCex7cMXFDSkkf3Q361zlYXlPVFT+qfeLEPv+ThAWkOHp/e+ylSh4ItYfNsXpfKbSY0Z5Kk77ZZfUQJE50zmLQZ0TqXdnBxxAz0KNh2Ldy7cVDqdzcQB2/NB9Ft2xHjevIRcfT2WSy53/xv7ffpRvEkwj3xb7JACI+hXfnqfLiQpos=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: Prune=false,Delete=false
      creationTimestamp: null
      name: mlflow-db-creds
      namespace: fair-staging
