---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zenml-extra-secret-env
  namespace: fair-staging
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    ZENML_SECRETS_STORE_ENCRYPTION_KEY: AgCh2xNyKrvO9yC0OZpsUyIsUK/FRRPeHf4WfVf9NkB+4NQOJqGzPmhifcstEDU42dy0bsNpWC5+cfNsPu+3UkVj/3gn9+A5upD1twYU8kPmu01qlhBLxLyDIcXYALkCLoH1JYugamschx+t97jPbPEu4tYFa1Fzk8PW41aa6cknnn/zZEpvKMoivIZXCa1wACr1DBQhiDWzYI91Nt68kJnRoJwfILZpDYN8JtZVkhimJenSLTIUGnM+qaqctHe9MTOrORuZge0No/C+aIhOzfSzhtW7JSHjefeqc/dWYlRrCfHKDkp+RHGYNHpnBrCAy+XkXZjGyYnBLNJ34w23hCyHLyHQ11z4GAtjgy/Anjf716VNgVjcYifE3uFV+jf0Akg53ldR9djDJ5yfozAZVG6tmbYfjKWfHqrXqTaeTOUBpp5Lvq6BeayZjLryIAOoAL73oCOp7Y4/YgnRvQFsJ577/ghCgHO6L8KAEEEc385cmy14jLMHKLSOL9TDfNPZk2GwLFDlazC6JApjYSeTFuwa+jF0YYisDFaJvbnHQW5Gjvl7T+lUUmVs0QF607GifU5gmXDFgERHjztc01ETUPaSTUWCd9IT8E82eKMuw472KwvVqS8OHKyDmnwe2DGYIomMXChkl0lgSxPpspAwDwBgjB/Ap3xbmPOJ3m3ZROPgsSWYfk5ixrQCr49DX3Rl4iRLtpkjNB+Hls2/rQ9wJSDlmquUxMheVB4oYdFEq+wyPPIFqhqDD3CfYeLJjbMnZtHYyrg1POeP8MvFB69+el5+
    ZENML_STORE_PASSWORD: AgAQ/RDP0AjA4ddF9HZNbaFcfreMV3s9S7BWMdDlYzShsWc9rfrOpSTKdhU7VzWTizAygSwAnwFxjoZLSe/hogj2IArTQ3H13AKSJ5sqjlexzqrU3p4aH1/VgipU9ZYDCydPsKiRKtZO98MCfK+qCV9OMDIvE4Rh0uHymquPCFTeNAO2YPhSoYvHfI97TkoY8+1Hp5C4CZ4tTDx/Aa0TVshC2tHj0p/saXNMT8Lgm6XyrLo/QAS9SYfybbXgLokc/b2JYE3myw/g0X9Pfzi2ZlkC1XkDwMNKGPklDRONY04jhjgxwtQDmZzCy1rKqarxCWKSlvRbcUpBb9A6gN2IkDM1F2IuL6LNP4/BUa9Fx0Db9F8BjYCnssLWCkS7gPi3fXqXijUoZ0q2i+TxM9FwBi+EjICDGN734rJN/9GCkmg5+yMivpxTL/+8mnLTegkaHyqe4SkR9rFO1gSAp2guQ9fMWWEOAYC3QrEL5OefBqBHx2+TH4PTnECLI9552vzWIm3A63WAOQHOYc81mfOhEkOb0cpqkfbxUVnCAG7WZSGFzpi0GQx2N9ShO6vcL6St21rgA1JaGyAA9kG8XHIvovPQVT2sABpu+ty5OT9BFk0kCc7Td9voJb1fzHWuZK/FFB3Ey0ZiKKVDo3BeOQsmtN0iTtJxdHw4klvKz6/fC8r1Fo9fGYy4YWCjDyO1jWadtsOuw2GuZ5PeTS29eoHqEA3kzvLnLUkrVO1VVaYZUwezSUa8cSsSr99VJ6HkD/A8jzDEi/E9Pca+jLMpwdlrRjmdhnu3XQQB
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: Prune=false,Delete=false
      creationTimestamp: null
      name: zenml-extra-secret-env
      namespace: fair-staging
