---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fair-stac-db-creds
  namespace: fair
spec:
  encryptedData:
    password: AgCp8/f3+wF6n3hcYFbQaGeZDYCtvlfSzCUKtdCTUtpBWkXE4uv9t4Ey0ocBo6S0Oz2F2Hji0BhERo87SdnmlvFKDutSHsh7mHobmIyZiDtE1JL7bmhQTT3gfeevcDbhwEDZNxpn23zNT3UzS4+W5OUXsm32f3b2RTWe2nokrxhXgLpOJIHwHuuDbyoqySsp+XIQA1AH0uIj0Q+C4sRjWH5Tlyb+NZlD6BFzTeTYr2bgD1O8Li2ZuHGYklthofDXYzVz8eY2hGG3ir9YDEWi+R+iPhI6A3tTh6o2zUmFsw/nP0hA6CT+kOOjMnLvxWXYyUN5v2RrPAC3JVVEhWhgvhCvT/ktoLB/1aKcgBdGmY8y5hUKpjRRAIVLx8PWaHfgeG2Z5AREUXwoqRtMKSV2wv1YMNJOwmG+NOTzet8/h9t+iyqoVpzqBOvUBV3LX9ia0v6smn7mp6cmFZaLZmC60A8xfvevpKZpyWGvkeajFJr+VB7d9ZdKidc9tCvJ6+JDfn/YOGCQ6p4FCJWvA71VHeEvKEBcqrrxtEWGdRUjCgcbPt55vRE59Kep/km9CxWQ2XTfextN5EL7vgDiUZ79Hynn0EsY0wZ3zhKsJZYI7JbTkCOw1jkkPQ7wX+7wlHwMJdeZ4dUQMGkz7gdppdZc3zyC5uQAQsE7lKlpMwYQQoNE1LMO2AFVfieILp5Z3p85jTqf3VJVIhzoM3XxVjrwLzT8YOYb2DiPl/X5Kp/HdX0xgwAGYe96KtHXOz/OWHiZ9U8f1SBoyj0sEryGmv+WnkQHspyXbtLG
    username: AgC2UELTPSxmJtjvyYeykKIvkznhv7yaPY/HPi9vzt2Ubzc1PwUBS/SOkAuuG19vFAOYGKg8CuQgxE50L5Yx8LnaX8Mw1vIrs0Yb3ASp47kp8rn8HYFVHiSLtotjTrxfWnD5AMFKqVlwzPxeAhFSeX3Tl2fLTN9WHCRs94/UDZqAZTuNgY3nsppB4z7YPNeNzf2ffmt9eS+w3+yQhR6di0qL3BAaOWA2aMaMWHQLRJmKruVR7CJ5oz8sDhELLdlcNRvqwoejZenvQypDxNM3kNZ/ZmQ7op0+sVk77AikkQCUx743tOkLNHKw4MRRRn+KGuUOOKOzN8gvpd1rNJH/7SGdqwUGP5ThcAICegRUNUAlCJAtYt+GK00tj4r+H2RttfTH49Fsh1SiG5u2i/PefFKzBqpnLuI5b/OyNAoJqFabAFQq3bsKUQVieAAdU6s1AiK+k0OnMgEK4VV7XRduHHgbVksXbGonsF6gWdSAu+MKD/J3hwaYsEgTStv1Fn5eurv1r3cNRStAS+HOZ2WVDdB2F9PeAt4UKqhFBnnTcz3PmNfZQ/7IhtMyA/ZGLzoGl2vl05xLTM3txYwnZWcSP/QlGXFlkXtioDdDWHtTu+0+8KAZDMfpMkQ5DItAeAVCwt4O8ZmKE2xkAFH6SOa7ZepPb9MOP4bmx3dHwMgrzB8qWIRRP6zgQmrk6e8HZ2uBlJloRSxIQwZ71FE=
  template:
    metadata:
      creationTimestamp: null
      name: fair-stac-db-creds
      namespace: fair
