---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fair-stac-prod-db-creds
  namespace: fair-prod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  encryptedData:
    password: AgA0PUdYNNeO5oq21a10kYEl5spnuq8kURr4v/wfqZ+4ZDyDcclvt15mBNED249sOomQJN4gk0BgoS1CVK1Rlx/0ypo8ogcECOmUlscweDpVLLRQ7kdxvVFDpyMwGsXDuK+9s/pxps13FOkl1RDktgx84mZTVYLtdY0Do/kN9i2GIQiOtS2RgY7bKFCrpBTO7SSA4n5Xcz3JdIpKF6XZ3H14XOvdRr1KbxJDEraZK1MDxmGa+UBVqHwAXWimGDUSLBOjzB+OcqXg8uKV1n2sMvq+09Vao2P5HFD4ENKZhjiejWotQmLHe0ITx6wuPCNBOJA1WbeLnItrwWoJNpEBtFz66x92Z//vx5eZFj8QNZd5CHpN5PaC0rAQaKhNd9StzCzEp7UguxRwk/HOSQCnoWnUHICfzynCF8LDuFdfcpCeOyZyYGU8BZQtotlegHV8v0oMrB2fgMNVF0inyQuiRPZruLhzD8idpMElqKPwJA1e3D3kDbhctDymZE6QokhrRR6m46xbC6lDwvl/Lhgb2M/nOdX5bxPI/aYMWeLzHw2ddlLdEUBKz4TZEEEahC2a8e7DH29w9GERz7ZRcyKwSISe/XD8dzopDEP/1XQ/yw1okpmv0p3gS1jcMt8LVKOBr2MHuu/W4DYd8vNFWqFzXmv/HiJhpts+wLVfOmZbNYkh1mOn93jH1LF3M3kyoCPu9oolYGviSdfeAhOIZB4jk2SXaJGFhjdpIpOjRtP066S7Qw==
    username: AgCO4JFLq2DNf84SyfYtR4lvOuFLygQ4F53tLF1Mr9T6bPGpmW/FFdtRiVlXMSz1JXG5FvSqVV5mXMal/+VOse9mttOd7ugEgJ3OmyQaUDh9SZK8w5VCRDV26ZUOPcSKuJDYIUBjBSbhOVVS1EisUnRsRTqNsinIndVYX8Qfu8mLtolQQ4dwPBo047s5SU47Uajik2dRr99pq/d1yfFHKR6rjFmUE5SUddySHGkmZRjHLpz5k9fS+XI3e89KXV8snKTUoMCcyMStUVNx6jQAlKyfVZrtzevv6hY4p0RSRET6Ujn3JCnI7BfnZ8i2rmgMoBLleMxo+RzpylZMANVIpnBFPEhrSyNw3bm4NQGbpQTjWryee32NTUTcgDa8xlrh3lpSkOGK5oUPIGrWJ6gFwqh/s2KEMAkO/aGySNaNoZgmqADr4iZfwId30TZO6kpo1acPhROexHF6sS/SiU3vOh75TNXbRjuVJKTyeRja1x+rT2pKOo3UHzFmLRyTJNn2SPmWHS6SryM1VQsWdh8o2ydKEOe4tDKi1ptnQuI9haP7hSK7wDsSfr6Ep8DpesafcDns9Ode5TpySYejlAsPlJGIWg4XxJlGS7rhn5L0sVXyJo/76ihdyyRAwa75h4R6p+NVXoZ1H9hknKsvTB0loxI6cCD0mS61Yjx07KVkdgBIffMhWTjNbjHZlPhNuwSLre902SDZ0A80WwNqqI8e1Q==
  template:
    metadata:
      name: fair-stac-prod-db-creds
      namespace: fair-prod
    type: Opaque
