---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-prod-admin-password
  namespace: fair-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  encryptedData:
    adminPassword: AgBGDDxo48DIq/1+R1aehcfJ3bIyGxylRax7qPZGXpkS8btYz59IFYteE3CkDwlKoXUk1UuwY4SbfssNd5xwNxIe0AQhgjrtC4adyshDZ7rexDkuLmYVVjrrhGbHdMNGrXWK+T0J7/3ojUi1nMjZYdnqucfGf/lqqZuecxGPmumz+tjEdx0nVu1gW0aeMF6Y3/6Iyic6N8lIlY8sI++y9nE4fdZ4dl6o86OTbBh089JSDwT+jiIyqfGtKHXdrTlPQ0nwmptCV2G2rCVfvc9w9j5mJZ+oGBkziFZ4hBqMEwmXjPLkNq307XCPGXP+UmwA3Koa4B/FTZpgmYPEjeGo9yf5aMZ6Mp/yJgCJgB26KaqEpDoepo6iU2kSqZFEvqbI/Ht2mQpk1tsYSwc1xSX1Oi8WI8MtOhElWRTGroiLfYcHqvhDdy5v56P2bN9ncdsXhefqpvo2a51DvylfiLWX9izey/Vqxp0NY380UdDMI4pEJmd+44kmxu975N8umDfoO8aJQ8ZqntLsYqcWxJVelvj09wFZAUEuTFldUv5sMtwPJcg5PnC3UrD/7Q1P1of6vxPY9KgUM0zoD2uT4ABnjnbKGqMD1YjyR7OKyHg8QleSS+9t1QhNUcXtfFEnil49zSFdvMZ3nerKzOO5N9rn4qXU/Hwg1CegawO+heCtz1mnMNXiD1f9jpyyKMJPmTQyhfLCz2/CQ3reBoK6mUn5GTA7ESgdF+EyXHihElzJn8SvKQ==
    adminUsername: AgBIDEdL/7dfBT6SzuVVGG0o0u4CO7JDSyIoK8hqxSWjxUF56kMWF1ZhKrcSxSKhFHWU3Cv7ikEcCWOE0TRvebevTeqJgYS+nt1ch/E/GrmPzBT3EwFbLqDuGz9Fd2nFJ2uoijhtOAJepwAfDB9506GMWAW1yXqyHtbnN0bxwW06SxARzSpZh5QOS/7l64e4Z0NU/Vx6sXY3Yc5srAXiwfHO9Eh4YiRbCSZ73ge1sB3PGi6p6CHgBBR7tmrqRt0H3cFUFXjSoQR+myDklHQKPz8LoSaeNMuq7+yW8p5D8Ri67sMvdpI+Ss2jFFoEq6D6tNEkO2dxtwN6BbGbsOJj37V4CymjNn/Dad/U/CfEZh0TEIADBKcF5C1DNCjYgsvzNXi8SymmD0hi6FV9/lTfNFDhGoa44X7spyyQN4lZceHaTDAg5YAbQ7HXQdaz3hlUyEJZNdkmZc+RTDx289VOVH8zrDkOQUq3rOe1ShC7X5NQNow36jVMC2CTGxhQaeVrW/7rO1108GNxmkKF5/89TBUgUYESE8tpGz0TbxDyy1Ff0GRRpVptOsBzV8VkalSaN4GMT/PQnph0Pz88X8aaoI/jMVFU45Ysc7IdC8H7A4svuKuSwIoPEICmr/xxw66oh+IG4L96YNL5YTMGp2Mhp1bBKXgrolkIfE61D5kjRppEbXiJff7ALVs0AyAzDk0Qm4l3kmfcwhqFANhjhyzwLtqWERgqEVw=
  template:
    metadata:
      name: mlflow-prod-admin-password
      namespace: fair-prod
