---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-s3-creds
  namespace: fair-prod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgByJJLGRxRFetKEx7UEYSly3sY/1U4kdbRtEmB5t8Sh6yF9yFaUE8sBprNzVpxKG1lFe1k8vRxxziRnQM6gezQdTScNKbTfOrB+CHh9XtL28n6oXRyGA6HLe8zx0qSW+J906coDKhMGWGK2ZTBybOY8uZUmbgA/FkehYNbNrpacVrwIwNomeb9rEDR1z3xHMgvGioi92eG1gGI/l1s7V16okHUHuouxq+Y7dIYwx3pAWI4HKpJxnFE1eOjWfMnHhTSFPvZL/AF69Cj3BJdLNYb3gE1jR19OQPoXXs7S76r33y6Xqn3wiqF/P/GOVRXZ+54RqXKUaLbiLGTsWWiqr1vN5ZHSWopyEEeCbGcElO88bB2mYdEAYVgkXyQVx1f9g/6L9vCyZQ/EzO9eM0zJTT94zLjaLU636y9Y29LMmIF9sNW+Py9ZSqaTn6i8CQjWMO7Q+XSYxVR3vpM4A303JRbeUP5iAUqsQKmxbUiqdIhCm7lVGKs5kYQ9bywZ+z+m8MuZguyfIraawMjCra9XKlviurR7hZCunFuogZSrQBhP7TKdRmvg63Tf7zK3z30GvOTPdrRByVvjpWgQMnfeSGt9vg7TYdDpNG9BLrMWu2xSqX5JaGb5M7HRfCQHrjvf471f/RmTLL8zJZxOXEJbgNweOwH63MsQ4Cvd8iW1lorlzOZhbQ2L4CFLi7RXHJTDmh/cofegdRzRvgLN/7OhNWleIltcTg==
    AWS_SECRET_ACCESS_KEY: AgC+16yKyp0XFfiV/f/c1ospCzZuSgBn/Cnf/zqgYGL4z70E8tPEBEbriUJD8xV3nFWANE4njPfEVgCJtZ9KwOg8CbjRvR2hQMLriqbivOIe4BE4VjNqUlEs+PaV27tR4893cuDUBChzrOTUhW3L1WWvQ2gCz2UFIlDi2xauVlI+dAz0hzPh7LZnZFvmtH3D/tzpk6AiNnGOj20UxQIfkxIwOfSuGRrdgd4wjCR5mrsSQXASBJd+oZqbeyHpATCE6OU3jwkesuNzCWGRMxR4L77tS7kUKWUBsq+1nwLQnjY/xkKNK9ShfwcTe58Q7oZGgMyay4xK8kUYMBmQHt46fswT0fOJeKEDjc7qg6FBBNRKHkI92dho/FYGVL/tigD/LOLLI2jeRS/rlic1Q4ZvbwO7iTBJTzB084f5jepldoDnE6dEVpQUV/kPUBl48CaMtlbMV2BYxmLkeuv3tiqRk0V0uoJ7XpRhARuTouN0W1cxkuuj1PUZVOzITZLdets/ilhWz9+0lion1+upPNvqP+uUQz4IqpPzBqJRvVEp6VzNufEotsU06gRq58lyxIv8bIUr8blRjmmIbIXFpoa8TcITlKsBs1S9IP7sMHJjsDfQs0hjOiNn5ni2iyQsGJLLNEETOu55KFQrXaOjOvYwQnJ7UIZwtYFcfaQATbXDCbOp1okDzbfN3Vb6kq+PtwAMDhESsXQSmMpM3+INxOz6m21hIY1kPztgXvTSJsHcROqzqINB0mCbjE+H
  template:
    metadata:
      name: mlflow-s3-creds
      namespace: fair-prod
    type: Opaque
