---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-prod-db-creds
  namespace: fair-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  encryptedData:
    password: AgCjxc9jB09Mq0v2A7rUTBVd+OYMMBmAa1sKiD3Wk9laDGxr6Yutw0o9qIc1dUyoUhKpEMUACjGIi5Qe6lVHkOhy0hHAesztcUIxXkA+w0i7Ps44bqZsn6BjKB+7UuBgdgS1qEjC0iLVK/C59HacSnRBqRFecDXcZJ4URQCWU/tKXon2wf7wCBGKfxYLSCrJZB2vCFHHIsWvsI/AsnxHUvqma4DstANIQ8hqLJrBpyZVb1WmONydhTqrJNBZ3E/9Pk77/yQxMzcJJAvBCUsJH3H0r05nFPbd9Hwl/kj67HqC4jyuIoG80sDBLHmOh7rPGOsI5yEGkCgqGAQrnncvprBn44dexgvpYxGDAfIvymYyL1HH2hXt5ZV1mu1Od5+gD45mLYYF/X4VepQh/ci0Pb35e6d90vjFIZsxBIyQgxO8v1aZyN0Ai4xm49FZSdoLwbadiZLiRHeTMNQLZCdiIL4KUpQlB3iz8ZWAcIx5Q4W7HG8wNRFziZHKGIsqORsEZ8qCOidzJdPCGaGUzX8ee7fyzaRZPAI33sd/ze92nq76TzmGvQ9Oo/BXsmhHoswv/zEof455tNrYvhcDAqMS4OAzl9f7KdakjGmLPWH+B94ZG1Y7gbaqik10DZD9t+jHzvustXGo5sTmDAnUo/HPx5zU8SxXBuyq4isR0u1U1k+pBjtxF+ktLlbH3W5oHDSjQsYnHhkBvD0+32yUhM5IDIApnus2MNhRnNeHPTTk8vacwg==
    username: AgA21wxdKqbrA18fkkZ5UFFy+fHgVJfZwwj32qU0L1aEAtlRafQzFXPvegNo3INz9UGqGXMwPfMgfM53TyjFOfoKNPTpqzaQsJM0YrU+jkhflKTFTgZt1AOOCBRVcQO3UApEhkdhp4cF1PXwN1hOVYyvIEumVxpdtGhUGyK2yXplHSysFTcdTjP4NWJK9CLjXUpUmyod4AZCLYiwXDw7aOS55QloMT1umiX06IqNNRDf6286/c0iNFTcYcoPuMmSULYJ5/xEkZQtMMWbnIy5/83PN1gMvdKhV+Ky8sLPjDsoMovVqZVuPq8L11O9/Sl6xtaCfzIyyInzr5PT91xZu4kGWpeFheztgSoYc38CjXEpnzICPhS+WRC3jfqXjrANm3M4RaDtVmfrQ7BWYWfFNGV1bP99N+yFW0FWZdOHukPhic30oc3wUr7L30YNtb8fS2zPmrt1sGnnIl3RdV0hfodd1ELPvfF4ADYzzUYYUYU07YwxgxCtwz6y6EPGKOIxf2Q8amSFQ7QOmeiYD/jIwUX8fiw7+IXsiXL68GHdJuvCwI33xxMEiDueI3cMn1V1dsgXKlG/+Jb7MvjCTPlWdrDAttqHO6X8qT4kkuVEvSD5OPbAtDORK6cIj4YF7ltcYjvWGaOidVxspLnv4ftM5BGIBzmWLu8vCLdC63Bv7hHYV9uoctR66V7WEq77H+R2Q+yrMkTqmnY=
  template:
    metadata:
      name: mlflow-prod-db-creds
      namespace: fair-prod
