---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zenml-extra-secret-env
  namespace: fair-prod
spec:
  encryptedData:
    ZENML_SECRETS_STORE_ENCRYPTION_KEY: AgCI35DcukDXxgsSTzTNvyH5KyxpesC75zW1q9byRR2CEH9j1j8T18ptUu3L2O+lhtT0wziflphSkT8DHhv2wQ/IQWCminzQfiNYR/3zXTl3omuSUNwrUK1s4zlR2UcVd1DaH0mjLq36QybzmEO4FWTyeBw/4H2Sa3dJzxVavyJNtlqTh50CGjNVd/YpCYPV/mdv2MHTsx8gWir4Lp0S2ZZdtadSvAh3C25iYCzx66CIrzcQ6TH0bPx6mLaiGgbdLEIecE7XdI0MpXP5T255D066q86jJcokMRcr+vdJr/SJsBMSPUhz7K9HrKGCPNV8E+e6i3dMQWg5bBBeo16osj+r8bBgCC8d1yxr74ph835UcicfkMXFELIPD9nRFpR+I6xa0wCSEj5Rb8+HwnpkC7QYx3uhny5lKg/tYdOpypHHdwp2ioZyo30Aq7Eu62a1ekRTKH9cegw/STkMXoF4H9ngv30sdxrkctla3fNsnBtxZ3QFkZ6RLcnmM+Cc93BS646wTVTO/OoqoKZ2/MsaHl+M6Bh+k41XOwli/xKCy7DMOmBuMG3F6Mq1xkHsiWRaHj2MthNL+LgPgmX6Atp6LDBEk72tHAP8EvTGjNApi/sPvnDxIJHb4plaFm7EZF1dga/eduGo2LgKhCGL7Eqw4DoOLOeARVTi5fGr3qUiGcebIkUUxKo7nunRmM07goceKKp3RWFd+5DpTzF1+ASSsPEE22D+XthaY8iS9ZqL7Np0B9lkb8aQN4ZXAtX8xHEXFqj5hSwZ+X/6HrU1FkoyJCwW
    ZENML_STORE_PASSWORD: AgCr7I4GIRxMmz95xv2f02ZujCH1y4b1OU2xF6eVHtdoy26hZRwOP5fgc8KjhRiaKlmjz3/ehu44dIWTetGgRs+VqPJ2N+Px55xPmtsvQxzSvevWyzGspM61SJxa/IbLbfTkkVvCjos9cjmGXNhJ5HEWkIuZohQJlPuRq0LPNfh/6wvKX1QIAgdki/tuRIMuDaQzAG5/ccutLn/dMz9wNFnn15wHXuGr7V+aPEY3TNObjkOJD4sICzYf4WKdujoJ1RDDKxddt8RK4gm6j5oKfe2e9/1K0nAC3VrsC7K5yFDnE3L8rd3klMh8Y7MAebCzKceM0dFqYkKnZhglVnLojgleaxkQH1Oz3Cy2ZxyZ17bKfABmXEqBOHzClHXJXDbrEU48dixZ+BhZafGJWzICti6iptJF27JAeCvQXIinkPmUTy1GHnkbsND1BPcrdJivMzcVjW2mw5BESlzv/xN6G5eGYin/np0cnaUZpZCmGHHpsw+NYk9XfDS4yXQu7rvuQb1QKsM1pwzAPf0xHF30UcTgEzrKesolZcKP/PS2W/kvVYSAfJNGUgThIxWKW7e43akpIjKQrBX+ibjLxY82nfUNqMe2G+7pHOmsoTOdQ5cZlPbQZ9z6SXtgmnl4K/Ilo0rHRgFsUJy+GCr0HAebg0t7iGLv24RXjNqzgYWdWuGLFrYhyVReY1FpoLN4grTSVF5W403e6BAZ28jhhnzrg9wp77W7mgIMvCQ/o301AJPfYg==
  template:
    metadata:
      name: zenml-extra-secret-env
      namespace: fair-prod
    type: Opaque
