---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: fair-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCQVLhTH61oSulN1N3zZrfbSOQEHbWtZzKYbo4gUnE4nf3jpcecylEAFpKn6zRPiKBcgxVRXAieJO5aeALCqJHNwh/z+Yc6HdMp/v3MZ5Z+V9TS42kLDY7arek/XFSTpxXzUTdZ0qU6Lrlq7krXiE82KUoO1bxqrH4wV+iBY3ympLp5a47v5FMg4E9yVL6ed3X6sSRzOwUyzFZUT0cEhy6GQvO/ioW/nIJf77gxoV32cNuxQ28piZ+8dT+EtuDJLHqk36cLM0HlIKRxGBuwT50K4jCqmcTqShz3GrrvWOf0ua2sR9YqTTF8xhJBq6CUiaiKNp3/4llrx3YO/wi1lG+7ZLc4I08WTeuC3Bmzg9ex2nI9PPkrjqo7ZBc9/3vJ2bfC8762qvk+ivc8tUhYf/7eZPbBIHbe5aqcHGRpYkgo/DtrF2VhZthAJ9LGkQ2vWZbyThDZmqftA+LfoJhLMAttdc8LV9sTnJdBrfFaYtkpnh2iX7udEICxJAkJyBXKrYlbpB1vnxEk9oWL+W3p7TuWWGRUD+JzTvJU3BuQ6zaglu6x67AEuGVPb+9x/uB2Opa7XR9cEOvmEP+4PXz2e4yhs3J6fnwVP/X8kAGB8ZcHwWZotNEYE3BOCzMfRDZQ9PBD/MM0Jzf3FPMd+8AsV1j8W1TG0+Ua0UE5NZlUuoawWSLIMyPOBgxRhot6iX6kD/tGtaafOn9qW7rEORzM1hiG4ueHMubrMq9I9krnLFdlzezSQvbM5gT+sOrXW4qUExQs5SQvKoXFCMqW1uvJZEx6oSqwTTt6qsmA3OrIiBXvaaplKbwKcEBFbKUEvH0ND8ZoyIkXRTNwNfg5VszTJoVvXQnniYwSdCKzOXX3+YXomwUSVLBBqhJYr0KtMw7nro+x8B9yrONbDmh/n5R0kGNVV2JRRgiBWA4h9kKs06vowKDLzNqS8Chfb64BfAK9cbu6BhNVUFNexsgJ
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: fair-prod
    type: kubernetes.io/dockerconfigjson
