ingress:
  annotations:
    # increase the max body size to 100MB
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/enable-access-log: "true"


postgrescluster:
  # # TODO: bridge alternatives for TF output to CRD annotations
  # metadata:
  #   annotations:
  #     eks.amazonaws.com/role-arn: ""
  backupsEnabled: true
  s3:
    bucket: "pgstac-backup"
    endpoint: "s3.us-east-1.amazonaws.com"
    region: "us-east-1"
    keyType: "web-id"
  instances:
  - name: eoapi
    replicas: 1
    dataVolumeClaimSpec:
      # TODO: gp3 SC
      storageClassName: "gp2"
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "10Gi"
          cpu: "1024m"
          memory: "3048Mi"

pgstacBootstrap:
  image:
    name: ghcr.io/stac-utils/pgstac-pypgstac
    tag: v0.9.6
