# Cloud Native PG (Postgres Operator)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg
  namespace: argocd
  # Required by CNPG
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnativepg
  source:
    repoURL: 'https://github.com/hotosm/k8s-infra.git'
    path: 'apps/cloudnativepg'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      # Required by CNPG
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
