# apps/kube-ops-view.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-ops-view
  namespace: argocd
spec:
  project: default
  sources:
    # Source 1: The upstream Helm Chart
    - repoURL: https://charts.christianhuth.de
      chart: kube-ops-view
      targetRevision: 8.3.3
      helm:
        releaseName: kube-ops-view
        valueFiles:
          - $k8s-infra/apps/kube-ops-view/helm/values.yaml

    # Source 2: Your k8s-infra repository containing the values file above
    - repoURL: https://github.com/hotosm/k8s-infra.git
      targetRevision: HEAD
      ref: k8s-infra

  destination:
    server: https://kubernetes.default.svc
    # ArgoCD will automatically create this namespace
    namespace: kube-ops-view
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true