apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: login
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hotosm/k8s-infra.git'
    path: 'apps/login'
    # targetRevision: HEAD
    # FIXME temp until debugging complete
    targetRevision: add-login-service
  destination:
    server: https://kubernetes.default.svc
    namespace: login
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
