apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oam-global-tms
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/hotosm/charts/openaerialmap/global-tms
      chart: global-tms
      targetRevision: 0.2.8
      helm:
        releaseName: global-tms
        # Use the default values
    # global-mosaic CronJob generates the PMTiles layer that global-tms serves
    - repoURL: 'https://github.com/hotosm/k8s-infra'
      targetRevision: main
      path: apps/oam-global-tms
  destination:
    server: https://kubernetes.default.svc
    namespace: eoapi
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
