apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oam-tilepack-api
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/hotosm/charts/openaerialmap/tilepack-api
      chart: tilepack-api
      targetRevision: 0.4.2
      helm:
        releaseName: tilepack-api
        # Use the default values
  destination:
    server: https://kubernetes.default.svc
    namespace: eoapi
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
