apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
      service-type: ClusterIP
  config:
    # KnativeServing has one cluster-wide domain configuration.
    domain:
      "predict.ai.hotosm.org": ""
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
      domain-template: "{{.Name}}.{{.Domain}}"
  # Keep traffic available during single-node drains.
  deployments:
    - name: activator
      replicas: 2
    - name: webhook
      replicas: 2
    - name: 3scale-kourier-gateway
      replicas: 2
  # Permit one replica disruption at a time.
  podDisruptionBudgets:
    - name: activator-pdb
      minAvailable: 1
    - name: webhook-pdb
      minAvailable: 1
    - name: 3scale-kourier-gateway-pdb
      minAvailable: 1
