---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-s3-creds
  namespace: mlflow-prod
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB/EoSdOxUYUtbxodGxB0RipYmBm7wpVb58jLIDFnyurZxf+yelFIFLkTgx9KcPDw4zESKTW5qP1S5Zbcg4+E6/CjIJAK7G2ylRnwFr7l9ccQ3AVKNiyq4RCdQPNCAmuGyFI3l4vNAFlNHsKGWa2ILBSwrI0w3vLqylo5AQrRm1i7oYTC+bEHXoBlMU4ljK8XGWWWbEeqkX0+pkLLM/vU8h/HIQ3U5qpXHPsKU57F1rrZdWXbvK/6a2Xl22xqJNqxx3R3Y96qTqHL/JDBe7QwqpwHnSEMyHqQmpktYWkiWnxibNSTpcDLYWMVeNv/2h/n6mu9jCNel1ue6IN68TNBR82kb96KCYutx0c6qABjccXmEHxFAizSCvoDAoZemWlTLoTqH9vezZYTPZZLVZuJxDUMFG01+emuy2Hn1gyzm5eefNnxdJ+YWasACqP9A4oFgzsE5BBJOFpS/Vejn205EbiFj3MfcG12PWWQHgsop4BubvB68eQqdiygjJI0ce62dpFUe+4i3ey7IBuwyJcCYm0Nn28kmYx6XNyZOQ3JvauRc5mUAL/GCzvvO4a34UPA43MfNYZxVfqxy0JNEtOnDEcG50oXxQBDn4/c/54A40rQv1Vhh1Pp2gnbS+lLqROgi8MGG8ge6mq3Im2Lat96NmDaBBsoMv4UPeRnRUKajFsMT3so54XP7H+Q4CS3/6st7RTv4tOqin2u+24I7Fv7By7QX3WA==
    AWS_SECRET_ACCESS_KEY: AgCVOSA6SYy4BAiPIEvGgCgIRVnD3jFLDOaEGJEduAoATFZb2wuR4KA/w88xX2tElhVb5Rf/uNjMDuW7XnH1V21Cl/gWv9VZPax1WlO1y+NuTPjZmIkDKTSDiSniJ7ktRA/dpJymOG2VL4D0MJS7BC9ugGH4+WgCS3/UGE4fK/4SwvGs3wSXNRK6FB4YELfagRpLPRRHpiC68g4tWrrZTSoZ/71RqX39HWQaKeIG9ranh76MuVifv6x/BeCrYuQAyJRY8fKXnfJEjCOzrD6xdDy5NuxJz0MQBashdiYmVwU65sQ0GOPDeaZ1hHYqUhvfzUyNp902YcvAsaM2wWVu56sLfcY3YIuDpjgzgD70df8znKNliK9yLMoq9Nr/GGgMCERvY5boONy6qNs9SieDSROFoM7sP4ELYuujjFC+eY+V+yaYRyYOOwTybBBEBDEiXy/vfm8InCe9oD4wK/sLWpm/kInJZ8mifxFxm1LysP6+e6d9g5rjX6gYXE0pd+HkLddsRDpXFBYKl6hpeDuh1Y05ufFVaeTm2qlHto/+BtyLy/QdV/PEwW+6x2lygXRXcSeMc0dSYgaVDjMzCL8KldhoHo6c4gwa/uTAsZ82h3tYJ8ceIJCPPjVrmuHTLMcZZ9iVuTGE3GWFpsSvI16RDO+A9SVP+etD4P3UG/7I/YPbzdQgZHj1AECcDGD+tt11bcAoZsesIeRy7pdxnjUzLBI+omaD5OkPzaNShQaRtkCJa8l2xzrttXDz
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-s3-creds
      namespace: mlflow-prod
