---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-prod-db-creds
  namespace: mlflow-prod
spec:
  encryptedData:
    password: AgBBHhfgPXJmyPyaTlWSXOGQLzikK6h/bvKXSnQvF3ISRqdpI05m++ImE4lCXqiNiABUKmYKubq8zLByL8ayWNF+8IiLZI2y8+rmShLBuXk0cSSpOy+pdqym3CfAZE1GADszFHXzHx/f3jBPtWNWh/aArg19Oohi98X1zcrVshCZhzwi9EwDllongISM5mEL1WcRw24ERQcxlnfvwoce7dVtqx2vDpDWo8/lyftnZuREPh6NuPXbUGagQvVhduS4oPQuJVl+HF9KzpHhcAV3gj/QcrSYUUUkk5bRquRTd705NcHbGd4HCoZSqQ6m7yC+GEq+rvfZdMokVWLQGwEVeHRdA6d31QjgnsFNjuK2A3a5RoHQIwTlwRI+7cAKzsMCC42TdQLxpwe6EO0iPQ47a4xYJYaSkteB4eAfTPFukmxTdTUqFhZK4tngpMwEGc9arJ32GZD/QM/bZvnBHXcfOz7sVDkpnVG/MeqXBoiQnC+KRQVMlWjbRFGMgRxVMG9+OdDaBCx1wIlZtvc+nGPsydJs5iPjasr2pFm+afgBnJjj33NaHTp/TFeN/lnhH8bSCmb5dKSUNQxxScsptNsdQkrmLSUt8HyBtPVscg3i8kz9W0NAqB9zwSLfOjAlS+rAcg3SOpXAVWNykrJwe9F3f0ErogQ8JyK/54xZqb+Petg9J9vGVOTmdtDkj5bBK/zcXTy0Q4oPgUwuxGKopipoRwG/H09hliO8+MplnP4rloRTew==
    username: AgB04M1UwjdjIWOaDftBu6Ko7DuT6l3uU+NK3cm0v6Fh+TnS19acBtZ4X3R5sZybng3YfIcIZ7ZaSC/0OzaaNLiYQqRVShOV8BSZ8rhfBe9KhKCWjvT3gLtFyNrSnNs7bzgOwc7rsEsnlvq1ZQmpqUKrKF4ajWwRAXEjjbVwXuTknbj0tyGglxpGsAoC5+25AQ93Cs/0j69KcEsTdexafZjvrXVSp22BsqhvsqNBWfoXyWRbhMzFU83F1XQ+eDk6tdhU2iXREG1XVjcQWv8k4eDAlr2PNNtcz5bJPcBnnkXVk+LGfqCmeIjA4wGM9Bk4pE7nhQbtChFt8awQB+fr/dlgzr4Yy4hw01ym91OV7zHdtHiEl+J2fIq1FZXSYuvATtENLZCbmIOvQv3jFaPaLdCKBFunY2jEewnWoutvdZGdvuS8xDufN+d4KBdxNaBlDmoP1l3ZqjBxPbTqNb4ZtQfdHLwqAiGMC9IjTYmMLEfOOB0dQ4+NVz7DUj/Vy8Eeu6eIutRVb9CrW8gJ2fTKlxUGM0GOea3L5jSEG2EzJHA10Dox96nyRJ/aHbExvlH+NJiUcOxhP6Lg1mRguxJILEEAqpTiRAq+zhYx4Na5ArEjQIu1JqheDLzl30y0PrT3i4Pi0RWRppsAfoPOZb/Jh8KJkamoKquK76l4O3EA/Qyvy82oIAA9ik7kxbzeSmvjDk4yTqWBVDg=
  template:
    metadata:
      name: mlflow-prod-db-creds
      namespace: mlflow-prod
