---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-ops-view-basic-auth
  namespace: kube-ops-view
spec:
  encryptedData:
    auth: AgC9r6z5+fVwaDDKfNwS7XmDanRHpPTJQNFHB73IPLIw6fgD2yMjpdNuKnXdfwgxzE94naCGk001AqcYOodwnz5PqejZzO+Ltiz3jw86OIPCFySrfW4pluGc99Zn4FP+YThQS2UNLls3jFuWc+5n6OpPH2wTDPCDm8RZo3VUbBfKFkQMGvAHhY0MQVzjKVyIQvfjpmmi6Kdz5X0+yR1UprKGryGmwBb4eXfL+9i6T0bMcjvOpirxKtIfxRT8kCsZmJ3nTyrR/lLSGSQkT7byGH3PpBp+gFNgi0+wE540kqEC15jNOWyzNjOdELzKRXPY/mtcYzAjqkQNERmETtcAqXyzryCytXS0GJ2zRCKghonOnF7/sbeC9MWDsys9c9Tg1Jiu5qHjIPLkI/EQepVIFJC4ppm+vtS6+dKHECt3nHog+RWP/A2MtzkGZiQb1vBXWR5BEthQCdE2mXcLYlNXnUZpQK0qOS09Pf8K7Jw8I4SMmb4911Vf8pD4c+bLfAQlE/4q3AhXGbwrijbCgo5+mZzpRnDpOK7PKBdZqTh/DpONTz1T80/FgWfIin8gyu7k9k+Eq3uBCUH8LKt2zNCvatgWynnLb92EGXXv/NRkWDCTUt7seshqWJl3OtxEZDujt4jYIuPR9o9SbNRqxMH9ie4XYk7zZ3WN8D2twp/meAqxngdvCy4PJelIm7WWwQUR/mKPHtNbotFfxnrYN77tGzH4P47vyBGHw9B3na6zp1aCG8kjS4YFisRyPFD0/cMb4rbFM4Fo7S8B737GWWB6BP7DBR8=
  template:
    metadata:
      name: kube-ops-view-basic-auth
      namespace: kube-ops-view
