---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-ops-view-basic-auth
  namespace: kube-ops-view
spec:
  encryptedData:
    auth: AgCgrCRqii7cRJlUBO//oQggwkM1cohK0jT+p7/3AgqkWy5QcQkl7OE61EUaDm401BeOhbv0wZ/vofeftPLAs3OIt20RzPZxAkgxXIOKNAnRsQU4UAdodYG1Lf6P2A7d8OXV5w3ZMs6CPXJsueTKDrdUmI8J+73Szuqcz8dx56d42XbaAMBF9uAaIDxXjUSN2mwGUHBDJDm5P39ZLtAfyXV8T37blQSRhI+PPlqfq4xjVphY+YnBa+j0J06/DJwgwnWDpmRw7XtTTYUH5XL4/x5HG7XXVmpOKaZnwaomUTOmexp26Ua8kwquDahKTh7CJVsSSrZ9Ei/qsufM2mcYC+5LBG4HXLxhK65Ua7RijzPV2DqfB2RkaSyYy/OfFEuxN5hK0XBzIkhSrf/MNrxCGJQX8ZOIZqcCOGbgKRORvLOv3u2by/R1LgwnYarZ0NgakdAcbYXVWTDCP21BSrt38VI6HhSEXm3f2CC4088OKUJv/6LM+YLJkm8ulP0MRJ1W+QmWZDxN+QPmTLy92WAR+Bb5oCJNJ6eF47s+aa6omcveI1JWgza+wT9HE8sC4zCZw2iwJtxYTySeO/VDenQnF+Sthb2p9ShnY8pRbgF51Vkg6hL5PVqeidrSQ4VDbsnxkqrsKrg1rMG787DSfbvgvxUmXmoRkrLm+ALzOC83L3l7NIddTzavmAb/B9Lpcbwatq+vQK7V39lEdNBFKSY2FL0HY8MJp5cJSJ7ywDjbzpy3ViipYJOelj+C69KZSj83zYalMDcPqz2KaeO0Kv/xtKeFpro=
  template:
    metadata:
      name: kube-ops-view-basic-auth
      namespace: kube-ops-view
