apiVersion: v1
kind: Service
metadata:
  name: kube-ops-view
  namespace: default
  annotations:
    # Forces a clean MagicDNS name on your Tailnet
    tailscale.com/hostname: "kube-ops-view"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    # This must match the labels in your deployment.yaml
    app: kube-ops-view
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080