apiVersion: v1
kind: Service
metadata:
  name: kube-ops-view
  namespace: default
  labels:
    app: kube-ops-view
spec:
  selector:
    app: kube-ops-view
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP