---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: xlsforms-s3-creds
  namespace: field
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCViy4ChX1QirBrUk61WKhU0RKdbT+nGBwXJJLmHf9BnUOecq/x6rW00dfKf40C899tiIZ7+x1pMjAcwDshs/P938HbyJPFVUWqf8xUvAcEC+y6OV8wd2cVi/1FwPoc7TJbdPSJWxZA+2p1A8UjR9NlIoIq7/ium5iPReMKNfH3QG8BJkVJcARs778RjcMUWmui5sPaSEH5MDqtGeV+7gyLBkDaulwipRu/YzYWP0+W6lREDo8QacLw2dRtWtOO+/k/2NlC0TVOMu8ZmmtkP5jf0pZMj9jQeIv1A+xIBhWbRxETCFqckszdYeh3Cy8RDfUTXiaXT63NKdFdHipOflg9bwvNjXTEgIidBzLF/lmupwTLTt0RK81cg75wNKOQdI4zQV3pwdzQJ86LDGg0IqGV8+YuJQQeHdDELiLxJij2aEyaViT1v2W6XmCX7JNgPopou9hcw7HJqLHZ4vczY0UYtteM8T9x6Azo0Khyewib+bopP9CkDcDgDA5QCsgndiDJeFpINp4WMuBqsMj4/SQbindx/JlbY5Jr3xj8V8Jtlxlula34vPVx8rU/eT9DGXKw9TTKOhwRxJAGYgtxXAouUqciqn+dAlQxysV02Mh65MekhxDGjmXZqKKz2bi/tULnMYXxXeIvMTk/0LsMAGE18Iq9mcJ1sbYwYOEKlXnvGfxd7sCglpRELX7nSnU2mu+TF6+Q/lIMz4vX9NfS7rfnw1DOQw==
    AWS_SECRET_ACCESS_KEY: AgBZn+4wvT0ix6TxmLrgOBF4fMjjpj+MDl9D5YHHx4wVeBOZiLXyooV1cS8xX+dlDKkzZzJS5UWfW4jZOJ1v04pkvyjsMgk5PEtdg690vDzoodWxJ4mU5X1q/ToEYPd23EtM/3fY4C/LNKEFPKqYlVh7R2O6+0XF5R5lEVGdhAJxgY2CUHdfP3RY/1VuTajwE2q9QptXyLF/4pdf/59a+E0rP44PN4y5Ly2et5vHlAQNVgI40N/GuOl7fM6ySjnZGN88lnasssrTCSkJyVQ/NU+bci8OLdK6M+IIq3RrY/JMOkMnwEsQOt3PfrlNVfzgL6rjLtgwLcKPExeFsQfEPOtCFKRsxeHdQjojGV0VCTahjZuRQoWDN6yOLNi33URMz4gnXZYTh2fIUptBZYeAXES0IN5TCBDb36ErlkZOV8f3R317T8ToNygwejbfPwWO4PUzON8i8lQ6vo1d/eXtjzq1sZ4DQbJ1/bXKbarA3kTMq/l3RqqZgFyeGxPMb4Kscljz83nOSUnemZP6R6UpT8VKVeAQMAN/0ACK498hDafNczgXwb3aU2/m+oW1/MIS0OCOQT4YdfD6iBYvaxc5dJqXtW/LL8sxSoznnaXgTCZAFefnYYc9XvZ1xV9k9OSFgEhOIO7p4MnxloEEOpp93LvZDV7YwGBlqLsPbHhuKMOPMEoTeNarvopPtIws2hY3ymfiBgKmqtUYcsRpPmeMvh8brc+Xab/L/nKZ8ulC4dNC2mPzdaK0oTkg
  template:
    metadata:
      creationTimestamp: null
      name: xlsforms-s3-creds
      namespace: field
