---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubeview-basic-auth
  namespace: kubeview
spec:
  encryptedData:
    auth: AgAjrlLEAmMCOQ0paR4QeeDapgKgMLKR6GlJNPxAy3f6s+zzxha66w84Al0aaLgMsfgxoUjUsmx3filds60Ujj7HT1FBORteac+Gxji581a4gp7pnio70dUuP8ryoa6RqS+zczQLDn2/bEPp3iRQGITk4stvt0+6aQLHFkzqLyicYEOGNm9/9ToBsAK03NfrcCZBvrDUJ3BQR57/capajenCWA1q6P2lUkVyEQ2zpB/6saxtDNQtkYMlAPwV8CH43HsAF2jy2pj8wCaFp40CLJhVlGYAqsqNBRKIE3F0dKBq4+jTzxeEbWMmsSpGp10uIwXrq0mM/WjWAvIHXYmyMxXIhTqIISgQx8eGVNS3dARyplG6BHlWI0Y9xRet6JFheSrLFZIIhlVqA5an44ZsCuG8it4E8FzJeH3B6Uz3NkgSPXJn44816bpl+e2x7nK1ozwmUOF3+dSG5WncAGt3XAn2XjT2zZHJoTs9sa0c+wV9tuqJ73mh6NxxUju7gX0sS5iB78O/RV7G7oi+8PM3tPOBUy9w7UwGuqISDfwFDvEZrQ+eJVU6wRGubUiE6zbXQtn9Av07oLrwniD+TbXCF7ejpqgRqdVJk9HRRrajn1hMAJTzY+OZwacjuaUjRnyaLJmvEaCeqDnrtjRlw90xxgWpSn/25+P94AI2cW31Sn1NxldrZJoWwgsAVYrA2tOCqigURX00J+E51nFug27o/qpKMUe+p9Ibrb3pYcdYcusJ8zm2BZzhCmg9n7gbcvuPE9jtPLB1aN1TDHpN2ihOCV+85Pk=
  template:
    metadata:
      name: kubeview-basic-auth
      namespace: kubeview
