environment: develop

# The CI pipeline will automatically update these tags for all 4 models
models:
  dinov3s_buildings:
    image: ghcr.io/hotosm/dinov3s-inference
    tag: "latest"
  resnet18_classification:
    image: ghcr.io/hotosm/resnet18-inference
    tag: "latest"
  unet_segmentation:
    image: ghcr.io/hotosm/unet-inference
    tag: "latest"
  yolo11n_detection:
    image: ghcr.io/hotosm/yolo11n-inference
    tag: "latest"

stac:
  # Skip STAC registration on develop
  register: false