environment: develop

knative:
  minScale: "0"
  maxScale: "3"
  
stac:
  # This explicitly tells Helm NOT to run the registration job
  register: false
  # You can put your dev URL here, or leave it out entirely since we are skipping
  apiUrl: "https://stac-dev.ai.hotosm.org" 

models:
  dinov3s_buildings:
    image: ghcr.io/hotosm/dinov3s-inference
    tag: "latest"
  resnet18_classification:
    image: ghcr.io/hotosm/resnet18-inference
    tag: "latest"
  unet_segmentation:
    image: ghcr.io/hotosm/unet-inference
    tag: "latest"
  yolo11n_detection:
    image: ghcr.io/hotosm/yolo11n-inference
    tag: "latest"