---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCdyAOIq9oOz3UB3f6Sj8p99l63AdXV7fj0vWi8PKPOkOdU5gFA65meDfIGH124fwph6ZAxph1vfjXReMrplSv4NSpTDAY3A364gYlu4uH3zNtEMa3Y8WtvLc28sOr3AweSKe+x36j+p1S3sWvCEompv1srDtGu2BuagVLjHuhYJ7VeU3boGnLr8xYz1vuD/EJFtK6HdbrlrMMWoYqLZMOxikGk+TusE7Ior7DPaZD46RwdfPmeGl1UjNWeHxOi3J+DJPqj7AWp2RB9Vx/ks2ZaBO8z35Hmsm/8SmoySuOuQ0tDv+H+UzLGhHCFAFakoO5cMBUDDV1oQhHAyp9agcYsSjpeMotnicCLS1D8/CGhpgiSHwAqXWNfPC0nxKYBwWZOQcvsoV+70HWsTzwg+lMXaqgusBGwaZaqKc3MnArNr2pqpOurCiLAlJKxA1LpqZNfTf2wCkacwiZdrE2OdtrFIsGQKsLMq7xsYOdfNO99d//IlHbh/wP50dpG/z1CRyFIA1Ggb4ADwiFEfzDU1MDNcYhNpcfytqsFT31Z8TaAj/skz3SKXN8hGucLcgiY+E+jMG/iH2Bv2uo3MQYp3wsVWUbxYY3W/VRyU7Z+aY73EKywX4+nzsgzVDGmZDouT9W1AxhdvKMTGQh5CySUz8DJV0hryyREuCJw2zb8Uhjn6yqZ0Dq2atKgeSj2zU9pxnzme0k1LyP0/YNbhZUl0QlQuw==
    client_secret: AgB0d/byK74VrfQ+UXhEvDhwAaeJdUL0Jo5Y0wn4queqfGhFea6e7iCd0shWqbD1NGxUrlGtMbK32zBH3HKT039q9BKolRwZ+Erb/nJdjDBKZb4FfRyerGfvwkALtP+AEX0vAqub37OfTQ+ICNh7svvYC7SK6HceK7VVVk+rat87LzpJMzFGSBHCWF+NWGZlWDVPbqyM5P809d28nH4CWF5bIBWygGWPqIBdkkClLt42XWo1Z0VL7VaLZNEYQpookaj6u4/6lfxkcqZsZW9+8zxparEJ6zOGBCJ8thv04xbE6Dw31K6NT+8fbNXc/Kpips0vrdhGCnaM4ucJkiokM/pwaCV9nNkmGiNWfoqf2XfBX6AZFEv3wQ8O3EmbQOD+Q+d6uu9WatyH6uO+iXYB4FRwCb0tloHNH+8I8crHmlIJqWz+rTJseRmzV4zK3bLjNjgYwtIW+uw5ePMI/eIi2Oa6JNU/qmpzcidymGmFXEUqpgKWZzamRnKLO/CkY+2XjeZbeGryn89iEMq7HzKXaywdg7Py1BJKti/DSOuKtPzMfAHz1E7HHneMWkSb/Eb5byf66jDN9zOBiQbk0WbNsDCcW7wsVe+S9pZcPmz2aCQI053PLv4qsU31jXpz4/fmYqXEGp3Esehn4AEzK3I6WrO9fFyjBhs1sliM7XgRWjDtjUPJcqlyMensrDxoD+3W3VWkQh0J2MdAbAeqV9wXdJULjvuVfERChvDODOGOhZ1vKwEJgPxdv8T/+qcOTb+URypYntLvMJCidBGRBM/GZ117
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
