---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBl2htfOZHhlIopxOjidbIs5ecLO3Jt+wUOHskgMXnZO24ZOz2S9LsPYw+WEyhto+eLypJd5OPM2RzGkWQtydjYc7JAxoZfOrqYYzOqEXhsop6nszbeNgovrcgePjOTRflbX1QIJJfEtQehryQBAMrrijM48pClWbCknHPTm0oySI4YeN1qHB+AAh8Jz8QxHZOcmdOPxdNZSe+lY99DQrGxq4T++Yhi+ae3LwGA/g43bFbd0WJqZFvN8JBLhP1Tqp/3PlljrWAkfW8GqF3iotL81j/2wYGsRq5OuMdt2vMBEgQ23sJZgtbgTAdY9vtDp/soIi5j6QAUOxztXdHDig31dzEgsKyelFn/pQodZYh0GiJa6gdD6n3539igXXYoetGlptxyo/QrLo4n1dgiTVcl3CJJsAsXABbT7TOk33NkDC6YhrqUD2XHHHBa9nqQOcEw7oqT5zRgOzHF7g4oAjObX25dY4siYIgstGuaugd7Uf0nIJmNbYTUwSL2HwqpEm02mGpKq7o2zlFLavTsSR0zpXVzfk9Cb1YqwXWyFGYwBXR0Zkig75Hk+gstMBJfF4DJ98XTNKJpXDU+4IJWlNuPDOjogZtT601ozVxZcwsvkM5VFajs76/IOIPwcOMBkurgI8UF5gdfSrofPuaQRrIpYzKyFUVIUrSusP3kSmC0S86H3SW/8sv3vMTMxjv5uhzttx5GB8o7NKL7mn0mtVwXCQ==
    client_secret: AgAUld5+VOzoGI9ZmOm7SjDpV+YZGxTQRG3F9nD+/HEjl2AMhHFpKJXe+YgvUEMo8WTdXHFmWZiERpKLvVgXxinx2cHw8Xyf2oxd8/oA2kdi7/iD05IvaE96YnJOgBKzQ30psqSWDo99Nn9N/74pI3/4PPo+qjH6p3F80rRJO0XRdztDM388OS5vL5jdBhp1FhksTryTfbCDJD7SuA01f+Pgx7+RbSNmtOJ2EMK0eyPx6/D2bOdBlow+cjg1T8yesENX+nVp1ZymvvMVM1+9dIFhW+3p2q5fC3RJZvnGtVx0MrwZBf9jiWxlTcKTzTx4bzu6pl/9SyDpCsyu8GovCa1WUHw/kSNBzaoqDwL08m/kgBljBSi86FuJGkfrA/mfHCT2J9LsVRQzYhmK0t9ZtEm3Uq/ztqXOY5L0Ev8R3Au4itVg4C+5RYnZbklhY4BqbNenmn6FSFyhaTLe5ukzLvfN3JZzvYp5Ft/JcviyMex+j9o1fpfdfjA+okwWYWqof6iuwaHahhBNddIWNvoCLyoSmBcdPKtyMgpZUNWetpSnxAWO/nkuR1IgIJ4XijwI4eRMw4wcEl4Mw+eT+PFTwyZWPgOSa6Sj+6chDB1yRXLQyWC2765fqrGAHtCVtYYiUaRXaa6pXMnDTSPi+WFU7bwH1rfOhvAGhu78/IrE6BzcJE/MoamQpqDRHerN8x0PFQmUU6AkEQqiBg4VW01dhgVlDpQ75IXYdIxmXDtMkBnDns59ORL7unAnfH8b8NXLDfew3ilfnRTm57gRZcsHroh2
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
