---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-prod-db-creds
  namespace: mlflow-prod
spec:
  encryptedData:
    password: AgBrlsHhZfpBhVhce8EZnbAt2QZRNZ+vxQ9wzYKGd5aQk0Ttc2YufhiB4YWL3h1/iL4XqkvBE1t2sahG4lnbH/WOGhbQ5AiIjU+woPQDhD9X7H9RVM2/Bin6v06OC0atsF9+lNbcqZmKoxciNKido3poqYxS7oxQsx+7lS8AIQNFsM+C3FfLjxV3vBqyZo3Up6mHO1WkZmutQTiFQ2NFhudNfpIF04ExCffpzO2mXBTqQfmwhnoCecDkSaP3Qy+IamwzUnHZA5tvkfOZa+AH4q4MaQMqQhku2gbXCMMdyUhgOPi1OWyzNZgB+iLxgxajWm9O+tWZmo+vxCHPDhw8UYIlSx2yKyaH1RphMZKsiw7u/pG4PiVzfQf6h46ZrU69w7HK5DHPvY07ikqJsIIXcCnn71BgIgWPwxNasx/1is3gC/GGoP559DwEYAaFWImdJm20BeRm2/Y/VZgKUyGq62YXeWewkjpOslRB+USlZq3hKa2Eal/ph8j3XIxYpoUE6zYN9sHEhMCKINBoOfd7EtJdMabbphX570oEwPjTwLhkQJ0vUz+TVHCDSrPtPjl+r4kYzYjI+p/BXaK+yL+IeWTa9lbYmSIyCGdcgEzVfwDucyi8tXTMcvPaj39Lx3Mzj3oes99mv5VJ8wmspC8EZ9S58yRTz9qfBCTlqRMS2OrXolCvgzUpaMzqzcQach98KLGmhNxAWd6lhtM+SBBUGCDaO6UveJgNBA4v4x54XA15xQ==
    username: AgCykYCfHSbQqTR0gO9TzA4qFJsxzhMZ716KvKd74v/T6ptADhboSsOBrPsP3R36hpBhyBmhH6ssmIo2Ab+RG/jtXObYtO3BpLBVfkg6Tz3xqp/NHipax7Db4rzOmpNePCq+57SqgWqAEUgfOjfSzMdwwFkfmFewaOFnsh7kTFUgbNkh19gGfNnkaog2l+OCrSp7qg7I9XFrLC00zVSeMuJRpArle7J6zxi/td0IOfOJpqZC5Nua98PBXfDaXfW4B4nMQQGyFOyr97yUsEBc8eh8pI2uBewHZFKTrC34MTX9ISBSZrBHA2u1EPeuSkSoKfSy7ic8eYOGSArtu/DKGyY+o9lWHOFD3QgvbnH5ItJZnznfhugPgdVW7++iSs6mgI2CszVyzECEa0tyQyc7YbiUWlP8lsGFmVSYXSc2bN0lIfcyuFnMl2lkq+f9HbLanzccugmk0Xc/hznjamFpY2Xxikc1oeoXICPeSdAX9WmKthBaTRhpUr89RlBKYI63eQj+OpfUFOeWvXvVu9TP566Waf6PqoGnCAlsh2xbRR+YT/ycecWQ6qQmthgleJ0cm3gzZpUqnpP3Sv2vcggJJX1DOQZP5QIrsTEjQ1i7+r4CHeFpyhfNL26Fyd2Tbr7aM4QngNcUSuDku9ZR4xZ0zgK3c+7iTCWIe2HlT1Tu6c5d3oqPC27Zc9Kvlot24YZ+7tbCpqi8UhGRjiu3jIywF85b9kgNvw==
  template:
    metadata:
      name: mlflow-prod-db-creds
      namespace: mlflow-prod
