---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-prod-db-creds
  namespace: mlflow-prod
spec:
  encryptedData:
    password: AgCqjss6Xb2HVI79lGhYiSXrJ8BzhPQ60SWCnIFowRgXU/5bOuDqX2DE9VU4VU5huOv6l58b01nMbqAbgaWnvmHDDnqKvqMsCUGhoCCMpX7XQi92Q5XDNYjIOwEvg34Bj7bINnNBL78YpXxYzcZ/KIw+oFp0mh124XtLeo1fHtRRhRQKyQSBN3y+vyQ5gfzDOO7Hw1ixMJiq8VdaO+EtAZ73B6I8cuQL4rTGu7G7lIFvzmxrK19Xid4K5We+tVpIJAtnpz7IFdWVAAy6V8BpuWuTSr9ZHeIADcm2zWkGMnnnmZZbNf4gQCozz2X3h3B31PUeVsmcuRwbkG3XELWAgPsPrgbDFpPByyDGy3YPYGBj/cBKJtt5ZImmlSNPPqNZXKkWNlouNDzpVQddgpC79+iadgxUqsUy0JuYP5UbhXOK0dpHOz2CfVHK+UIBlJlRFDviqbpQOIKCelhQW5ypmpoiW3Zh05zACwdt7f7vjc1ctY/okz1FOwU1+WLrKA63qWwIz5K/XVm9bGeUQDLI0gInp4TgA1x+185V3AjBuIDjEGmtVHnAVUU5NvSrjnddaYOntkAeiLYjyiryGPjkEMmL1I5ThjeS+9fdT35m2QsvE2et4s8Zk7MobmegKWZs1MLXKHB+Rrs3N7jYlQ5y/1SzdOtXQCITk37EICFNqlXAhxaum3isdBHnBVZz4gVIhP/m4ubbFj/zWhpiQ30/D9oO+AOkHbJ1Gr+XAruW4cklPg==
    username: AgAvzVcqJHYabtxNh2brfM2660cxkByg6VWVLkq+HndTT3jh3tib2Lv9prPPKmhI9WH4Rkq892/q0PieTM4j0A0ioqxjI1uHijqgrrISuzQMEZXoaq9CZaFRHvxoub9WYMNO6Xa1aBkTvOIlxmqFdirgjh/QA7WuOLWyr341eBbsBE8jVjtqhHDX9q/R9iqJqCXOQf8KKzqXVl9GUAI/f+OFWzwdkwF/WdCECLzeDZWqwCzZ9r4lbIekq26+T7q6/JpUBNl3FQx5TINNAhdHSz3g99CFRDMHQ32KqKX5E4Akhpmqi1l/1SzKTVNVSrG6FjJnKEhoqMQeaw0SChYK+JnpnnwQv7ZP+/dzqAYQJ99i0DKMTawgbOuyI1b1Aw38G8qF1htfGejlbKdAYXLI0sY3neG7ung+5i1ucw3LcdPjlpQ1vgAw8zFSQOBD18oVeYwVWNHZYXE3MqIMVOc+TOVrWHdsl4w3ErWf+tcB5zIvCIGMec/GZB2xcT5stLq51zdrRxGRLXdmGJLChN8VvcHt69FH5qlGi0O2jOU6HI9Y3hxf7x/ujjMsI/lRJWMzzlurdgu2nb348YdQbARpLTa/1Nip4LCug7RV+pdj4WPqYcrBTkHmBCFd5GPKVD3/cI86Ojsh61+dwS/N3JNN83bXvF083a+CfX4fCnzXZMdMyEgQWDkwz+8Sbezi7SC9i8NZShegwThOZEse2hR5WesnEFxtfA==
  template:
    metadata:
      name: mlflow-prod-db-creds
      namespace: mlflow-prod
