---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-prod-db-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAnhJhfDShjBeqjRPnvaJRfLgBg/NSm6wacJW066nBwNyG4ZN1pfWMQVYo3PyhHcO2B7jrqSBGSpuiE8I+L3IK+x6ijsisJAq77h6yZex3ScZw6uCy4fDfKVKYTGUT2O3dPCjW/lYC1fhzIfuaVIMUzfIh+ceGY4ncuwECPyuLRrk3rNr0jazB+jO73WgUZ5qo7IuPO6R8gcFOLkaEaNVjGmIU/gW5F/nw2982hTZzqa/G7DqDFYCaB/k3vsRzwxwGcibZnEi6ShBjHzJrIs30J3Y5nN0JtSE3OP/Wqx7IDyKDJqfB3WVsB+05KU/WVIGsyjfcZw6847+eOrUtlnyJuos29hGK9bd/IUa2pU2G7YfyLUSKA6S8A1PrOCTvNEhYunsboLskqTjxxAiF+SqUAwaeXcm7+cSE7+qjrasGPJ8ek/RBl3rmk4TQmzmPXfXZJBt3uCKSrWCoptFH3wMtV3h3bI565XJiXaXOxvbUN+97z/ZP+wIPA6Q2t2EPOR6oclG/OpNQYoysRx4xRGfTLUqbzHNY4j22ZJz4W5aavq8raVvTF2fR8zFbMboJupKP8gM0xlzu1ZLTHgMiW/cV68J/+SDV5BE4wJZvK880Pa+6zrwMee8n+emv2srkz3kCMbNc24eeceB2jsF+Sl+oVTKE9p2A2n64aFktekU1uk2oqizPv0Hg7JkpN/sDWko9ULlw/A8vUVUQ0Y7nLXdtPVivqh7UxbMheNBFJDRV/wA==
    username: AgBqy3B89/NQHpMEI7O0NDiRWCxnUjDDIOyehZVvMiL446jWIQgYoWDtRROIRkAMo1j98s706vIbkRtpp4XvPYT5//bs8fTFy1N/s25hryLppAHiKS3iBWEKKQ9qsT6QlMsrGDWEyTPBQVoAAnxfosNP3/txv193gjtw1LiNhB+h82ziWf+RJ67NG7GSzqANa37vSWUyqjymGdngAxJnx7wmwkh7w9c+oVJYizg+PgSmjkWVDUL3UESRXiNP1LwFwR0SAS3v1lWybsrddUMUtMJL0BgngqqIdXs1mIVTwlLKSqN53EfYdbZfpkAmdZDo6IP8aquqVZnhqhHwA43ovrSA7RUNswfa/WxZfUZPYjw/otMb1rN1GMgCBK9uvxxZqF3lez8qjw2sldOFNcpGxVIOgk8XtlY5wUpDefWwlBHCYzX5AEotdumL/UM/gmiatZZ7sBCefNWI6urIAceH8BOTylUszC5LZQWsys+f2sBsISEfxf4Zo8nvVerEUkzG3WBF55RP7JM2PqPcvdFWB5mbZI80+5JvphnumnqxzyP+ou8MemTphtQyOouuJk3dLA2PuiJIZSDUCWg0ZqqrOwcSG/3DToGvJeKTeCU/0A5GgsEER1lfNVoXqKwuXJcLk5RW98nWBqQFUSo/7lqgOFYi1Yk7lZEN6hKDvTg6iYxxaQJPTe5Ga0uj1HrKE92pp/PC+VHs7BO2DQTgmbSARFqmUwtv4g==
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-prod-db-creds
      namespace: postgres
